# Generated by Django 5.1 on 2024-09-09 18:16

from django.db import migrations

COUNTRIES = [
    {
        "name": "Afghanistan",
        "alpha2Code": "AF",
        "capital": "Kabul",
        "region": "Asia"
    },
    {
        "name": "Albania",
        "alpha2Code": "AL",
        "capital": "Tirana",
        "region": "Europe"
    },
    {
        "name": "Algeria",
        "alpha2Code": "DZ",
        "capital": "Algiers",
        "region": "Africa"
    },
    {
        "name": "Andorra",
        "alpha2Code": "AD",
        "capital": "Andorra la Vella",
        "region": "Europe"
    },
    {
        "name": "Angola",
        "alpha2Code": "AO",
        "capital": "Luanda",
        "region": "Africa"
    },
    {
        "name": "Antigua and Barbuda",
        "alpha2Code": "AG",
        "capital": "Saint John's",
        "region": "Americas"
    },
    {
        "name": "Argentina",
        "alpha2Code": "AR",
        "capital": "Buenos Aires",
        "region": "Americas"
    },
    {
        "name": "Armenia",
        "alpha2Code": "AM",
        "capital": "Yerevan",
        "region": "Asia"
    },
    {
        "name": "Australia",
        "alpha2Code": "AU",
        "capital": "Canberra",
        "region": "Oceania"
    },
    {
        "name": "Austria",
        "alpha2Code": "AT",
        "capital": "Vienna",
        "region": "Europe"
    },
    {
        "name": "Azerbaijan",
        "alpha2Code": "AZ",
        "capital": "Baku",
        "region": "Asia"
    },
    {
        "name": "Bahamas",
        "alpha2Code": "BS",
        "capital": "Nassau",
        "region": "Americas"
    },
    {
        "name": "Bahrain",
        "alpha2Code": "BH",
        "capital": "Manama",
        "region": "Asia"
    },
    {
        "name": "Bangladesh",
        "alpha2Code": "BD",
        "capital": "Dhaka",
        "region": "Asia"
    },
    {
        "name": "Barbados",
        "alpha2Code": "BB",
        "capital": "Bridgetown",
        "region": "Americas"
    },
    {
        "name": "Belarus",
        "alpha2Code": "BY",
        "capital": "Minsk",
        "region": "Europe"
    },
    {
        "name": "Belgium",
        "alpha2Code": "BE",
        "capital": "Brussels",
        "region": "Europe"
    },
    {
        "name": "Belize",
        "alpha2Code": "BZ",
        "capital": "Belmopan",
        "region": "Americas"
    },
    {
        "name": "Benin",
        "alpha2Code": "BJ",
        "capital": "Porto-Novo",
        "region": "Africa"
    },
    {
        "name": "Bhutan",
        "alpha2Code": "BT",
        "capital": "Thimphu",
        "region": "Asia"
    },
    {
        "name": "Bolivia",
        "alpha2Code": "BO",
        "capital": "Sucre",
        "region": "Americas"
    },
    {
        "name": "Bosnia and Herzegovina",
        "alpha2Code": "BA",
        "capital": "Sarajevo",
        "region": "Europe"
    },
    {
        "name": "Botswana",
        "alpha2Code": "BW",
        "capital": "Gaborone",
        "region": "Africa"
    },
    {
        "name": "Brazil",
        "alpha2Code": "BR",
        "capital": "Brasília",
        "region": "Americas"
    },
    {
        "name": "Brunei",
        "alpha2Code": "BN",
        "capital": "Bandar Seri Begawan",
        "region": "Asia"
    },
    {
        "name": "Bulgaria",
        "alpha2Code": "BG",
        "capital": "Sofia",
        "region": "Europe"
    },
    {
        "name": "Burkina Faso",
        "alpha2Code": "BF",
        "capital": "Ouagadougou",
        "region": "Africa"
    },
    {
        "name": "Burundi",
        "alpha2Code": "BI",
        "capital": "Gitega",
        "region": "Africa"
    },
    {
        "name": "Cabo Verde",
        "alpha2Code": "CV",
        "capital": "Praia",
        "region": "Africa"
    },
    {
        "name": "Cambodia",
        "alpha2Code": "KH",
        "capital": "Phnom Penh",
        "region": "Asia"
    },
    {
        "name": "Cameroon",
        "alpha2Code": "CM",
        "capital": "Yaoundé",
        "region": "Africa"
    },
    {
        "name": "Canada",
        "alpha2Code": "CA",
        "capital": "Ottawa",
        "region": "Americas"
    },
    {
        "name": "Central African Republic",
        "alpha2Code": "CF",
        "capital": "Bangui",
        "region": "Africa"
    },
    {
        "name": "Chad",
        "alpha2Code": "TD",
        "capital": "N'Djamena",
        "region": "Africa"
    },
    {
        "name": "Chile",
        "alpha2Code": "CL",
        "capital": "Santiago",
        "region": "Americas"
    },
    {
        "name": "China",
        "alpha2Code": "CN",
        "capital": "Beijing",
        "region": "Asia"
    },
    {
        "name": "Colombia",
        "alpha2Code": "CO",
        "capital": "Bogotá",
        "region": "Americas"
    },
    {
        "name": "Comoros",
        "alpha2Code": "KM",
        "capital": "Moroni",
        "region": "Africa"
    },
    {
        "name": "Congo (Congo-Brazzaville)",
        "alpha2Code": "CG",
        "capital": "Brazzaville",
        "region": "Africa"
    },
    {
        "name": "Congo (Democratic Republic of the)",
        "alpha2Code": "CD",
        "capital": "Kinshasa",
        "region": "Africa"
    },
    {
        "name": "Costa Rica",
        "alpha2Code": "CR",
        "capital": "San José",
        "region": "Americas"
    },
    {
        "name": "Croatia",
        "alpha2Code": "HR",
        "capital": "Zagreb",
        "region": "Europe"
    },
    {
        "name": "Cuba",
        "alpha2Code": "CU",
        "capital": "Havana",
        "region": "Americas"
    },
    {
        "name": "Cyprus",
        "alpha2Code": "CY",
        "capital": "Nicosia",
        "region": "Asia"
    },
    {
        "name": "Czech Republic",
        "alpha2Code": "CZ",
        "capital": "Prague",
        "region": "Europe"
    },
    {
        "name": "Denmark",
        "alpha2Code": "DK",
        "capital": "Copenhagen",
        "region": "Europe"
    },
    {
        "name": "Djibouti",
        "alpha2Code": "DJ",
        "capital": "Djibouti",
        "region": "Africa"
    },
    {
        "name": "Dominica",
        "alpha2Code": "DM",
        "capital": "Roseau",
        "region": "Americas"
    },
    {
        "name": "Dominican Republic",
        "alpha2Code": "DO",
        "capital": "Santo Domingo",
        "region": "Americas"
    },
    {
        "name": "Ecuador",
        "alpha2Code": "EC",
        "capital": "Quito",
        "region": "Americas"
    },
    {
        "name": "Egypt",
        "alpha2Code": "EG",
        "capital": "Cairo",
        "region": "Africa"
    },
    {
        "name": "El Salvador",
        "alpha2Code": "SV",
        "capital": "San Salvador",
        "region": "Americas"
    },
    {
        "name": "Equatorial Guinea",
        "alpha2Code": "GQ",
        "capital": "Malabo",
        "region": "Africa"
    },
    {
        "name": "Eritrea",
        "alpha2Code": "ER",
        "capital": "Asmara",
        "region": "Africa"
    },
    {
        "name": "Estonia",
        "alpha2Code": "EE",
        "capital": "Tallinn",
        "region": "Europe"
    },
    {
        "name": "Eswatini",
        "alpha2Code": "SZ",
        "capital": "Mbabane",
        "region": "Africa"
    },
    {
        "name": "Ethiopia",
        "alpha2Code": "ET",
        "capital": "Addis Ababa",
        "region": "Africa"
    },
    {
        "name": "Fiji",
        "alpha2Code": "FJ",
        "capital": "Suva",
        "region": "Oceania"
    },
    {
        "name": "Finland",
        "alpha2Code": "FI",
        "capital": "Helsinki",
        "region": "Europe"
    },
    {
        "name": "France",
        "alpha2Code": "FR",
        "capital": "Paris",
        "region": "Europe"
    },
    {
        "name": "Gabon",
        "alpha2Code": "GA",
        "capital": "Libreville",
        "region": "Africa"
    },
    {
        "name": "Gambia",
        "alpha2Code": "GM",
        "capital": "Banjul",
        "region": "Africa"
    },
    {
        "name": "Georgia",
        "alpha2Code": "GE",
        "capital": "Tbilisi",
        "region": "Asia"
    },
    {
        "name": "Germany",
        "alpha2Code": "DE",
        "capital": "Berlin",
        "region": "Europe"
    },
    {
        "name": "Ghana",
        "alpha2Code": "GH",
        "capital": "Accra",
        "region": "Africa"
    },
    {
        "name": "Greece",
        "alpha2Code": "GR",
        "capital": "Athens",
        "region": "Europe"
    },
    {
        "name": "Grenada",
        "alpha2Code": "GD",
        "capital": "St. George's",
        "region": "Americas"
    },
    {
        "name": "Guatemala",
        "alpha2Code": "GT",
        "capital": "Guatemala City",
        "region": "Americas"
    },
    {
        "name": "Guinea",
        "alpha2Code": "GN",
        "capital": "Conakry",
        "region": "Africa"
    },
    {
        "name": "Guinea-Bissau",
        "alpha2Code": "GW",
        "capital": "Bissau",
        "region": "Africa"
    },
    {
        "name": "Guyana",
        "alpha2Code": "GY",
        "capital": "Georgetown",
        "region": "Americas"
    },
    {
        "name": "Haiti",
        "alpha2Code": "HT",
        "capital": "Port-au-Prince",
        "region": "Americas"
    },
    {
        "name": "Honduras",
        "alpha2Code": "HN",
        "capital": "Tegucigalpa",
        "region": "Americas"
    },
    {
        "name": "Hungary",
        "alpha2Code": "HU",
        "capital": "Budapest",
        "region": "Europe"
    },
    {
        "name": "Iceland",
        "alpha2Code": "IS",
        "capital": "Reykjavik",
        "region": "Europe"
    },
    {
        "name": "India",
        "alpha2Code": "IN",
        "capital": "New Delhi",
        "region": "Asia"
    },
    {
        "name": "Indonesia",
        "alpha2Code": "ID",
        "capital": "Jakarta",
        "region": "Asia"
    },
    {
        "name": "Iran",
        "alpha2Code": "IR",
        "capital": "Tehran",
        "region": "Asia"
    },
    {
        "name": "Iraq",
        "alpha2Code": "IQ",
        "capital": "Baghdad",
        "region": "Asia"
    },
    {
        "name": "Ireland",
        "alpha2Code": "IE",
        "capital": "Dublin",
        "region": "Europe"
    },
    {
        "name": "Israel",
        "alpha2Code": "IL",
        "capital": "Jerusalem",
        "region": "Asia"
    },
    {
        "name": "Italy",
        "alpha2Code": "IT",
        "capital": "Rome",
        "region": "Europe"
    },
    {
        "name": "Jamaica",
        "alpha2Code": "JM",
        "capital": "Kingston",
        "region": "Americas"
    },
    {
        "name": "Japan",
        "alpha2Code": "JP",
        "capital": "Tokyo",
        "region": "Asia"
    },
    {
        "name": "Jordan",
        "alpha2Code": "JO",
        "capital": "Amman",
        "region": "Asia"
    },
    {
        "name": "Kazakhstan",
        "alpha2Code": "KZ",
        "capital": "Astana",
        "region": "Asia"
    },
    {
        "name": "Kenya",
        "alpha2Code": "KE",
        "capital": "Nairobi",
        "region": "Africa"
    },
    {
        "name": "Kiribati",
        "alpha2Code": "KI",
        "capital": "Tarawa",
        "region": "Oceania"
    },
    {
        "name": "Kuwait",
        "alpha2Code": "KW",
        "capital": "Kuwait City",
        "region": "Asia"
    },
    {
        "name": "Kyrgyzstan",
        "alpha2Code": "KG",
        "capital": "Bishkek",
        "region": "Asia"
    },
    {
        "name": "Laos",
        "alpha2Code": "LA",
        "capital": "Vientiane",
        "region": "Asia"
    },
    {
        "name": "Latvia",
        "alpha2Code": "LV",
        "capital": "Riga",
        "region": "Europe"
    },
    {
        "name": "Lebanon",
        "alpha2Code": "LB",
        "capital": "Beirut",
        "region": "Asia"
    },
    {
        "name": "Lesotho",
        "alpha2Code": "LS",
        "capital": "Maseru",
        "region": "Africa"
    },
    {
        "name": "Liberia",
        "alpha2Code": "LR",
        "capital": "Monrovia",
        "region": "Africa"
    },
    {
        "name": "Libya",
        "alpha2Code": "LY",
        "capital": "Tripoli",
        "region": "Africa"
    },
    {
        "name": "Liechtenstein",
        "alpha2Code": "LI",
        "capital": "Vaduz",
        "region": "Europe"
    },
    {
        "name": "Lithuania",
        "alpha2Code": "LT",
        "capital": "Vilnius",
        "region": "Europe"
    },
    {
        "name": "Luxembourg",
        "alpha2Code": "LU",
        "capital": "Luxembourg",
        "region": "Europe"
    },
    {
        "name": "Madagascar",
        "alpha2Code": "MG",
        "capital": "Antananarivo",
        "region": "Africa"
    },
    {
        "name": "Malawi",
        "alpha2Code": "MW",
        "capital": "Lilongwe",
        "region": "Africa"
    },
    {
        "name": "Malaysia",
        "alpha2Code": "MY",
        "capital": "Kuala Lumpur",
        "region": "Asia"
    },
    {
        "name": "Maldives",
        "alpha2Code": "MV",
        "capital": "Malé",
        "region": "Asia"
    },
    {
        "name": "Mali",
        "alpha2Code": "ML",
        "capital": "Bamako",
        "region": "Africa"
    },
    {
        "name": "Malta",
        "alpha2Code": "MT",
        "capital": "Valletta",
        "region": "Europe"
    },
    {
        "name": "Marshall Islands",
        "alpha2Code": "MH",
        "capital": "Majuro",
        "region": "Oceania"
    },
    {
        "name": "Mauritania",
        "alpha2Code": "MR",
        "capital": "Nouakchott",
        "region": "Africa"
    },
    {
        "name": "Mauritius",
        "alpha2Code": "MU",
        "capital": "Port Louis",
        "region": "Africa"
    },
    {
        "name": "Mexico",
        "alpha2Code": "MX",
        "capital": "Mexico City",
        "region": "Americas"
    },
    {
        "name": "Micronesia",
        "alpha2Code": "FM",
        "capital": "Palikir",
        "region": "Oceania"
    },
    {
        "name": "Moldova",
        "alpha2Code": "MD",
        "capital": "Chișinău",
        "region": "Europe"
    },
    {
        "name": "Monaco",
        "alpha2Code": "MC",
        "capital": "Monaco",
        "region": "Europe"
    },
    {
        "name": "Mongolia",
        "alpha2Code": "MN",
        "capital": "Ulaanbaatar",
        "region": "Asia"
    },
    {
        "name": "Montenegro",
        "alpha2Code": "ME",
        "capital": "Podgorica",
        "region": "Europe"
    },
    {
        "name": "Morocco",
        "alpha2Code": "MA",
        "capital": "Rabat",
        "region": "Africa"
    },
    {
        "name": "Mozambique",
        "alpha2Code": "MZ",
        "capital": "Maputo",
        "region": "Africa"
    },
    {
        "name": "Myanmar",
        "alpha2Code": "MM",
        "capital": "Naypyidaw",
        "region": "Asia"
    },
    {
        "name": "Namibia",
        "alpha2Code": "NA",
        "capital": "Windhoek",
        "region": "Africa"
    },
    {
        "name": "Nauru",
        "alpha2Code": "NR",
        "capital": "Yaren District",
        "region": "Oceania"
    },
    {
        "name": "Nepal",
        "alpha2Code": "NP",
        "capital": "Kathmandu",
        "region": "Asia"
    },
    {
        "name": "Netherlands",
        "alpha2Code": "NL",
        "capital": "Amsterdam",
        "region": "Europe"
    },
    {
        "name": "New Zealand",
        "alpha2Code": "NZ",
        "capital": "Wellington",
        "region": "Oceania"
    },
    {
        "name": "Nicaragua",
        "alpha2Code": "NI",
        "capital": "Managua",
        "region": "Americas"
    },
    {
        "name": "Niger",
        "alpha2Code": "NE",
        "capital": "Niamey",
        "region": "Africa"
    },
    {
        "name": "Nigeria",
        "alpha2Code": "NG",
        "capital": "Abuja",
        "region": "Africa"
    },
    {
        "name": "North Korea",
        "alpha2Code": "KP",
        "capital": "Pyongyang",
        "region": "Asia"
    },
    {
        "name": "North Macedonia",
        "alpha2Code": "MK",
        "capital": "Skopje",
        "region": "Europe"
    },
    {
        "name": "Norway",
        "alpha2Code": "NO",
        "capital": "Oslo",
        "region": "Europe"
    },
    {
        "name": "Oman",
        "alpha2Code": "OM",
        "capital": "Muscat",
        "region": "Asia"
    },
    {
        "name": "Pakistan",
        "alpha2Code": "PK",
        "capital": "Islamabad",
        "region": "Asia"
    },
    {
        "name": "Palau",
        "alpha2Code": "PW",
        "capital": "Ngerulmud",
        "region": "Oceania"
    },
    {
        "name": "Palestine",
        "alpha2Code": "PS",
        "capital": "Ramallah",
        "region": "Asia"
    },
    {
        "name": "Panama",
        "alpha2Code": "PA",
        "capital": "Panama City",
        "region": "Americas"
    },
    {
        "name": "Papua New Guinea",
        "alpha2Code": "PG",
        "capital": "Port Moresby",
        "region": "Oceania"
    },
    {
        "name": "Paraguay",
        "alpha2Code": "PY",
        "capital": "Asunción",
        "region": "Americas"
    },
    {
        "name": "Peru",
        "alpha2Code": "PE",
        "capital": "Lima",
        "region": "Americas"
    },
    {
        "name": "Philippines",
        "alpha2Code": "PH",
        "capital": "Manila",
        "region": "Asia"
    },
    {
        "name": "Poland",
        "alpha2Code": "PL",
        "capital": "Warsaw",
        "region": "Europe"
    },
    {
        "name": "Portugal",
        "alpha2Code": "PT",
        "capital": "Lisbon",
        "region": "Europe"
    },
    {
        "name": "Qatar",
        "alpha2Code": "QA",
        "capital": "Doha",
        "region": "Asia"
    },
    {
        "name": "Romania",
        "alpha2Code": "RO",
        "capital": "Bucharest",
        "region": "Europe"
    },
    {
        "name": "Russia",
        "alpha2Code": "RU",
        "capital": "Moscow",
        "region": "Europe"
    },
    {
        "name": "Rwanda",
        "alpha2Code": "RW",
        "capital": "Kigali",
        "region": "Africa"
    },
    {
        "name": "Saint Kitts and Nevis",
        "alpha2Code": "KN",
        "capital": "Basseterre",
        "region": "Americas"
    },
    {
        "name": "Saint Lucia",
        "alpha2Code": "LC",
        "capital": "Castries",
        "region": "Americas"
    },
    {
        "name": "Saint Vincent and the Grenadines",
        "alpha2Code": "VC",
        "capital": "Kingstown",
        "region": "Americas"
    },
    {
        "name": "Samoa",
        "alpha2Code": "WS",
        "capital": "Apia",
        "region": "Oceania"
    },
    {
        "name": "San Marino",
        "alpha2Code": "SM",
        "capital": "San Marino",
        "region": "Europe"
    },
    {
        "name": "Sao Tome and Principe",
        "alpha2Code": "ST",
        "capital": "São Tomé",
        "region": "Africa"
    },
    {
        "name": "Saudi Arabia",
        "alpha2Code": "SA",
        "capital": "Riyadh",
        "region": "Asia"
    },
    {
        "name": "Senegal",
        "alpha2Code": "SN",
        "capital": "Dakar",
        "region": "Africa"
    },
    {
        "name": "Serbia",
        "alpha2Code": "RS",
        "capital": "Belgrade",
        "region": "Europe"
    },
    {
        "name": "Seychelles",
        "alpha2Code": "SC",
        "capital": "Victoria",
        "region": "Africa"
    },
    {
        "name": "Sierra Leone",
        "alpha2Code": "SL",
        "capital": "Freetown",
        "region": "Africa"
    },
    {
        "name": "Singapore",
        "alpha2Code": "SG",
        "capital": "Singapore",
        "region": "Asia"
    },
    {
        "name": "Slovakia",
        "alpha2Code": "SK",
        "capital": "Bratislava",
        "region": "Europe"
    },
    {
        "name": "Slovenia",
        "alpha2Code": "SI",
        "capital": "Ljubljana",
        "region": "Europe"
    },
    {
        "name": "Solomon Islands",
        "alpha2Code": "SB",
        "capital": "Honiara",
        "region": "Oceania"
    },
    {
        "name": "Somalia",
        "alpha2Code": "SO",
        "capital": "Mogadishu",
        "region": "Africa"
    },
    {
        "name": "South Africa",
        "alpha2Code": "ZA",
        "capital": "Pretoria",
        "region": "Africa"
    },
    {
        "name": "South Korea",
        "alpha2Code": "KR",
        "capital": "Seoul",
        "region": "Asia"
    },
    {
        "name": "South Sudan",
        "alpha2Code": "SS",
        "capital": "Juba",
        "region": "Africa"
    },
    {
        "name": "Spain",
        "alpha2Code": "ES",
        "capital": "Madrid",
        "region": "Europe"
    },
    {
        "name": "Sri Lanka",
        "alpha2Code": "LK",
        "capital": "Sri Jayawardenepura Kotte",
        "region": "Asia"
    },
    {
        "name": "Sudan",
        "alpha2Code": "SD",
        "capital": "Khartoum",
        "region": "Africa"
    },
    {
        "name": "Suriname",
        "alpha2Code": "SR",
        "capital": "Paramaribo",
        "region": "Americas"
    },
    {
        "name": "Sweden",
        "alpha2Code": "SE",
        "capital": "Stockholm",
        "region": "Europe"
    },
    {
        "name": "Switzerland",
        "alpha2Code": "CH",
        "capital": "Bern",
        "region": "Europe"
    },
    {
        "name": "Syria",
        "alpha2Code": "SY",
        "capital": "Damascus",
        "region": "Asia"
    },
    {
        "name": "Taiwan",
        "alpha2Code": "TW",
        "capital": "Taipei",
        "region": "Asia"
    },
    {
        "name": "Tajikistan",
        "alpha2Code": "TJ",
        "capital": "Dushanbe",
        "region": "Asia"
    },
    {
        "name": "Tanzania",
        "alpha2Code": "TZ",
        "capital": "Dodoma",
        "region": "Africa"
    },
    {
        "name": "Thailand",
        "alpha2Code": "TH",
        "capital": "Bangkok",
        "region": "Asia"
    },
    {
        "name": "Timor-Leste",
        "alpha2Code": "TL",
        "capital": "Dili",
        "region": "Asia"
    },
    {
        "name": "Togo",
        "alpha2Code": "TG",
        "capital": "Lomé",
        "region": "Africa"
    },
    {
        "name": "Tonga",
        "alpha2Code": "TO",
        "capital": "Nuku'alofa",
        "region": "Oceania"
    },
    {
        "name": "Trinidad and Tobago",
        "alpha2Code": "TT",
        "capital": "Port of Spain",
        "region": "Americas"
    },
    {
        "name": "Tunisia",
        "alpha2Code": "TN",
        "capital": "Tunis",
        "region": "Africa"
    },
    {
        "name": "Turkey",
        "alpha2Code": "TR",
        "capital": "Ankara",
        "region": "Asia"
    },
    {
        "name": "Turkmenistan",
        "alpha2Code": "TM",
        "capital": "Ashgabat",
        "region": "Asia"
    },
    {
        "name": "Tuvalu",
        "alpha2Code": "TV",
        "capital": "Funafuti",
        "region": "Oceania"
    },
    {
        "name": "Uganda",
        "alpha2Code": "UG",
        "capital": "Kampala",
        "region": "Africa"
    },
    {
        "name": "Ukraine",
        "alpha2Code": "UA",
        "capital": "Kyiv",
        "region": "Europe"
    },
    {
        "name": "United Arab Emirates",
        "alpha2Code": "AE",
        "capital": "Abu Dhabi",
        "region": "Asia"
    },
    {
        "name": "United Kingdom",
        "alpha2Code": "GB",
        "capital": "London",
        "region": "Europe"
    },
    {
        "name": "United States of America",
        "alpha2Code": "US",
        "capital": "Washington, D.C.",
        "region": "Americas"
    },
    {
        "name": "Uruguay",
        "alpha2Code": "UY",
        "capital": "Montevideo",
        "region": "Americas"
    },
    {
        "name": "Uzbekistan",
        "alpha2Code": "UZ",
        "capital": "Tashkent",
        "region": "Asia"
    },
    {
        "name": "Vanuatu",
        "alpha2Code": "VU",
        "capital": "Port Vila",
        "region": "Oceania"
    },
    {
        "name": "Venezuela",
        "alpha2Code": "VE",
        "capital": "Caracas",
        "region": "Americas"
    },
    {
        "name": "Vietnam",
        "alpha2Code": "VN",
        "capital": "Hanoi",
        "region": "Asia"
    },
    {
        "name": "Yemen",
        "alpha2Code": "YE",
        "capital": "Sana'a",
        "region": "Asia"
    },
    {
        "name": "Zambia",
        "alpha2Code": "ZM",
        "capital": "Lusaka",
        "region": "Africa"
    },
    {
        "name": "Zimbabwe",
        "alpha2Code": "ZW",
        "capital": "Harare",
        "region": "Africa"
    }
]


def load_countries_to_db(apps, schema_editor):
    Country = apps.get_model("accounts", "Country")
    for country_dict in COUNTRIES:
        country = Country(
            name = country_dict["name"],
            code = country_dict["alpha2Code"]
        )
        country.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(load_countries_to_db)
    ]
