# Generated by Django 5.1 on 2024-09-09 19:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20240909_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='preferred_communication',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='state',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TalentAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monday', models.BooleanField(default=False)),
                ('monday_start_time', models.TimeField(default=None, null=True)),
                ('monday_end_time', models.TimeField(default=None, null=True)),
                ('tuesday', models.BooleanField(default=False)),
                ('tuesday_start_time', models.TimeField(default=None, null=True)),
                ('tuesday_end_time', models.TimeField(default=None, null=True)),
                ('wednesday', models.BooleanField(default=False)),
                ('wednesday_start_time', models.TimeField(default=None, null=True)),
                ('wednesday_end_time', models.TimeField(default=None, null=True)),
                ('thursday', models.BooleanField(default=False)),
                ('thursday_start_time', models.TimeField(default=None, null=True)),
                ('thursday_end_time', models.TimeField(default=None, null=True)),
                ('friday', models.BooleanField(default=False)),
                ('friday_start_time', models.TimeField(default=None, null=True)),
                ('friday_end_time', models.TimeField(default=None, null=True)),
                ('saturday', models.BooleanField(default=False)),
                ('saturday_start_time', models.TimeField(default=None, null=True)),
                ('saturday_end_time', models.TimeField(default=None, null=True)),
                ('sunday', models.BooleanField(default=False)),
                ('sunday_start_time', models.TimeField(default=None, null=True)),
                ('sunday_end_time', models.TimeField(default=None, null=True)),
                ('talent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.talent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
