# Generated by Django 5.1 on 2024-09-11 05:56

from django.db import migrations




DEPARTMENT_AND_SKILLS = [
    {
        "Industry": "General Industries",
        "Department": "Information Technology (IT)",
        "Roles": "Chief Information Officer (CIO)\nChief Technology Officer (CTO)\nIT Manager/Director\nSystem Administrator/Network Administrator\nDatabase Administrator (DBA)\nIT Security Specialist/Information Security Analyst\nSoftware Developer/Programmer\nBusiness Analyst\nHelp Desk/Support Technician\nIT Project Manager\nProduct Manager\nQuality Assurance (QA) Analyst/Tester\nData Analyst\nCloud Architect/Administrator\nAI/ML Engineer\nNetwork Engineer\nIT Support Specialist\nIT Auditor\nDesktop Support Technician\nIT Trainer\nTelecommunications Specialist\nSystems Analyst\nWeb Developer\nDevOps Engineer\nCybersecurity Analyst\nEnterprise Architect\nIT Consultant\nMobile App Developer\nIT Operations Manager\nData Scientist\nIT Compliance Officer\nDigital Transformation Manager\nUser Interface (UI) Designer\nUser Experience (UX) Designer\nIT Procurement Specialist\nIT Risk Analyst\nIT Governance Specialist\nIT Change Manager\nIT Financial Analyst\nIT Vendor Manager\nIT Communications Specialist",
        "Tools/Platforms": "Jira, ServiceNow, Microsoft Azure, Group Policy, AWS Management Console, Virtualization Platforms, Google Cloud Console, Docker, Kubernetes, Jenkins, Git, Wireshark, Nagios, SolarWinds, Splunk, Chef, Puppet, Visual Studio Code, Eclipse, PyCharm, IntelliJ IDEA, Git, GitHub, GitLab, Slack, Microsoft Teams, Jira, Asana, Crucible, Microsoft Windows Server, GitHub Pull Requests, Jenkins, Travis CI, CircleCI, Docker, Kubernetes, AWS, Azure, GCP, Prometheus, Grafana, React, Angular, Vue.js, MySQL Workbench, MongoDB Compass, Wireshark, Nmap, Microsoft 365, Windows, Visual Studio, .NET Framework, .NET Core, Azure DevOps, Active Directory, Microsoft Azure, SQL Server, Dynamics 365, Xbox, Azure IoT, Azure Ai, Domain Name System (DNS)",
        "Common Methodologies/Frameworks": "Agile, Scrum, ITIL, SAFe (Scaled Agile Framework), Lean Six Sigma, TOGAF (The Open Group Architecture Framework), COBIT (Control Objectives for Information and Related Technologies), PMBOK (Project Management Body of Knowledge), Kanban, Waterfall, RUP (Rational Unified Process), PRINCE2 (Projects IN Controlled Environments), Lean IT\nLanguages: JavaScript, Python, Java, TypeScript, C#, PHP, HTML, CSS, SQL, Ruby, Swift, Kotlin, Go, C++, Shell scripting (Bash), MATLAB, R, Scala, Groovy, Perl, PowerShell, Objective-C, Apex, Visualforce, ",
        "General Skills": "IT Infrastructure Management, Cybersecurity, Cloud Computing, Database Management, Software Development, IT Project Management, Data Science, Machine Learning, DevOps, Network Security, System Administration, IT Governance, Agile Methodology, Big Data Analytics, Virtualization, Blockchain, Mobile App Development, Web Development, Artificial Intelligence, Robotics, Scripting and Automation, Network Infrastructure, Server Knowledge",
        "Soft Skills": "Problem Solving, Analytical Skills, Attention to Detail, Adaptability, Collaboration, Continuous Learning, Technical Proficiency, Troubleshooting, Creativity, Communication"
    },
    {
        "Industry": "General Industries",
        "Department": "Human Resources (HR)",
        "Roles": "HR Manager\nHR Director\nRecruitment Specialist/Recruiter\nHuman Resources Generalist\nHR Coordinator/Administrator\nEmployee Relations Specialist\nTraining and Development Specialist\nCompensation and Benefits Specialist\nHR Business Partner\nHRIS (Human Resource Information System) Specialist\nLabor Relations Specialist\nOrganizational Development Specialist\nDiversity, Equity, and Inclusion (DEI) Specialist\nCompensation Analyst\nBenefits Administrator\nPerformance Management Specialist\nWellness Coordinator\nHR Compliance Specialist\nTalent Acquisition Manager\nEmployee Engagement Specialist\nChange Management Specialist",
        "Tools/Platforms": "Workday, ADP, BambooHR, Greenhouse, Namely, Paycom, Zenefits, UltiPro, Kronos, PeopleSoft, Bullhorn, Gusto, JazzHR, SmartRecruiters, Lever, Indeed.com, Linkedin Recruiter, ",
        "Common Methodologies/Frameworks": "HR Analytics, HRIS (Human Resource Information System), Employee Life Cycle Models, Workforce Planning Models, Succession Planning Models, Diversity and Inclusion Frameworks, Employee Wellness Models, Recruitment and Selection Models, HR Compliance Frameworks",
        "General Skills": "Legal and Compliance, Employee Benefits, Compensation Management, Performance Management, Employee Training and Development, Talent Management, Employee Engagement, Diversity, Equity, and Inclusion (DEI), Employee Relations, HR Analytics, Change Management, Strategic HR Planning, Health and Safety, Labor Relations, Technology Adoption",
        "Soft Skills": "Communication, Empathy, Conflict Resolution, Interpersonal Skills, Confidentiality, Recruitment Skills, Emotional Intelligence, Time Management, Organizational Skills, Adaptability"
    },
    {
        "Industry": "General Industries",
        "Department": "Finance and Accounting",
        "Roles": "Chief Financial Officer (CFO)\nController\nFinancial Analyst\nAccountant\nAccounts Payable Specialist\nAccounts Receivable Specialist\nPayroll Specialist\nInternal Auditor\nTax Accountant\nBudget Analyst\nTreasury Analyst\nFinance Manager\nCredit Analyst\nCost Accountant\nBookkeeper\nFinancial Planning and Analysis (FP&A) Analyst\nCompliance Officer\nBilling Specialist\nRisk Analyst\nInvestment Analyst",
        "Tools/Platforms": "QuickBooks, SAP, Oracle Financials, Xero, FreshBooks, NetSuite, Wave, Zoho Books, Sage Intacct, Bench, Tally, Expensify, Concur, Stripe, PayPal",
        "Common Methodologies/Frameworks": "GAAP, IFRS, Double-Entry Accounting, Cash Flow Analysis, Cost Accounting, Activity-Based Costing (ABC), Budgeting and Forecasting Models, Financial Modeling, Financial Statement Analysis, Internal Controls, Taxation Frameworks, Auditing Standards, Sarbanes-Oxley Compliance (SOX), Financial Risk Management, Economic Value Added (EVA)",
        "General Skills": "Financial Planning and Analysis, Budgeting, Forecasting, Financial Reporting, Taxation, Audit and Compliance, Risk Management, Treasury Management, Cost Accounting, Management Accounting, Financial Modeling, Cash Flow Management, Internal Controls, Regulatory Compliance, Financial Systems, Payroll Processing, Expense Management, Procurement, Vendor Management",
        "Soft Skills": "Attention to Detail, Analytical Skills, Integrity, Time Management, Adaptability, Numerical Competence, Problem Solving, Decision Making, Communication, Accuracy"
    },
    {
        "Industry": "General Industries",
        "Department": "Sales and Marketing",
        "Roles": "Sales Representative\nAccount Executive\nSales Manager\nMarketing Coordinator\nMarketing Specialist\nDigital Marketing Manager\nContent Marketing Manager\nSocial Media Manager\nBrand Manager\nProject Manager\nMarketing Analyst\nMarket Research Analyst\nSales Operations Analyst\nPublic Relations Specialist\nEvent Coordinator\nInside Sales Representative\nCRM Administrator\nEmail Marketing Specialist\nSEO Specialist\nAdvertising Manager",
        "Tools/Platforms": "Salesforce, HubSpot, Mailchimp, Marketo, Pardot, Google Analytics, SEMrush, Ahrefs, Moz, Buffer, Canva, Hootsuite, Sprout Social, Adobe Creative Cloud, LinkedIn Sales Navigator",
        "Common Methodologies/Frameworks": "Inbound Marketing, Outbound Marketing, Content Marketing, Social Media Marketing, Email Marketing, Search Engine Optimization (SEO), Search Engine Marketing (SEM), Pay-Per-Click (PPC), Google Analytics, Market Research, SWOT Analysis, Sales Funnel Management, Lead Generation, Branding Strategies, Competitive Analysis, Public Relations (PR) Strategies, Campaign Management, Influencer Marketing",
        "General Skills": "Sales Strategy, Lead Generation, Customer Relationship Management (CRM), Sales Enablement, Sales Forecasting, Account Management, Negotiation, Product Knowledge, Market Research, Brand Management, Digital Marketing, Content Marketing, Social Media Marketing, Email Marketing, Marketing Analytics, Advertising, Public Relations, Event Management, Influencer Marketing, Customer Segmentation, Campaign Management",
        "Soft Skills": "Communication, Persuasion, Relationship Building, Adaptability, Creativity, Negotiation Skills, Presentation Skills, Time Management, Active Listening, Teamwork"
    },
    {
        "Industry": "General Industries",
        "Department": "Operations (Physical Products)",
        "Roles": "Operations Manager\nSupply Chain Manager\nLogistics Manager\nWarehouse Manager\nProduction Manager\nQuality Assurance Manager\nDemand Planner\nProcurement Manager\nOperations Analyst\nInventory Manager\nProduct Development Manager\nDistribution Center Manager\nE-commerce Operations Manager\nManufacturing Engineer\nCompliance Manager",
        "Tools/Platforms": "Trello, Asana, Monday.com, Wrike, Smartsheet, Airtable, Microsoft Teams, Basecamp, ClickUp, Jira, TeamViewer, Notion, Evernote, Slack, Confluence, Visual Studio Code, Eclipse, PyCharm, IntelliJ IDEA, Git, GitHub, GitLab, Jenkins, Travis CI, CircleCI, Docker, Kubernetes, AWS, Azure, GCP, Prometheus, Grafana, React, Angular, Vue.js, MySQL Workbench, MongoDB Compass, Wireshark, Nmap",
        "Common Methodologies/Frameworks": "Lean Manufacturing, Six Sigma, 5S, Kanban, Total Quality Management (TQM), Theory of Constraints (TOC), Just-in-Time (JIT), Kaizen, Value Stream Mapping, Manufacturing Resource Planning (MRP II), Statistical Process Control (SPC), Root Cause Analysis, Process Mapping, Failure Mode and Effects Analysis (FMEA), Design for Manufacturability (DFM)",
        "General Skills": "Supply Chain Management, Logistics Planning, Inventory Optimization, Procurement, Distribution, Strategic Sourcing, Contract Negotiation, Vendor Management, International Trade, Customs Compliance, Risk Mitigation, Manufacturing Processes, Lean Manufacturing, Inventory Management, Automation, Process Optimization, Industrial Engineering, CAD/CAM, Machine Operation, Safety Protocols, Materials Handling, Equipment Maintenance, Project Management, Six Sigma,  ISO Standards, Process Improvement, Facilities Management",
        "Soft Skills": "Organization, Problem Solving, Time Management, Decision Making, Attention to Detail, Process Improvement, Strategic Thinking, Adaptability, Critical Thinking, Leadership"
    },
    {
        "Industry": "General Industries",
        "Department": "Operations (Digital Products)",
        "Roles": "Digital Operations Manager\nProduct Manager (Digital)\nAgile Project Manager\nScrum Master\nDevOps Engineer\nRelease Manager\nIT Operations Manager\nData Operations Analyst\nCloud Operations Engineer\nDigital Content Manager\nUser Experience (UX) Manager\nCustomer Support Manager (Digital)\nDigital Marketing Operations Manager\nCybersecurity Operations Manager\nIT Compliance Analyst",
        "Tools/Platforms": "Jira, Trello, Slack, Asana, Confluence, Git/GitHub, AWS (Amazon Web Services), Google Cloud Platform (GCP), Microsoft Azure, Docker, Splunk, New Relic, Zendesk, Salesforce, HubSpot",
        "Common Methodologies/Frameworks": "Agile, Scrum, DevOps, Continuous Integration/Continuous Deployment (CI/CD), Kanban, Lean Software Development, Feature-Driven Development (FDD), Extreme Programming (XP), Test-Driven Development (TDD), Behavior-Driven Development (BDD), Lean Startup, Design Thinking",
        "General Skills": "Project Management, Process Improvement, Strategic Planning, Budgeting, Resource Allocation, Risk Management, Quality Assurance, Vendor Management, Performance Monitoring, Data Analysis, Decision Making, Agile Methodology, DevOps, IT Governance, Cybersecurity, Cloud Computing, Database Management, Software Development, Data Science, Machine Learning, Virtualization, Blockchain, Mobile App Development, Web Development, Artificial Intelligence, Robotics, Scripting and Automation",
        "Soft Skills": "Team Management, Leadership, Communication, Problem-Solving, Adaptability, Time Management, Attention to Detail, Decision-Making, Interpersonal Skills, Conflict Resolution"
    },
    {
        "Industry": "General Industries",
        "Department": "Customer Service/Support",
        "Roles": "Customer Service Representative\nCustomer Support Specialist\nCall Center Supervisor\nCustomer Success Manager\nTechnical Support Engineer\nHelp Desk Analyst\nLive Chat Support Agent\nCustomer Experience Manager\nSupport Team Lead\nClient Services Coordinator\nEscalation Specialist\nService Desk Manager\nContact Center Manager\nCustomer Service Trainer\nSocial Media Customer Support Specialist",
        "Tools/Platforms": "Zendesk, Freshdesk, Intercom, Help Scout, Salesforce Service Cloud, LiveChat, Zoho Desk, Kayako, HappyFox, Front, Jitbit, Desk.com, TeamSupport, Freshservice, Gorgias",
        "Common Methodologies/Frameworks": "ITIL, HDIT, CRM, KCS (Knowledge-Centered Service), Six Sigma, Agile Service Management, Lean Service Management, ISO 18295, COBIT, Customer Effort Score (CES), Net Promoter Score (NPS), Quality Assurance (QA) Frameworks, Call Center Reporting and Analytics, VoC (Voice of the Customer) Programs, COPC (Customer Operations Performance Center) Standards, Service Level Agreements (SLAs)",
        "General Skills": "Technical Support, Call Center Operations, Ticketing Systems, Customer Feedback Analysis, Customer Satisfaction, Service Level Agreements (SLA), Escalation Handling, Cross-functional Collaboration, Training and Development, Quality Assurance in Customer Service, Service Recovery",
        "Soft Skills": "Patience, Empathy, Communication, Problem Solving, Adaptability, Conflict Resolution, Active Listening, Time Management, Flexibility, Positive Attitude, Agile Mindset, Team Collaboration, Attention to Detail, Decision-Making, Innovation, Continuous Learning"
    },
    {
        "Industry": "General Industries",
        "Department": "Research and Development (R&D)",
        "Roles": "Research Scientist\nR&D Manager\nProduct Development Engineer\nResearch Analyst\nInnovation Specialist\nLaboratory Technician\nData Scientist\nBiomedical Engineer\nDesign Engineer\nResearch and Development Coordinator\nClinical Research Associate\nSystems Analyst\nR&D Project Manager\nQuality Assurance Analyst (R&D)\nResearch and Development Director",
        "Tools/Platforms": "MATLAB, LabVIEW, Autodesk, ANSYS, SolidWorks, CATIA, Altium Designer, PTC Creo, COMSOL Multiphysics, Mendeley, EndNote, RefWorks, OriginPro, NVivo, SciFinder, Visual Studio Code, Eclipse, PyCharm, IntelliJ IDEA, Git, GitHub, GitLab, Jira, Asana, Confluence, Notion, Evernote, Slack, Tableau, Power BI, SAS, Apache Hadoop, Apache Spark, KNIME Analytics Platform, Alteryx, Google Analytics, JMP, QlikView, Qlik Sense, IBM SPSS Statistics, D3.js, Looker",
        "Common Methodologies/Frameworks": "Design Thinking, Lean Startup, Feature-Driven Development (FDD), Scrum, Agile Modeling, Extreme Programming (XP), Joint Application Development (JAD), Design Sprint, \nWaterfall Model, Stage-Gate Model, Spiral Model, RAD (Rapid Application Development), Prototype Model, Incremental Model, V-Model, Big Design Up Front (BDUF)",
        "General Skills": "Critical Thinking, Analytical Skills, Experimental Design, Statistical Analysis, Prototyping, Intellectual Property Management, Research Methodologies, Scientific Writing, Data Interpretation, Literature Review, Hypothesis Testing, Laboratory Techniques, Regulatory Compliance, Patent Analysis, Quality Control",
        "Soft Skills": "Analytical Thinking, Creativity, Attention to Detail, Collaboration, Problem Solving, Research Skills, Critical Thinking, Innovation, Adaptability, Scientific Method"
    },
    {
        "Industry": "General Industries",
        "Department": "Production/Manufacturing",
        "Roles": "Production Supervisor\nManufacturing Engineer\nProduction Operator\nQuality Control Inspector\nAssembly Line Worker\nProcess Engineer\nPlant Manager\nCNC Machinist\nIndustrial Engineer\nMaintenance Technician\nProduction Planner\nOperations Technician\nPackaging Technician\nWelder\nFabrication Manager",
        "Tools/Platforms": "SAP ERP, Oracle ERP, MES (Manufacturing Execution System), Plex Systems, Infor CloudSuite Industrial, Epicor ERP, QAD, Fishbowl Manufacturing, IQMS, JobBOSS, Odoo Manufacturing, E2 Manufacturing System, Prodsmart, 3D EXPERIENCE by Dassault Systèmes, FactoryLogix MES",
        "Common Methodologies/Frameworks": "Six Sigma, Lean Manufacturing, Kanban, 5S, Total Quality Management (TQM), Statistical Process Control (SPC), Theory of Constraints (TOC), Value Stream Mapping, Just-In-Time (JIT), Computer-Aided Design (CAD), Computer-Aided Manufacturing (CAM), Manufacturing Execution System (MES), Computer Numerical Control (CNC), Materials Requirement Planning (MRP), Process Failure Mode and Effects Analysis (PFMEA), Design for Manufacturability (DFM), Rapid Prototyping, Continuous Improvement, Robotics and Automation.",
        "General Skills": "Quality Control, Lean Manufacturing, Six Sigma, Process Improvement, Production Planning, Inventory Management, Machine Operation, Root Cause Analysis, Equipment Maintenance, Safety Compliance, Manufacturing Documentation, CNC Machining, Materials Handling, Assembly Line Operations, Welding Techniques, Robotics Programming, Automation Technologies, Supply Chain Optimization, Kaizen Principles, 5S Methodology, Industrial Engineering, Statistical Process Control (SPC), CAD/CAM Software, Manufacturing Execution Systems (MES), Facility Layout Planning, Fixture Design, Injection Molding, Plastics Processing, Metal Stamping, ISO Standards Compliance",
        "Soft Skills": "Attention to Detail, Precision, Time Management, Problem Solving, Adaptability, Technical Skills, Critical Thinking, Teamwork, Organization, Communication"
    },
    {
        "Industry": "General Industries",
        "Department": "Supply Chain and Logistics",
        "Roles": "Supply Chain Manager\nLogistics Coordinator\nWarehouse Manager\nProcurement Specialist\nDistribution Center Manager\nInventory Analyst\nFreight Coordinator\nSupply Chain Analyst\nLogistics Manager\nCustoms Compliance Specialist\nTransportation Planner\nDemand Planner\nReverse Logistics Coordinator\nImport/Export Coordinator\nOrder Fulfillment Specialist",
        "Tools/Platforms": "SAP SCM (Supply Chain Management), Oracle SCM Cloud, Blue Yonder (formerly JDA Software), Kinaxis RapidResponse, Manhattan Associates, Logility, E2open, Elemica, MercuryGate, Llamasoft, Slync.io, FourKites, Transporeon, project44, SAP Integrated Business Planning (IBP)",
        "Common Methodologies/Frameworks": "Lean Supply Chain, Six Sigma, Agile Supply Chain, Just-In-Time (JIT), Demand Planning, Capacity Planning, Inventory Optimization, Warehouse Management System (WMS), Transportation Management System (TMS), Supplier Relationship Management (SRM), Materials Requirement Planning (MRP), Radio-Frequency Identification (RFID), Global Trade Management (GTM), Order Fulfillment, Network Design and Optimization, Reverse Logistics, Cross-Docking, Freight Consolidation, Last-Mile Delivery Optimization, Route Planning and Optimization.",
        "General Skills": "Supply Chain Optimization, Inventory Management, Demand Planning, Logistics Coordination, Transportation Management, Supplier Relationship Management, Procurement, Warehouse Management, Distribution Planning, Forecasting, Customs Compliance, International Trade Regulations, Route Optimization, Cost Reduction Strategies, Vendor Negotiation",
        "Soft Skills": "Organization, Time Management, Attention to Detail, Problem Solving, Analytical Skills, Collaboration, Adaptability, Decision Making, Strategic Planning, Communication"
    },
    {
        "Industry": "General Industries",
        "Department": "Legal",
        "Roles": "Lawyer\nLegal Assistant\nParalegal\nLegal Secretary\nCorporate Counsel\nLegal Consultant\nCompliance Officer\nContract Specialist\nIntellectual Property Attorney\nImmigration Lawyer\nEnvironmental Attorney\nTax Attorney\nFamily Law Attorney\nCourt Clerk\nLegal Researcher",
        "Tools/Platforms": "Clio, LegalZoom, Westlaw, LexisNexis, MyCase, CaseMap, Thomson Reuters Practical Law, Bloomberg Law, ContractSafe, eDiscovery, CaseFleet, LawPay, Zola Suite, Visual Studio Code, Slack, Microsoft Teams, Jira, Asana, Confluence, Notion, Evernote, DocuSign, Adobe Sign, HelloSign, PandaDoc, SignEasy, SignNow, OneSpan Sign, RightSignature, SignRequest, KeepSolid Sign, Zoho Sign, Signable, CocoSign, Formstack Sign, Sertifi",
        "Common Methodologies/Frameworks": "Legal Research Methodologies, Case Management Systems, Document Management Systems, Contract Management Frameworks, E-Discovery Frameworks, Legal Project Management Frameworks, Compliance Management Frameworks, Intellectual Property Management Frameworks, Legal Billing Frameworks, Legal Analytics Frameworks, Legal Process Outsourcing (LPO) Frameworks, Litigation Support Frameworks, Regulatory Compliance Management Frameworks",
        "General Skills": "Legal Research, Contract Drafting, Legal Writing, Litigation Support, Case Management, Intellectual Property Management, Compliance Management, Regulatory Affairs, Due Diligence, Negotiation Skills, Legal Documentation, Corporate Governance, Legal Analysis, Arbitration and Mediation, Legal Project Management",
        "Soft Skills": "Analytical Thinking, Attention to Detail, Research Skills, Communication, Negotiation Skills, Legal Knowledge, Critical Thinking, Time Management, Problem Solving, Ethics"
    },
    {
        "Industry": "General Industries",
        "Department": "Quality Assurance (QA) or Quality Control (QC)",
        "Roles": "Quality Assurance (QA) Manager\nQuality Control (QC) Inspector\nQuality Assurance (QA) Analyst\nQuality Control (QC) Technician\nQuality Assurance (QA) Engineer\nQuality Control (QC) Supervisor\nQuality Assurance (QA) Tester\nQuality Control (QC) Analyst\nQuality Assurance (QA) Auditor\nQuality Control (QC) Engineer\nQuality Assurance (QA) Specialist\nQuality Control (QC) Coordinator\nQuality Assurance (QA) Consultant\nQuality Control (QC) Lab Technician\nQuality Assurance (QA) Trainer",
        "Tools/Platforms": "Jira, TestRail, Zephyr, qTest, Tricentis Tosca, Selenium, Appium, Postman, LoadRunner, TestComplete, Katalon Studio, Ranorex, Miro, Confluence, Bitbucket, Visual Studio Code, Eclipse, PyCharm, IntelliJ IDEA, Git, GitHub, GitLab, Slack, Microsoft Teams, Jira, Asana, Confluence, Notion, Evernote",
        "Common Methodologies/Frameworks": "Call Center Quality Assurance Frameworks, COPC (Customer Operations Performance Center) Standards, Voice of the Customer (VoC) Programs, Customer Satisfaction (CSAT), Net Promoter Score (NPS), Customer Effort Score (CES), First Call Resolution (FCR), Average Handling Time (AHT), Service Level Agreements (SLAs), Quality Monitoring, Speech Analytics, Call Center Reporting and Analytics, Customer Journey Mapping, Customer Feedback Loops, Agent Performance Metrics, KCS (Knowledge-Centered Service), Six Sigma, Lean, ISO Standards, Test-Driven Development (TDD), Agile Testing, Behavior-Driven Development (BDD), Acceptance Test-Driven Development (ATDD), DevOps, Continuous Testing, Shift-Left Testing, Exploratory Testing, Risk-Based Testing, Model-Based Testing, Usability Testing, Performance Testing, Security Testing, Compliance Testing, Regression Testing",
        "General Skills": "Quality Inspection, Statistical Analysis, Root Cause Analysis, Auditing, Process Improvement, Six Sigma, Lean Manufacturing, ISO Standards Compliance, Testing Methodologies, Calibration, Data Analysis, Documentation Control, Continuous Improvement, Non-Destructive Testing (NDT), Failure Mode and Effects Analysis (FMEA)",
        "Soft Skills": "Attention to Detail, Analytical Skills, Problem Solving, Critical Thinking, Precision, Process Improvement, Communication, Adaptability, Time Management, Teamwork"
    },
    {
        "Industry": "General Industries",
        "Department": "Administration",
        "Roles": "Virtual Assistant\nAdministrative Assistant\nExecutive Assistant\nOffice Manager\nAdministrative Coordinator\nReceptionist\nSecretary\nOffice Administrator\nData Entry Clerk\nPersonal Assistant\nFront Desk Coordinator\nClerical Assistant\nAdministrative Specialist\nOffice Clerk\nRecords Coordinator\nAdministrative Support Manager",
        "Tools/Platforms": "Microsoft Office Suite, Google Workspace, Slack, Zoom, Adobe Acrobat, Dropbox, Microsoft SharePoint, Salesforce, Notion, Evernote, Trello, Asana, Calendly, Monday.com, Canva, Adobe Creative Cloud",
        "Common Methodologies/Frameworks": "ISO 9001, Lean Administration, Six Sigma, ISO 27001, ITIL, COBIT, Agile Administration, Scrum, Kanban, Waterfall Model, Business Process Reengineering (BPR), Total Quality Management (TQM), Change Management, Kaizen, Continuous Improvement, Governance Frameworks, Regulatory Compliance Frameworks",
        "General Skills": "Office Management, Time Management, Calendar Management, Record Keeping, Filing Systems, Data Entry, Event Planning, Travel Coordination, Report Generation, Meeting Coordination, Vendor Management, Budget Management, Office Equipment Maintenance, Facilities Coordination, Procurement and Purchasing",
        "Soft Skills": "Organization, Time Management, Communication, Multitasking, Adaptability, Attention to Detail, Problem Solving, Initiative, Flexibility, Decision Making"
    },
    {
        "Industry": "General Industries",
        "Department": "Facilities Management",
        "Roles": "Facilities Manager\nFacilities Coordinator\nFacility Maintenance Technician\nBuilding Manager\nProperty Manager\nFacilities Engineer\nMaintenance Supervisor\nFacility Planner\nEnvironmental Health and Safety (EHS) Coordinator\nGroundskeeper\nSpace Planner\nHVAC Technician\nFacilities Operations Manager\nCustodial Supervisor\nEnergy Manager",
        "Tools/Platforms": "IBM TRIRIGA, Archibus, ServiceChannel, UpKeep, FMX, Hippo CMMS, Maintenance Connection, Fiix, AssetWorks, Planon, AkitaBox, OfficeSpace Software, iOFFICE, OfficeMaps, Robin, Visual Studio Code, Slack, Microsoft Teams, Jira, Asana, Confluence, Notion, Evernote",
        "Common Methodologies/Frameworks": "ISO 41001, CMMS (Computerized Maintenance Management System), IWMS (Integrated Workplace Management System), Total Quality Management (TQM), Lean Management, Six Sigma, Agile Facilities Management, Kanban, Continuous Improvement, Building Information Modeling (BIM), Environmental Management Systems (EMS), Risk Management Frameworks, Energy Management Systems (EnMS), Sustainability Reporting Standards",
        "General Skills": "Building Maintenance, Space Planning, Health and Safety Compliance, Emergency Preparedness, Sustainability Initiatives, Budgeting for Facilities, Energy Management, Vendor Management, Project Management for Facility Upgrades, HVAC Systems Knowledge, Security Systems Management, Workplace Ergonomics, Waste Management, Lease Management, Renovation Planning",
        "Soft Skills": "Organization, Problem Solving, Time Management, Communication, Leadership, Adaptability, Planning, Critical Thinking, Negotiation Skills, Budgeting"
    },
    {
        "Industry": "General Industries",
        "Department": "Public Relations (PR) and Communications",
        "Roles": "Public Relations Manager\nCommunications Specialist\nPR Coordinator\nMedia Relations Manager\nCorporate Communications Manager\nPublicist\nSocial Media Manager\nContent Writer\nPress Secretary\nCommunications Director\nEvent Coordinator\nBrand Manager\nCopywriter\nCrisis Communications Specialist\nInternal Communications Manager",
        "Tools/Platforms": "Meltwater, Cision, Hootsuite, Buffer, Mention, TrendKite (now Cision), Sprout Social, HubSpot, Google Analytics, SEMrush, Canva, Adobe Creative Cloud, Mailchimp, Slack, Microsoft Teams, Jira, Asana, Confluence, Notion, Evernote, Visual Studio Code, GitHub, GitLab, Slack, Microsoft Teams, Jira, Asana, Confluence, Notion, Evernote, LinkedIn, Facebook, Instagram, TikTok, Twitter. ",
        "Common Methodologies/Frameworks": "Crisis Communication Plans, Media Relations Strategies, Social Media Management, Stakeholder Analysis, Reputation Management, Integrated Marketing Communication (IMC), Thought Leadership, Public Affairs",
        "General Skills": "Media Relations, Crisis Communication, Brand Development, Content Creation, Press Release Writing, Event Planning, Public Speaking, Social Media Strategy, Market Research, Stakeholder Engagement, Speechwriting, Community Outreach, Campaign Management, Corporate Communication, Editing and Proofreading",
        "Soft Skills": "Communication, Relationship Building, Writing Skills, Creativity, Adaptability, Networking, Social Media Management, Time Management, Presentation Skills, Strategic Thinking"
    },
    {
        "Industry": "General Industries",
        "Department": "Business Development",
        "Roles": "Business Development Manager\nSales Representative\nAccount Executive\nBusiness Development Executive\nSales Manager\nMarket Research Analyst\nRelationship Manager\nPartnership Manager\nAccount Manager\nSales Consultant\nLead Generation Specialist\nBusiness Development Coordinator\nStrategic Partnerships Manager\nSales Development Representative (SDR)\nCorporate Development Manager",
        "Tools/Platforms": "LinkedIn Sales Navigator, ZoomInfo, Salesforce, HubSpot CRM, Pipedrive, Zoho CRM, Mailchimp, Asana, Trello, Slack, Gong.io, Outreach, Yesware, Crystal, Leadfeeder, Visual Studio Code, Eclipse, PyCharm, IntelliJ IDEA, Git, GitHub, GitLab, Slack, Microsoft Teams, Jira, Asana, Confluence, Notion, Evernote",
        "Common Methodologies/Frameworks": "SWOT Analysis, PESTLE Analysis, Business Model Canvas, Porter's Five Forces, Ansoff Matrix, BANT Criteria, Blue Ocean Strategy, Competitive Intelligence, Customer Segmentation, Value Proposition Canvas, McKinsey 7S Framework, SMART Criteria, Strategic Planning, Market Entry Strategies, Customer Acquisition Cost (CAC), Customer Lifetime Value (CLV), Sales Funnel Analysis, Lead Scoring",
        "General Skills": "Market Research, Sales Strategy, Lead Generation, Partnership Development, Negotiation, Contract Management, Financial Analysis, Competitive Analysis, Strategic Planning, Product Knowledge, Networking, Relationship Building, Customer Acquisition, Proposal Writing, Market Entry Strategy",
        "Soft Skills": "Communication, Negotiation Skills, Relationship Building, Adaptability, Sales Skills, Strategic Thinking, Creativity, Time Management, Decision Making, Networking"
    },
    {
        "Industry": "General Industries",
        "Department": "Compliance",
        "Roles": "Compliance Officer\nCompliance Manager\nRegulatory Affairs Specialist\nCompliance Analyst\nRisk and Compliance Manager\nAML (Anti-Money Laundering) Analyst\nCompliance Consultant\nEthics and Compliance Officer\nPrivacy Officer\nInternal Auditor\nFinancial Compliance Analyst\nCorporate Compliance Specialist\nQuality Assurance and Compliance Manager\nLegal and Compliance Coordinator\nCompliance Investigator",
        "Tools/Platforms": "Compliancy Group, LogicGate, ZenGRC, Reciprocity ZenQMS, MetricStream, ComplianceBridge, Lockpath, Qualys, NAVEX Global, HighBond by Galvanize, VComply, ComplyAssistant, 360factors Predict360, Resolver, Compli, Visual Studio Code, Eclipse, PyCharm, IntelliJ IDEA, Git, GitHub, GitLab, Slack, Microsoft Teams, Jira, Asana, Confluence, Notion, Evernote",
        "Common Methodologies/Frameworks": "SO 19600:2014, ISO 31000:2018, GDPR, SOX, PCI DSS, HIPAA, COBIT, NERC CIP, NIST Cybersecurity Framework, FISMA, ISO 37001, Whistleblower Protection Programs, Compliance Auditing and Monitoring",
        "General Skills": "Regulatory Compliance, Risk Assessment, Policy Development, Auditing, Legal Research, Data Privacy Compliance, Corporate Governance, Anti-Money Laundering (AML) Compliance, Ethical Decision-Making, Internal Controls, Investigation Skills, Contract Compliance, Due Diligence, Quality Assurance, Compliance Reporting",
        "Soft Skills": "Attention to Detail, Analytical Skills, Communication, Integrity, Ethical Decision Making, Legal Knowledge, Adaptability, Time Management, Problem Solving, Decision Making"
    },
    {
        "Industry": "General Industries",
        "Department": "Risk Management",
        "Roles": "Risk Manager\nRisk Analyst\nCredit Risk Analyst\nOperational Risk Manager\nEnterprise Risk Manager\nRisk Consultant\nRisk Assurance Specialist\nFinancial Risk Analyst\nQuantitative Risk Analyst\nInsurance Risk Manager\nCompliance and Risk Officer\nMarket Risk Analyst\nCyber Risk Analyst\nRisk Modeling Analyst\nFraud Risk Manager",
        "Tools/Platforms": "RiskWatch, Riskon, IBM OpenPages, Resolver, Sphera, Riskonnect, MetricStream, LogicManager, Predict360 by 360factors, RiskCloud by LogicGate, NAVEX Global RiskRate, Qualys.",
        "Common Methodologies/Frameworks": "COSO ERM, ISO 31000:2018, FAIR, PMI Risk Management Framework, FERMA Risk Management Standard, NIST Risk Management Framework, RIMS Risk Maturity Model, M_o_R, ISO 27005:2018, AS/NZS 4360:2004, CIA Triad, Bowtie Methodology, Fault Tree Analysis, FMEA, Scenario Analysis, Monte Carlo Simulation",
        "General Skills": "Risk Assessment, Scenario Analysis, Quantitative Analysis, Financial Modeling, Risk Mitigation Strategies, Crisis Management, Business Continuity Planning, Insurance Analysis, Contract Risk Management, Compliance Management, Fraud Detection, Decision-Making under Uncertainty, Enterprise Risk Management (ERM), Incident Response Planning, Market Risk Analysis",
        "Soft Skills": "Analytical Thinking, Problem Solving, Communication, Decision Making, Adaptability, Attention to Detail, Critical Thinking, Time Management, Strategic Planning, Flexibility"
    },
    {
        "Industry": "Healthcare",
        "Department": "Emergency Department (ED)",
        "Roles": "Emergency Physician\nEmergency Nurse\nParamedics/EMTs\nED Technician\nED Manager",
        "Tools/Platforms": "Electronic Health Records (EHR), Clinical Decision Support Systems (CDSS), Medical Imaging Systems, Emergency Department Information Systems (EDIS), Telemedicine Platforms, Patient Monitoring Systems, Medication Administration Systems, Clinical Communication Tools, Charting Software, Mobile Data Terminals (MDTs), Electronic Patient Care Reporting (ePCR), Medical Equipment, Navigation Systems, Radio Communication Systems, Clinical Equipment, Medical Equipment Management Systems, Inventory Management Systems, Healthcare Management Software, Scheduling and Staffing Tools, Performance Metrics Dashboards, Communication and Collaboration Tools",
        "Common Methodologies/Frameworks": "Advanced Trauma Life Support (ATLS), Basic Life Support (BLS), Advanced Cardiac Life Support (ACLS), Clinical Pathways and Protocols, Emergency Nursing Core Competencies, Triage Systems (e.g., Emergency Severity Index - ESI), Trauma Nursing Core Course (TNCC), Patient Safety Protocols, Pre-Hospital Care Protocols, Advanced Life Support (ALS), National EMS Education Standards, Standard Operating Procedures (SOPs), Emergency Care Protocols, Infection Control Procedures, Lean Management, Six Sigma, Quality Improvement Frameworks, Patient Flow Optimization Models, Operational Efficiency Strategies",
        "General Skills": "Clinical Assessment, Emergency Response, Patient Care, Critical Thinking, Problem-Solving, Communication Skills, Team Collaboration, Technical Proficiency, Time Management, Documentation, Medical Knowledge, Decision-Making, Leadership, Stress Management, Multitasking, Patient Advocacy, Data Analysis, Risk Management, Patient Education, Process Improvement",
        "Soft Skills": "Communication, Teamwork, Problem-Solving, Adaptability, Emotional Intelligence, Time Management, Leadership, Conflict Resolution, Stress Management, Critical Thinking, Interpersonal Skills, Empathy, Organizational Skills, Decision-Making, Creativity"
    },
    {
        "Industry": "Healthcare",
        "Department": "Internal Medicine",
        "Roles": "Internist\nMedical Resident\nMedical Assistant\nClinical Coordinator",
        "Tools/Platforms": "Electronic Health Records (EHR), Clinical Decision Support Systems (CDSS), Medical Imaging Systems, Practice Management Software, Patient Portals, Telemedicine Platforms, Medical Charting Software, Scheduling Software, Laboratory Information Systems (LIS), Prescription Management Systems",
        "Common Methodologies/Frameworks": "Clinical Pathways, Evidence-Based Medicine, Patient-Centered Care, Standard Operating Procedures (SOPs), Integrated Care Models, Chronic Disease Management Protocols, Preventive Care Guidelines, Quality Improvement Frameworks, Patient Safety Protocols, Care Coordination Models",
        "General Skills": "Clinical Assessment, Patient Care, Documentation, Diagnosis and Treatment Planning, Coordination of Care, Medical Knowledge, Data Analysis, Problem-Solving, Time Management, Patient Education",
        "Soft Skills": "Communication, Teamwork, Adaptability, Empathy, Emotional Intelligence, Stress Management, Critical Thinking, Interpersonal Skills, Organization, Decision-Making"
    },
    {
        "Industry": "Healthcare",
        "Department": "Surgery",
        "Roles": "Surgeon\nSurgical Nurse\nSurgical Technician\nAnesthesiologist",
        "Tools/Platforms": "Electronic Health Records (EHR), Surgical Instrumentation, Anesthesia Delivery Systems, Medical Imaging Systems, Operating Room Management Software, Patient Monitoring Systems, Surgical Navigation Systems, Sterilization Equipment, Surgical Safety Checklists, Electronic Anesthesia Records",
        "Common Methodologies/Frameworks": "Surgical Protocols, Evidence-Based Surgery Guidelines, Patient Safety Standards, Surgical Checklists (e.g., WHO Surgical Safety Checklist), Perioperative Care Models, Standard Operating Procedures (SOPs), Pain Management Protocols, Infection Control Procedures, Enhanced Recovery After Surgery (ERAS), Quality Improvement Frameworks",
        "General Skills": "Surgical Techniques, Patient Care, Intraoperative Monitoring, Problem-Solving, Coordination of Care, Critical Thinking, Medical Knowledge, Documentation, Anesthesia Management, Time Management",
        "Soft Skills": "Communication, Teamwork, Adaptability, Stress Management, Emotional Intelligence, Leadership, Interpersonal Skills, Attention to Detail, Decision-Making, Empathy"
    },
    {
        "Industry": "Healthcare",
        "Department": "Pediatrics",
        "Roles": "Pediatrician\nPediatric Nurse\nPediatric Resident\nChild Life Specialist",
        "Tools/Platforms": "Electronic Health Records (EHR), Pediatric Medical Equipment, Growth and Development Tracking Tools, Patient Monitoring Systems, Pediatric Imaging Systems, Pediatric Care Management Software, Immunization Registries, Pediatric Charting Software, Telemedicine Platforms, Pediatric Medication Management Systems",
        "Common Methodologies/Frameworks": "Pediatric Clinical Guidelines, Growth and Development Milestones, Evidence-Based Pediatric Care, Pediatric Assessment Protocols, Child-Friendly Communication Techniques, Family-Centered Care Models, Preventive Pediatric Care Guidelines, Standard Operating Procedures (SOPs), Pediatric Pain Management Protocols, Quality Improvement Frameworks",
        "General Skills": "Clinical Assessment, Pediatric Care, Patient and Family Education, Growth and Development Monitoring, Diagnosis and Treatment Planning, Coordination of Care, Documentation, Problem-Solving, Medical Knowledge, Emotional Support",
        "Soft Skills": "Communication, Empathy, Patience, Adaptability, Emotional Intelligence, Teamwork, Stress Management, Interpersonal Skills, Critical Thinking, Compassion"
    },
    {
        "Industry": "Healthcare",
        "Department": "Obstetrics and Gynecology (OB/GYN)",
        "Roles": "OB/GYN Physician\nLabor and Delivery Nurse\nGynecologic Surgeon\nPerinatologist",
        "Tools/Platforms": "Electronic Health Records (EHR), Obstetric and Gynecologic Imaging Systems, Labor and Delivery Management Software, Fetal Monitoring Systems, Surgical Instrumentation, Ultrasound Machines, Patient Monitoring Systems, Electronic Medical Records (EMR), Maternal Health Tracking Tools, Anesthesia Delivery Systems",
        "Common Methodologies/Frameworks": "Obstetric and Gynecologic Clinical Guidelines, Evidence-Based Practice Protocols, Labor and Delivery Protocols, Prenatal and Postnatal Care Models, Standard Operating Procedures (SOPs), Maternal-Fetal Medicine Guidelines, Gynecologic Surgical Protocols, Pain Management Protocols, Risk Assessment Models, Quality Improvement Frameworks",
        "General Skills": "Clinical Assessment, Obstetric and Gynecologic Care, Surgical Techniques, Patient Education, Labor and Delivery Management, Diagnosis and Treatment Planning, Coordination of Care, Documentation, Anesthesia Management, Emergency Response",
        "Soft Skills": "Communication, Empathy, Adaptability, Stress Management, Emotional Intelligence, Teamwork, Decision-Making, Interpersonal Skills, Compassion, Leadership"
    },
    {
        "Industry": "Healthcare",
        "Department": "Cardiology",
        "Roles": "Cardiologist\nCardiac Nurse\nElectrophysiologist\nCardiac Technician",
        "Tools/Platforms": "Electronic Health Records (EHR), Cardiac Imaging Systems, Electrocardiogram (ECG) Machines, Cardiac Monitoring Systems, Cardiac Catheterization Equipment, Stress Testing Systems, Pacemakers and Defibrillators, Cardiology Information Systems, Holter Monitors, Telemedicine Platforms",
        "Common Methodologies/Frameworks": "Cardiac Care Guidelines, Evidence-Based Cardiovascular Medicine, Risk Assessment Models, Heart Failure Management Protocols, Electrophysiology Protocols, Clinical Pathways for Cardiovascular Diseases, Standard Operating Procedures (SOPs), Preventive Cardiology Guidelines, Quality Improvement Frameworks, Patient Safety Protocols",
        "General Skills": "Cardiac Assessment, Patient Care, Diagnosis and Treatment Planning, Electrophysiological Analysis, Monitoring and Interpretation, Medical Knowledge, Coordination of Care, Documentation, Emergency Response, Data Analysis",
        "Soft Skills": "Communication, Empathy, Critical Thinking, Teamwork, Adaptability, Emotional Intelligence, Problem-Solving, Stress Management, Interpersonal Skills, Decision-Making"
    },
    {
        "Industry": "Healthcare",
        "Department": "Oncology",
        "Roles": "Oncologist\nOncology Nurse\nRadiation Therapist\nOncology Pharmacist",
        "Tools/Platforms": "Electronic Health Records (EHR), Oncology Information Systems, Medical Imaging Systems, Chemotherapy Management Software, Patient Portals, Clinical Decision Support Systems (CDSS), Radiation Therapy Planning Software, Infusion Pumps, Chemotherapy Administration Systems, Patient Treatment Planning Systems, Drug Interaction Software, Pharmacy Information Systems",
        "Common Methodologies/Frameworks": "Evidence-Based Oncology Guidelines, Cancer Care Pathways, Tumor Board Protocols, Radiation Therapy Protocols, Evidence-Based Radiation Oncology Guidelines, Chemotherapy Administration Guidelines, Symptom Management Protocols, Drug Interaction Management, Safety and Quality Assurance Protocols, Standard Operating Procedures (SOPs)",
        "General Skills": "Clinical Assessment, Diagnosis and Treatment Planning, Cancer Management, Patient Education, Data Analysis, Coordination of Care, Symptom Management, Chemotherapy Administration, Treatment Planning, Medication Management",
        "Soft Skills": "Communication, Empathy, Critical Thinking, Teamwork, Adaptability, Emotional Intelligence, Problem-Solving, Stress Management, Interpersonal Skills, Attention to Detail"
    },
    {
        "Industry": "Healthcare",
        "Department": "Radiology",
        "Roles": "Radiologist\nRadiologic Technologist\nUltrasound Technician\nRadiology Nurse",
        "Tools/Platforms": "Electronic Health Records (EHR), Medical Imaging Systems, Picture Archiving and Communication Systems (PACS), Radiology Information Systems (RIS), Ultrasound Machines, CT Scanners, MRI Machines, Radiology Workstations, Patient Monitoring Systems, Image Analysis Software",
        "Common Methodologies/Frameworks": "Imaging Protocols, Evidence-Based Imaging Guidelines, Quality Assurance Protocols, Standard Operating Procedures (SOPs), Radiation Safety Standards, Image Interpretation Frameworks, Patient Safety Protocols, Diagnostic Accuracy Protocols, Clinical Pathways",
        "General Skills": "Imaging Techniques, Diagnostic Imaging Interpretation, Patient Care, Equipment Operation, Image Analysis, Documentation, Coordination of Care, Technical Proficiency, Emergency Response, Data Analysis",
        "Soft Skills": "Communication, Attention to Detail, Empathy, Teamwork, Adaptability, Stress Management, Emotional Intelligence, Problem-Solving, Interpersonal Skills, Critical Thinking"
    },
    {
        "Industry": "Healthcare",
        "Department": "Pathology",
        "Roles": "Pathologist\nMedical Laboratory Technician\nCytotechnologist\nHistotechnologist",
        "Tools/Platforms": "Electronic Health Records (EHR), Laboratory Information Systems (LIS), Microscopes, Imaging Systems, Pathology Information Systems, Slide Scanners, Automated Stainers, Tissue Processors, Cytology Preparation Equipment, Data Analysis Software",
        "Common Methodologies/Frameworks": "Pathology Protocols, Evidence-Based Diagnostic Guidelines, Quality Assurance Procedures, Standard Operating Procedures (SOPs), Diagnostic Accuracy Frameworks, Laboratory Safety Standards, Cytology and Histology Techniques, Accreditation Standards, Clinical Pathways",
        "General Skills": "Diagnostic Interpretation, Laboratory Techniques, Tissue and Cell Analysis, Data Analysis, Quality Control, Documentation, Coordination of Care, Equipment Operation, Clinical Assessment, Technical Proficiency",
        "Soft Skills": "Attention to Detail, Communication, Problem-Solving, Adaptability, Critical Thinking, Teamwork, Stress Management, Emotional Intelligence, Interpersonal Skills, Precision"
    },
    {
        "Industry": "Healthcare",
        "Department": "Pharmacy",
        "Roles": "Pharmacist\nPharmacy Technician\nClinical Pharmacist\nPharmacy Manager",
        "Tools/Platforms": "Electronic Health Records (EHR), Pharmacy Management Systems, Prescription Management Systems, Drug Interaction Software, Medication Administration Systems, Automated Dispensing Systems, Inventory Management Software, Clinical Decision Support Systems (CDSS), Pharmacy Information Systems, Patient Portals",
        "Common Methodologies/Frameworks": "Evidence-Based Pharmacotherapy Guidelines, Drug Interaction Management, Medication Safety Protocols, Quality Assurance Procedures, Standard Operating Procedures (SOPs), Pharmaceutical Care Models, Clinical Pharmacy Guidelines, Inventory Management Standards, Risk Management Frameworks",
        "General Skills": "Medication Management, Drug Interaction Analysis, Patient Counseling, Inventory Control, Prescription Processing, Clinical Assessment, Documentation, Coordination with Healthcare Team, Data Analysis, Quality Control",
        "Soft Skills": "Communication, Attention to Detail, Empathy, Problem-Solving, Adaptability, Teamwork, Stress Management, Emotional Intelligence, Leadership, Interpersonal Skills"
    },
    {
        "Industry": "Healthcare",
        "Department": "Nursing",
        "Roles": "Registered Nurse (RN)\nNurse Practitioner (NP)\nLicensed Practical Nurse (LPN)\nNurse Manager",
        "Tools/Platforms": "Electronic Health Records (EHR), Patient Monitoring Systems, Clinical Decision Support Systems (CDSS), Medication Administration Systems, Nursing Documentation Software, Telehealth Platforms, Patient Portals, Scheduling Software, Healthcare Management Systems, Clinical Workflow Tools",
        "Common Methodologies/Frameworks": "Evidence-Based Practice Guidelines, Nursing Care Plans, Patient Safety Protocols, Standard Operating Procedures (SOPs), Quality Improvement Frameworks, Care Coordination Models, Preventive Health Guidelines, Risk Management Procedures, Clinical Pathways, Accreditation Standards",
        "General Skills": "Patient Care, Clinical Assessment, Medication Management, Documentation, Coordination of Care, Diagnosis and Treatment Planning, Patient Education, Critical Thinking, Time Management, Data Analysis",
        "Soft Skills": "Communication, Empathy, Adaptability, Teamwork, Emotional Intelligence, Stress Management, Problem-Solving, Leadership, Interpersonal Skills, Decision-Making"
    },
    {
        "Industry": "Healthcare",
        "Department": "Physical Therapy",
        "Roles": "Physical Therapist (PT)\nPhysical Therapy Assistant (PTA)\nRehabilitation Aide",
        "Tools/Platforms": "Electronic Health Records (EHR), Rehabilitation Management Software, Patient Assessment Tools, Exercise Equipment, Manual Therapy Tools, Patient Portals, Gait Analysis Systems, Treatment Planning Software, Modalities Equipment (e.g., TENS units), Telehealth Platforms",
        "Common Methodologies/Frameworks": "Evidence-Based Practice Guidelines, Rehabilitation Protocols, Patient-Centered Care Models, Standard Operating Procedures (SOPs), Functional Independence Measure (FIM), Outcome Measurement Tools, Therapeutic Exercise Guidelines, Pain Management Protocols, Quality Improvement Frameworks",
        "General Skills": "Patient Assessment, Treatment Planning, Exercise Therapy, Manual Therapy Techniques, Documentation, Coordination of Care, Rehabilitation Techniques, Patient Education, Data Analysis, Equipment Operation",
        "Soft Skills": "Communication, Empathy, Adaptability, Problem-Solving, Attention to Detail, Teamwork, Emotional Intelligence, Stress Management, Interpersonal Skills, Motivation"
    },
    {
        "Industry": "Healthcare",
        "Department": "Psychiatry",
        "Roles": "Psychiatrist\nClinical Psychologist\nMental Health Nurse\nPsychiatric Social Worker",
        "Tools/Platforms": "Electronic Health Records (EHR), Psychological Assessment Tools, Telehealth Platforms, Mental Health Management Software, Patient Portals, Cognitive Behavioral Therapy (CBT) Tools, Diagnostic and Statistical Manual of Mental Disorders (DSM), Psychotherapy Documentation Software",
        "Common Methodologies/Frameworks": "Evidence-Based Practice Guidelines, Cognitive Behavioral Therapy (CBT) Protocols, Psychotherapy Techniques, Standard Operating Procedures (SOPs), Mental Health Assessment Frameworks, Crisis Intervention Models, Quality Improvement Frameworks, Patient Safety Protocols",
        "General Skills": "Patient Assessment, Diagnosis and Treatment Planning, Psychotherapy, Crisis Intervention, Documentation, Coordination of Care, Patient Education, Clinical Assessment, Data Analysis, Therapeutic Techniques",
        "Soft Skills": "Communication, Empathy, Adaptability, Active Listening, Emotional Intelligence, Stress Management, Problem-Solving, Interpersonal Skills, Compassion, Patience"
    },
    {
        "Industry": "Healthcare",
        "Department": "Public Health",
        "Roles": "Public Health Administrator\nEpidemiologist\nHealth Educator\nCommunity Health Worker",
        "Tools/Platforms": "Public Health Management Software, Epidemiology Data Analysis Tools, Health Information Systems, Community Health Platforms, Survey and Data Collection Tools, Health Promotion Software, Geographic Information Systems (GIS), Statistical Analysis Software, Patient Portals, Telehealth Platforms",
        "Common Methodologies/Frameworks": "Evidence-Based Public Health Guidelines, Epidemiological Methods, Community Health Assessment Frameworks, Standard Operating Procedures (SOPs), Health Promotion Models, Risk Assessment Frameworks, Quality Improvement Frameworks, Preventive Health Protocols",
        "General Skills": "Data Analysis, Community Health Assessment, Health Education, Program Development, Epidemiological Research, Public Health Policy, Patient and Community Engagement, Documentation, Coordination of Care, Health Promotion",
        "Soft Skills": "Communication, Empathy, Adaptability, Problem-Solving, Teamwork, Emotional Intelligence, Organizational Skills, Stress Management, Interpersonal Skills, Leadership"
    },
    {
        "Industry": "Healthcare",
        "Department": "Administration",
        "Roles": "Healthcare Administrator\nOffice Manager\nMedical Secretary\nExecutive Director",
        "Tools/Platforms": "Healthcare Management Software, Electronic Health Records (EHR), Practice Management Systems, Scheduling Software, Financial Management Software, Human Resources Systems, Compliance and Regulatory Tools, Data Analysis Software, Patient Portals, Communication Platforms",
        "Common Methodologies/Frameworks": "Healthcare Management Protocols, Quality Improvement Frameworks, Financial Management Standards, Human Resources Policies, Compliance Guidelines, Operational Efficiency Models, Risk Management Frameworks, Strategic Planning",
        "General Skills": "Office Management, Financial Management, Patient and Staff Coordination, Documentation, Strategic Planning, Regulatory Compliance, Data Analysis, Scheduling, Resource Allocation, Communication",
        "Soft Skills": "Leadership, Communication, Organizational Skills, Problem-Solving, Adaptability, Teamwork, Decision-Making, Emotional Intelligence, Stress Management, Interpersonal Skills"
    }
]


def load_objects_to_db(apps, schema_editor):
    Industry = apps.get_model("accounts", "Industry")
    Department = apps.get_model("accounts", "Department")
    Role = apps.get_model("accounts", "Role")
    SkillCategory = apps.get_model("accounts", "SkillCategory")
    Skill = apps.get_model("accounts", "Skill")

    for obj in DEPARTMENT_AND_SKILLS:
        industry, _ = Industry.objects.get_or_create(name=obj["Industry"].strip().title())
        department, _ = Department.objects.get_or_create(name=obj["Department"].strip().title(), industry=industry)
        for role_name in obj["Roles"].split("\n"):
            Role.objects.get_or_create(name=role_name.strip().title(), department=department)
        category_names = ["Tools/Platforms", "Common Methodologies/Frameworks", "General Skills", "Soft Skills"]
        for category_name in category_names:
            skill_category, _ = SkillCategory.objects.get_or_create(name=category_name.strip().title())
            for skill_name in obj[category_name].split(","):
                if skill_name == "":
                    continue
                Skill.objects.get_or_create(name=skill_name.strip().title(), category=skill_category, department=department)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_industry_skillcategory_skillreference_and_more'),
    ]

    operations = [
        migrations.RunPython(load_objects_to_db)
    ]