# Generated by Django 5.1 on 2024-09-11 05:56

from django.db import migrations


from  accounts.constants import DEPARTMENT_AND_SKILLS



def load_objects_to_db(apps, schema_editor):
    Industry = apps.get_model("accounts", "Industry")
    Department = apps.get_model("accounts", "Department")
    Role = apps.get_model("accounts", "Role")
    SkillCategory = apps.get_model("accounts", "SkillCategory")
    Skill = apps.get_model("accounts", "Skill")

    for obj in DEPARTMENT_AND_SKILLS:
        industry, _ = Industry.objects.get_or_create(name=obj["Industry"].strip())
        department, _ = Department.objects.get_or_create(name=obj["Department"].strip(), industry=industry)
        for role_name in obj["Roles"].split("\n"):
            Role.objects.get_or_create(name=role_name.strip().title(), department=department)
        category_names = ["Tools/Platforms", "Common Methodologies/Frameworks", "General Skills", "Soft Skills"]
        for category_name in category_names:
            skill_category, _ = SkillCategory.objects.get_or_create(name=category_name.strip())
            for skill_name in obj[category_name].split(","):
                if skill_name == "":
                    continue
                Skill.objects.get_or_create(name=skill_name.strip(), category=skill_category, department=department)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_industry_skillcategory_skillreference_and_more'),
    ]

    operations = [
        migrations.RunPython(load_objects_to_db)
    ]