# Generated by Django 5.1 on 2024-09-12 14:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20240911_0556'),
        ('core', '0001_initial'),
        ('jobs', '0003_job_avaibility_timezone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlanguage',
            name='language',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='userlanguage',
            name='talent',
        ),
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='role',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='role_type',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='education',
            name='talent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.talent'),
        ),
        migrations.AddField(
            model_name='experience',
            name='annual_salary',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='experience',
            name='annual_salary_bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='experience',
            name='annual_salary_bonus_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annual_salary_bonus_currency', to='core.currency'),
        ),
        migrations.AddField(
            model_name='experience',
            name='annual_salary_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annual_salary_currency', to='core.currency'),
        ),
        migrations.AddField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='employment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.employmenttype'),
        ),
        migrations.AddField(
            model_name='experience',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.joblevel'),
        ),
        migrations.AddField(
            model_name='experience',
            name='talent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.talent'),
        ),
        migrations.AddField(
            model_name='talent',
            name='additional_languages',
            field=models.ManyToManyField(related_name='other_languages', to='core.language'),
        ),
        migrations.AddField(
            model_name='talent',
            name='native_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='native_language', to='core.language'),
        ),
        migrations.AddField(
            model_name='talent',
            name='notice_period_type',
            field=models.CharField(choices=[('DAYS', 'days'), ('WEEKS', 'weeks'), ('MONTH', 'months')], default='months', max_length=32),
        ),
        migrations.AlterField(
            model_name='talent',
            name='gender',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('NON_BINARY', 'non-binary'), ('OTHERS', 'prefer to self describe')], max_length=16),
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(max_length=64)),
                ('industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.industry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='education',
            name='level',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.educationlevel'),
        ),
    ]
