# Generated by Django 5.1 on 2024-09-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userlanguage_language_remove_talent_languages_and_more'),
        ('jobs', '0004_businessmodel_alter_job_minimum_education_level_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='SkillReference',
        ),
        migrations.DeleteModel(
            name='UserLanguage',
        ),
    ]
