# Generated by Django 5.1 on 2024-09-12 14:51

from django.db import migrations


def load_education_level_to_db(apps, schema_editor):
    from accounts.constants import EDUCATION_LEVEL
    EducationLevel = apps.get_model("accounts", "EducationLevel")
    Industry = apps.get_model("accounts", "Industry")
    for level_dict in EDUCATION_LEVEL:
        industry = Industry.objects.filter(name=level_dict["industry"]).first()
        level = EducationLevel(
            industry=industry,
            level=level_dict["education"]
        )
        level.save()

def load_languages_to_db(apps, schema_editor):
    from core.constants import LANGUAGES
    Language = apps.get_model("core", "Language")
    for language in LANGUAGES:
        lang = Language(
            name=language
        )
        lang.save()

def load_job_levels_to_db(apps, schema_editor):
    from jobs.constants import JOB_LEVEL
    JobLevel = apps.get_model("jobs", "JobLevel")
    for level in JOB_LEVEL:
        JobLevel.objects.create(name=level)



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_language_delete_skillreference_and_more'),
    ]

    operations = [
        migrations.RunPython(load_education_level_to_db),
        migrations.RunPython(load_languages_to_db),
        migrations.RunPython(load_job_levels_to_db),
    ]
