# Generated by Django 5.1 on 2024-09-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20240912_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='gender',
            field=models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('NON_BINARY', 'non-binary'), ('OTHERS', 'prefer to self describe')], max_length=32, null=True),
        ),
    ]
