# Generated by Django 5.1 on 2024-09-13 12:14

import accounts.enums
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_talent_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='gender',
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_mode',
            field=models.CharField(choices=accounts.enums.AuthType.choices, default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('NON_BINARY', 'non-binary'), ('OTHERS', 'prefer to self describe')], default='prefer to self describe', max_length=16),
        ),
        migrations.CreateModel(
            name='TalentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_skills', models.JSONField(default=list)),
                ('business_models', models.ManyToManyField(related_name='talent_bm_skills', to='accounts.skill')),
                ('frameworks', models.ManyToManyField(related_name='talent_framework_skills', to='accounts.skill')),
                ('general_skills', models.ManyToManyField(related_name='talent_general_skills', to='accounts.skill')),
                ('soft_skills', models.ManyToManyField(related_name='talent_soft_skills', to='accounts.skill')),
                ('talent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.talent')),
                ('tools', models.ManyToManyField(related_name='talent_tool_skills', to='accounts.skill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
