# Generated by Django 5.1 on 2024-09-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_talent_gender_alter_user_auth_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='profile_completion_stage',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('NON_BINARY', 'non-binary'), ('OTHERS', 'prefer to self describe')], default='prefer to self describe', max_length=32),
        ),
    ]
