# Generated by Django 5.1 on 2024-09-16 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_talent_profile_completion_stage_alter_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='profile_completion_stage',
        ),
    ]
