# Generated by Django 5.1 on 2024-09-18 19:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_talent_profile_completion_stage'),
        ('jobs', '0011_alter_jobpost_annual_bonus_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentskill',
            name='business_models',
        ),
        migrations.RemoveField(
            model_name='talentskill',
            name='frameworks',
        ),
        migrations.RemoveField(
            model_name='talentskill',
            name='general_skills',
        ),
        migrations.RemoveField(
            model_name='talentskill',
            name='soft_skills',
        ),
        migrations.RemoveField(
            model_name='talentskill',
            name='talent',
        ),
        migrations.RemoveField(
            model_name='talentskill',
            name='tools',
        ),
        migrations.AddField(
            model_name='experience',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role'),
        ),
        migrations.AddField(
            model_name='talent',
            name='business_models',
            field=models.ManyToManyField(to='jobs.businessmodel'),
        ),
        migrations.AddField(
            model_name='talent',
            name='skills',
            field=models.ManyToManyField(to='accounts.skill'),
        ),
        migrations.CreateModel(
            name='AdditionalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.talent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TalentAvailableDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=32)),
                ('end_time', models.TimeField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.talent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='TalentAvailability',
        ),
        migrations.DeleteModel(
            name='TalentSkill',
        ),
    ]
