# Generated by Django 5.1 on 2024-10-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_talent_address_talent_viber_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_mode',
            field=models.CharField(choices=[('GOOGLE', 'Google'), ('LINKEDIN', 'LinkedIn'), ('FACEBOOK', 'Facebook'), ('EMAIL', 'email')], default='email', max_length=20),
        ),
    ]
