# Generated by Django 5.1 on 2024-10-11 15:03

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_auth_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='years_of_experience',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat(models.F('first_name'), models.Value(' '), models.F('last_name')), output_field=models.CharField()),
        ),
    ]
