# Generated by Django 5.1 on 2024-11-12 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_talent_years_of_experience_user_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='location',
        ),
        migrations.AddField(
            model_name='business',
            name='address',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.country'),
        ),
        migrations.AlterField(
            model_name='businessuser',
            name='role',
            field=models.CharField(choices=[('owner', 'OWNER'), ('admin', 'ADMIN'), ('team_member', 'TEAM_MEMBER')], max_length=32),
        ),
        migrations.AlterField(
            model_name='talent',
            name='notice_period_type',
            field=models.CharField(choices=[('days', 'DAYS'), ('weeks', 'WEEKS'), ('months', 'MONTH')], default='months', max_length=32),
        ),
        migrations.AlterField(
            model_name='talentavailableday',
            name='day',
            field=models.CharField(choices=[('Monday', 'MONDAY'), ('Tuesday', 'TUESDAY'), ('Wednesday', 'WEDNESDAY'), ('Thursday', 'THURSDAY'), ('Friday', 'FRIDAY'), ('Saturday', 'SATURDAY'), ('Sunday', 'SUNDAY')], max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_mode',
            field=models.CharField(choices=[('Google', 'GOOGLE'), ('LinkedIn', 'LINKEDIN'), ('Facebook', 'FACEBOOK'), ('email', 'EMAIL')], default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('non-binary', 'NON_BINARY'), ('prefer to self describe', 'OTHERS')], default='prefer to self describe', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('business', 'BUSINESS'), ('talent', 'TALENT')], max_length=16, null=True),
        ),
    ]
