# Generated by Django 5.1 on 2024-11-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_business_location_business_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessuser',
            name='role',
            field=models.CharField(choices=[('owner', 'owner'), ('admin', 'admin'), ('team_member', 'team_member')], max_length=32),
        ),
        migrations.AlterField(
            model_name='talent',
            name='notice_period_type',
            field=models.CharField(choices=[('days', 'days'), ('weeks', 'weeks'), ('months', 'months')], default='months', max_length=32),
        ),
        migrations.AlterField(
            model_name='talentavailableday',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_mode',
            field=models.CharField(choices=[('Google', 'Google'), ('LinkedIn', 'LinkedIn'), ('Facebook', 'Facebook'), ('email', 'email')], default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('non-binary', 'non-binary'), ('prefer to self describe', 'prefer to self describe')], default='prefer to self describe', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('business', 'business'), ('talent', 'talent')], max_length=16, null=True),
        ),
    ]
