# Generated by Django 5.1 on 2024-11-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_businessuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_mode',
            field=models.CharField(choices=[('Google', 'Google'), ('LinkedIn', 'LinkedIn'), ('Facebook', 'Facebook'), ('Email', 'Email')], default='Email', max_length=20),
        ),
    ]
