# Generated by Django 5.1 on 2024-11-13 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_user_auth_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessuser',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('pending', 'pending')], default='active', max_length=32),
        ),
        migrations.AlterField(
            model_name='businessuser',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.businessuser'),
        ),
    ]
