# Generated by Django 5.1 on 2024-11-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_business_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessuser',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('pending', 'pending'), ('deleted', 'deleted')], default='active', max_length=32),
        ),
    ]
