# Generated by Django 5.1 on 2024-12-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_businessuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='months_of_experience',
            field=models.FloatField(default=0),
        ),
    ]
