# Generated by Django 5.1 on 2024-12-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_talent_months_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
