# Generated by Django 5.1 on 2025-01-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_talent_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='additional_skills',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='apple_id',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_mode',
            field=models.CharField(choices=[('Google', 'Google'), ('LinkedIn', 'LinkedIn'), ('Facebook', 'Facebook'), ('Apple', 'Apple'), ('Email', 'Email')], default='Email', max_length=20),
        ),
        migrations.DeleteModel(
            name='AdditionalSkill',
        ),
    ]
