# Generated by Django 5.1 on 2024-12-31 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_talent_visible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
    ]
