# Generated by Django 5.1 on 2025-01-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_country_options'),
        ('accounts', '0025_talent_additional_skills_user_apple_id_and_more'),
    ]

    operations = [
    ]
