# Generated by Django 5.1 on 2025-02-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_experience_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercase',
            name='reason',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customercase',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='experience',
            name='annual_salary',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='annual_salary_bonus',
            field=models.FloatField(default=0, null=True),
        ),
    ]
