# Generated by Django 5.1 on 2025-03-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_customercase_reason_alter_customercase_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='postal_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
