# Generated by Django 5.1 on 2025-03-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_talent_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='viber_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='whatsapp_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('business', 'business'), ('talent', 'talent')], max_length=50, null=True),
        ),
    ]
