# Generated by Django 5.1 on 2025-03-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_talent_viber_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='work_model',
            field=models.CharField(choices=[('remote', 'remote'), ('hybrid', 'hybrid'), ('in office', 'in office')], max_length=64, null=True),
        ),
    ]
