# Generated by Django 5.1 on 2025-03-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_talent_work_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessuser',
            name='role',
            field=models.CharField(choices=[('owner', 'owner'), ('admin', 'admin'), ('team_member', 'team_member')], max_length=100),
        ),
        migrations.AlterField(
            model_name='businessuser',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('pending', 'pending'), ('deleted', 'deleted')], default='active', max_length=100),
        ),
        migrations.AlterField(
            model_name='talent',
            name='employment_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='notice_period_type',
            field=models.CharField(choices=[('days', 'days'), ('weeks', 'weeks'), ('months', 'months')], default='months', max_length=50),
        ),
        migrations.AlterField(
            model_name='talentavailableday',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='apple_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_mode',
            field=models.CharField(choices=[('Google', 'Google'), ('LinkedIn', 'LinkedIn'), ('Facebook', 'Facebook'), ('Apple', 'Apple'), ('Email', 'Email')], default='Email', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='facebook_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='google_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
