# Generated by Django 5.1 on 2025-03-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_businessuser_role_alter_businessuser_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='employment_type',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('non-binary', 'non-binary'), ('prefer to self describe', 'prefer to self describe')], default='prefer to self describe', max_length=100),
        ),
    ]
