# Generated by Django 5.1 on 2025-03-20 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_businessuser_role_alter_businessuser_status_and_more'),
        ('jobs', '0050_alter_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='employment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.employmenttype'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('non-binary', 'non-binary'), ('prefer to self describe', 'prefer to self describe')], default='prefer to self describe', max_length=100),
        ),
    ]
