# Generated by Django 5.1 on 2025-03-20 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_talent_employment_type_alter_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='employment_type',
        ),
    ]
