# Generated by Django 5.1 on 2025-03-20 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_remove_talent_employment_type_alter_user_gender'),
        ('jobs', '0050_alter_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='employment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.employmenttype'),
        ),
    ]
