# Generated by Django 5.1 on 2025-03-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_talent_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='size',
            field=models.CharField(null=True),
        ),
    ]
