# Generated by Django 5.1 on 2025-03-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_experience_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercase',
            name='reason',
            field=models.CharField(choices=[('Technical Issues', 'Technical Issues'), ('System Help', 'System Help'), ('Report a Business', 'Report a Business'), ('Others', 'Others')], max_length=255),
        ),
    ]
