# Generated by Django 5.1 on 2025-03-25 08:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_business_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='business',
            name='size',
            field=models.CharField(choices=[('0-10 Employees', '0-10 Employees'), ('11-50 Employees', '11-50 Employees'), ('51-250 Employees', '51-250 Employees'), ('251-1000 Employees', '251-1000 Employees'), ('1001-5000 Employees', '1001-5000 Employees'), ('5001-10,000 Employees', '5001-10,000 Employees'), ('10,001+ Employees', '10,001+ Employees')], null=True),
        ),
    ]
