# Generated by Django 5.1 on 2025-03-25 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_businessindustry_alter_business_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='industry',
        ),
    ]
