# Generated by Django 5.1 on 2025-03-25 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_remove_business_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.businessindustry'),
        ),
    ]
