# Generated by Django 5.1 on 2025-03-25 08:51

from django.db import migrations


INDUSTRIES = [
    "Accommodation and Food Services",
    "Administrative and Support Services",
    "Construction",
    "Consumer Services",
    "Education",
    "Entertainment Providers",
    "Farming, Ranching, Forestry",
    "Financial Services",
    "Government Administration",
    "Holding Companies",
    "Hospitals and Health Care",
    "Manufacturing",
    "Oil, Gas, and Mining",
    "Professional Services",
    "Real Estate and Equipment Rental Services",
    "Retail",
    "Technology, Information and Media",
    "Transportation, Logistics, Supply Chain and Storage",
    "Utilities",
    "Wholesale",
]


def load_business_industries(apps, schema_editor):
    BusinessIndustry = apps.get_model("accounts", "BusinessIndustry")
    for i in INDUSTRIES:
        BusinessIndustry.objects.create(
            name=i
        )



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_business_industry'),
    ]

    operations = [
        migrations.RunPython(load_business_industries)
    ]
