# Generated by Django 5.1 on 2025-03-25 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_experience_end_date'),
        ('accounts', '0039_auto_20250325_0851'),
    ]

    operations = [
    ]
