# Generated by Django 5.1 on 2025-03-26 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_customercase_reason'),
        ('accounts', '0040_merge_20250325_1119'),
    ]

    operations = [
    ]
