# Generated by Django 5.1 on 2025-03-27 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_alter_businessuser_added_by_alter_businessuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='talent_viewers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='talent',
            name='address',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='city',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='instagram',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='postal_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='state',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='twitter_x',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='viber_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='whatsapp_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
