# Generated by Django 5.1 on 2025-04-07 03:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_talent_viewers_alter_talent_address_alter_talent_bio_and_more'),
        ('core', '0004_alter_language_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=128, null=True)),
                ('maximum_notice_period', models.PositiveSmallIntegerField(null=True)),
                ('work_structure', models.CharField(choices=[('remote', 'remote'), ('hybrid', 'hybrid'), ('in office', 'in office')], max_length=100, null=True)),
                ('business_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.businessuser')),
                ('educational_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.educationlevel')),
                ('industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.industry')),
                ('languages', models.ManyToManyField(to='core.language')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role')),
                ('skills', models.ManyToManyField(to='accounts.skill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
