# Generated by Django 5.1 on 2025-04-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_talentfilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='photo',
            field=models.ImageField(null=True, upload_to='talents'),
        ),
    ]
