# Generated by Django 5.1 on 2025-04-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_alter_business_name'),
        ('accounts', '0045_alter_talent_photo'),
    ]

    operations = [
    ]
