# Generated by Django 5.1 on 2025-05-08 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_merge_20250422_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='cv',
            field=models.FileField(null=True, upload_to='cvs'),
        ),
    ]
