# Generated by Django 5.1 on 2025-05-26 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_talent_role_alter_talent_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentfilter',
            name='name',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='talentfilter',
            name='business_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.businessuser'),
        ),
    ]
