# Generated by Django 5.1 on 2025-06-30 14:36

from django.db import migrations

def create_default_workflows(apps, schema_editor):
    from accounts.services import create_business_workflows
    Business = apps.get_model("accounts", "Business")

    for business in Business.objects.all():
        create_business_workflows(business.id)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_auto_20250620_1341'),
    ]

    operations = [
        migrations.RunPython(create_default_workflows)
    ]
