# Generated by Django 5.1 on 2025-07-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_auto_20250630_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationlevel',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
