# Generated by Django 5.1 on 2025-07-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_auto_20250630_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='external_id',
            field=models.IntegerField(null=True),
        ),
    ]
