# Generated by Django 5.1 on 2025-07-25 14:52

import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_educationlevel_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='availability_timezone',
            field=timezone_field.fields.TimeZoneField(default='America/Vancouver'),
        ),
        migrations.AddField(
            model_name='talentavailableday',
            name='utc_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='talentavailableday',
            name='utc_start_time',
            field=models.TimeField(null=True),
        ),
    ]
