# Generated by Django 5.1 on 2025-07-25 06:51

from django.db import migrations
from accounts.enums import BusinessUserRoleType
from django.db.models import Case, When, F, ExpressionWrapper, Q, CharField, Value


def update_business_user_roles(apps, schema_editor):
    BusinessUser = apps.get_model("accounts", "BusinessUser")
    BusinessUser.objects.update(role=Case(
        When(Q(role=BusinessUserRoleType.ADMIN.value), then=Value(BusinessUserRoleType.TALENT_MANAGER.value)),
        When(Q(role=BusinessUserRoleType.TEAM_MEMBER.value), then=Value(BusinessUserRoleType.RECRUITER.value)),
        default=F("role"),
        output_field=CharField()
    ))


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_country_external_id'),
    ]

    operations = [
        migrations.RunPython(update_business_user_roles)
    ]
