# Generated by Django 5.1 on 2025-07-25 10:54
import logging

from django.db import migrations
from django.db.migrations import RunPython


def delete_invalid_countries(apps, schema_editor):
    Country = apps.get_model('accounts', 'Country')
    queryset = Country.objects.filter(external_id__isnull=True)
    count = queryset.count()
    queryset.delete()
    logging.info("Deleted %d invalid countries", count)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_country_external_id'),
    ]

    operations = [
        RunPython(delete_invalid_countries)
    ]
