# Generated by Django 5.1 on 2025-07-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_auto_20250725_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercase',
            name='reason',
            field=models.CharField(choices=[('Technical Issues', 'Technical Issues'), ('System Help', 'System Help'), ('Report a Business', 'Report a Business'), ('Report a Talent', 'Report a Talent'), ('Other', 'Other')], max_length=255),
        ),
    ]
