# Generated by Django 5.1 on 2025-07-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_auto_20250725_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='flexible_availability',
            field=models.BooleanField(default=False),
        ),
    ]
