# Generated by Django 5.1 on 2025-07-25 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_auto_20250725_0651'),
        ('accounts', '0054_alter_customercase_reason'),
    ]

    operations = [
    ]
