# Generated by Django 5.1 on 2025-07-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_merge_20250725_1628'),
        ('accounts', '0056_auto_20250726_1442'),
    ]

    operations = [
    ]
