# Generated by Django 5.1 on 2025-07-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_merge_20250726_1902'),
        ('jobs', '0076_merge_20250726_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='employment_type',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='work_model',
        ),
        migrations.AddField(
            model_name='talent',
            name='employment_types',
            field=models.ManyToManyField(blank=True, to='jobs.employmenttype'),
        ),
        migrations.AddField(
            model_name='talent',
            name='work_models',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='businessuser',
            name='role',
            field=models.CharField(blank=True, choices=[('owner', 'owner'), ('admin', 'admin'), ('team_member', 'team_member'), ('talent_manager', 'talent_manager'), ('recruiter', 'recruiter')], max_length=100),
        ),
    ]
