# Generated by Django 5.1 on 2025-07-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_remove_talent_employment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
