# Generated by Django 5.1 on 2025-07-31 13:25

from django.db import migrations
from django.db.models import Q


def delete_none_education_level(apps, schema_editor):
    EducationLevel = apps.get_model('accounts', 'EducationLevel')
    EducationLevel.objects.filter(Q(level=None)|Q(level__iexact="None")).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_user_phone_code'),
    ]

    operations = [
        migrations.RunPython(delete_none_education_level)
    ]
