# Generated by Django 5.1 on 2025-08-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_country_phone_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('non-binary', 'non-binary'), ('prefer to self describe', 'prefer to self describe')], default='prefer to self describe', max_length=100, null=True),
        ),
    ]
