# Generated by Django 5.1 on 2025-08-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('non-binary', 'non-binary'), ('prefer to self describe', 'prefer to self describe')], default='prefer to self describe', max_length=100),
        ),
    ]
