# Generated by Django 5.1 on 2025-09-29 10:43

from django.db import migrations

from helpers.utils import capitalize_bracketed


def update_skills_and_departments(apps, schema_editor):
    Skill = apps.get_model('accounts', 'Skill')
    Department = apps.get_model('accounts', 'Department')
    models = [Skill, Department]

    for model in models:
        items = model.objects.filter(name__icontains="-").iterator()

        for item in items:
            name = item.name.replace("-", " ")
            if model.objects.filter(name__iexact=name).exists():
                item.delete()

        items = model.objects.filter(name__icontains="(").iterator()

        for item in items:
            item.name = capitalize_bracketed(item.name)
            item.save(update_fields=["name"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_alter_user_gender'),
    ]

    operations = [
        migrations.RunPython(update_skills_and_departments),
    ]
