# Generated by Django 5.1 on 2025-10-02 09:36

from django.db import migrations


def add_virtual_assistant(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    Department = apps.get_model('accounts', 'Department')
    Industry = apps.get_model('accounts', 'Industry')
    if not Role.objects.filter(name__iexact='Virtual Assistant').exists():
        industry = Industry.objects.filter(name__iexact='General Industries').first()
        if not industry:
            industry = Industry.objects.create(name='General Industries')
        department = Department.objects.filter(name__iexact='Administration', industry=industry).first()
        if not department:
            department = Department.objects.create(name='Administration', industry=industry)
        Role.objects.create(name='Virtual Assistant', department=department)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_alter_education_end_date'),
    ]

    operations = [
        migrations.RunPython(add_virtual_assistant),
    ]
