# Generated by Django 5.1 on 2025-10-02 16:56

from django.db import migrations

from helpers.utils import capitalize_bracketed


def update_roles(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    items = Role.objects.filter(name__icontains="(").iterator()

    for item in items:
        item.name = capitalize_bracketed(item.name)
        item.save(update_fields=["name"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_auto_20251002_1036'),
    ]

    operations = [
        migrations.RunPython(update_roles),
    ]
