# Generated by Django 5.1 on 2025-10-06 16:40

from django.db import migrations

from helpers.utils import uppercase_first_word


def update_skills_and_departments(apps, schema_editor):
    Skill = apps.get_model('accounts', 'Skill')
    Department = apps.get_model('accounts', 'Department')
    Role = apps.get_model('accounts', 'Role')
    models = [Skill, Department, Role]

    for model in models:
        items = model.objects.filter(name__icontains="(").iterator()

        for item in items:
            item.name = uppercase_first_word(item.name)
            item.save(update_fields=["name"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_auto_20251002_1756'),
    ]

    operations = [
        migrations.RunPython(update_skills_and_departments),
    ]
