# Generated by Django 5.1 on 2025-10-07 11:00

from django.db import migrations


class Migration(migrations.Migration):

    def load_objects_to_db(apps, schema_editor):
        from accounts.constants import DEPARTMENT_AND_SKILLS

        Industry = apps.get_model("accounts", "Industry")
        Department = apps.get_model("accounts", "Department")
        Role = apps.get_model("accounts", "Role")
        SkillCategory = apps.get_model("accounts", "SkillCategory")
        Skill = apps.get_model("accounts", "Skill")

        def clean_value(value):
            value = value.strip()
            if "\n" in value:
                return
            if value == "":
                return
            return value

        for obj in DEPARTMENT_AND_SKILLS:
            industry_value = clean_value(obj["Industry"])
            if not industry_value:
                continue
            industry = Industry.objects.filter(name__iexact=industry_value).first()
            if not industry:
                continue
            industry.name = industry_value
            industry.save(update_fields=["name"])
            department_value = clean_value(obj["Department"])
            if not department_value:
                continue
            department = Department.objects.filter(name__iexact=department_value, industry=industry).first()
            if not department:
                continue
            department.name = department_value
            department.save(update_fields=["name"])
            for role_name in obj["Roles"].split("\n"):
                role_value = clean_value(role_name)
                if not role_value:
                    continue

                role = Role.objects.filter(name__iexact=role_value, department=department).first()
                if not role:
                    continue
                role.name = role_value
                role.save(update_fields=["name"])

            category_names = ["Tools/Platforms", "Common Methodologies/Frameworks", "General Skills", "Soft Skills"]
            for category_name in category_names:
                skill_category = SkillCategory.objects.filter(name__iexact=category_name).first()
                if not skill_category:
                    continue
                skill_category.name = category_name.strip()
                skill_category.save(update_fields=["name"])
                for skill_name in obj[category_name].split(","):
                    if skill_name == "":
                        continue
                    skill_value = clean_value(skill_name)
                    if not skill_value:
                        continue
                    skill = Skill.objects.filter(name__iexact=skill_value, category=skill_category,
                                                 department=department).first()
                    if not skill:
                        continue
                    skill.name = skill_value
                    skill.save(update_fields=["name"])

    dependencies = [
        ('accounts', '0068_auto_20251006_1740'),
    ]

    operations = [
        migrations.RunPython(load_objects_to_db),
    ]
