# Generated by Django 5.1 on 2025-10-17 14:20

from django.db import migrations


def load_objects_to_db(apps, schema_editor):
	from accounts.constants import DEPARTMENT_AND_SKILLS


	Industry = apps.get_model("accounts", "Industry")
	Department = apps.get_model("accounts", "Department")
	Role = apps.get_model("accounts", "Role")
	SkillCategory = apps.get_model("accounts", "SkillCategory")
	Skill = apps.get_model("accounts", "Skill")

	def clean_value(value):
		value = value.strip()
		if "\n" in value:
			return
		if value == "":
			return
		return value

	skill_list = set()
	role_list = set()
	for obj in DEPARTMENT_AND_SKILLS:
		industry_value = clean_value(obj["Industry"])
		if not industry_value:
			continue

		industries = Industry.objects.filter(name__iexact=industry_value)
		industry = industries.first()
		if industries.count() > 0:
			industries.exclude(id=industry.id).delete()
		else:
			industry = Industry.object.create(name=industry_value)
		department_value = clean_value(obj["Department"])
		if not department_value:
			continue
		departments = Department.objects.filter(name__iexact=department_value, industry=industry)
		department = departments.first()
		if departments.count() > 0:
			departments.exclude(id=department.id).delete()
		else:
			department = Department.objects.create(name=department_value, industry=industry)

		for role_name in obj["Roles"].split("\n"):
			role_value = clean_value(role_name)
			if not role_value:
				continue

			roles = Role.objects.filter(name__iexact=role_value).order_by("name")
			role = roles.first()
			role_list.add(role_value)

			if roles.count() > 0:
				roles.exclude(id=role.id).delete()
			else:
				Role.objects.create(name=role_value, department=department)

		category_names = ["Tools/Platforms", "Common Methodologies/Frameworks", "General Skills", "Soft Skills"]
		for category_name in category_names:
			skill_categories = SkillCategory.objects.filter(name__iexact=category_name)
			skill_category = skill_categories.first()
			if skill_categories.count():
				skill_categories.exclude(id=skill_category.id).delete()
			else:
				skill_category = SkillCategory.objects.create(name=category_name.strip())
			for skill_name in obj[category_name].split(","):
				if skill_name == "":
					continue
				skill_value = clean_value(skill_name)
				if not skill_value:
					continue
				skills = Skill.objects.filter(name__iexact=skill_value)
				skill = skills.first()
				skill_list.add(skill_value)
				if skills.count() > 0:
					skills.exclude(id=skill.id).delete()
				else:
					Skill.objects.create(name=skill_value, category=skill_category,
					                     department=department)
		Skill.objects.exclude(name__in=skill_list).delete()
		Role.objects.exclude(name__in=role_list).delete()

class Migration(migrations.Migration):

	dependencies = [
		('accounts', '0070_alter_user_gender_businessclient'),
	]

	operations = [
		migrations.RunPython(load_objects_to_db)
	]
