# Generated by Django 5.1 on 2025-10-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_alter_user_gender_businessclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('Prefer not to say', 'Prefer not to say'), ('others', 'others')], default='others', max_length=100),
        ),
    ]
