# Generated by Django 5.1 on 2025-10-20 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_alter_user_gender'),
        ('accounts', '0071_auto_20251017_1420'),
    ]

    operations = [
    ]
