# Generated by Django 5.1 on 2025-10-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_merge_0071_alter_user_gender_0071_auto_20251017_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='skills',
            field=models.ManyToManyField(blank=True, to='accounts.skill'),
        ),
    ]
