# Generated by Django 5.1 on 2025-10-21 16:23

import core.enums
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0073_alter_talent_skills'),
        ('core', '0013_auto_20251014_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='annual_salary',
            new_name='salary',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='annual_salary_bonus',
            new_name='salary_bonus',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='annual_salary_bonus_currency',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='annual_salary_currency',
        ),
        migrations.AddField(
            model_name='experience',
            name='salary_bonus_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_bonus_currency', to='core.currency'),
        ),
        migrations.AddField(
            model_name='experience',
            name='salary_bonus_type',
            field=models.CharField(choices=[('Hourly', 'Hourly'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi-Weekly'), ('Monthly', 'Monthly'), ('Bi-Monthly', 'Bi-Monthly'), ('Annually', 'Annually')], default=core.enums.SalaryType['ANNUALLY'], max_length=50),
        ),
        migrations.AddField(
            model_name='experience',
            name='salary_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_currency', to='core.currency'),
        ),
        migrations.AddField(
            model_name='experience',
            name='salary_type',
            field=models.CharField(choices=[('Hourly', 'Hourly'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi-Weekly'), ('Monthly', 'Monthly'), ('Bi-Monthly', 'Bi-Monthly'), ('Annually', 'Annually')], default=core.enums.SalaryType['ANNUALLY'], max_length=50),
        ),
    ]
