# Generated by Django 5.1 on 2025-10-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0074_rename_annual_salary_experience_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='salary_bonus_type',
            field=models.CharField(choices=[('Hourly', 'Hourly'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi-Weekly'), ('Monthly', 'Monthly'), ('Bi-Monthly', 'Bi-Monthly'), ('Annually', 'Annually')], default='Annually', max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='salary_type',
            field=models.CharField(choices=[('Hourly', 'Hourly'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi-Weekly'), ('Monthly', 'Monthly'), ('Bi-Monthly', 'Bi-Monthly'), ('Annually', 'Annually')], default='Annually', max_length=50),
        ),
    ]
