# Generated by Django 5.1 on 2025-10-30 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0076_alter_experience_salary_bonus_type_and_more'),
        ('core', '0013_auto_20251014_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='city_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.city'),
        ),
        migrations.AddField(
            model_name='talent',
            name='state_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.state'),
        ),
    ]
