# Generated by Django 5.1 on 2025-10-30 07:31

from django.db import migrations
from django.db.models import Q


def update_city_and_state_object(apps, schema_editor):
    City = apps.get_model('core', 'City')
    Talent = apps.get_model('accounts', 'Talent')
    State   = apps.get_model('core', 'State')
    

    talents = Talent.objects.all()
    for talent in talents:
        if talent.city:
            city = City.objects.filter(Q(name__iexact=talent.city)|Q(uid=talent.city))
            if talent.country:
                city = city.filter(state__country_id=talent.country.id)
            city = city.first()
            if city:
                talent.city_obj = city
        
        if talent.state:
            state = State.objects.filter(Q(name__iexact=talent.state)|Q(uid=talent.state))
            if talent.country:
                state = state.filter(country=talent.country)
            state = state.first()
            if state:
                talent.state_obj = state
        
        talent.save()
    

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_talent_city_obj_talent_state_obj'),
    ]

    operations = [
        migrations.RunPython(update_city_and_state_object),
    ]
