# Generated by Django 5.1 on 2025-11-17 14:21

from django.db import migrations
from django.db.models import Q, F


def update_state_and_city_object(apps, schema_editor):
    
    Talent = apps.get_model("accounts", "Talent")
    City = apps.get_model("core", "City")
    State = apps.get_model("core", "State")
    
    Talent.objects.filter(state__isnull=False).update(
        state_obj=State.objects.filter(Q(uid=F("state"))|Q(name__iexact=F("state"))).first()
    )
    Talent.objects.filter(city__isnull=False).update(
        city_obj=City.objects.filter(Q(uid=F("city")) | Q(name__iexact=F("city"))).first()
    )
    

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_talent_city_obj_talent_state_obj'),
    ]

    operations = [
        migrations.RunPython(update_state_and_city_object)
    ]
