# Generated by Django 5.1 on 2025-11-17 14:21

from django.db import migrations
from django.db.models import Q, F, OuterRef


def update_state_and_city_object(apps, schema_editor):
    
    Talent = apps.get_model("accounts", "Talent")
    City = apps.get_model("core", "City")
    State = apps.get_model("core", "State")
    
    for talent in Talent.objects.filter(Q(state__isnull=False)|Q(city__isnull=False)).iterator():
        if talent.state:
            talent.state_obj=State.objects.filter(Q(uid=talent.state)|Q(name__iexact=talent.state)).first()
        if talent.city:
            talent.city_obj = City.objects.filter(Q(uid=talent.city) | Q(name__iexact=talent.city)).first()
        talent.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_talent_city_obj_talent_state_obj'),
    ]

    operations = [
        migrations.RunPython(update_state_and_city_object)
    ]
