# Generated by Django 5.1 on 2025-10-30 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0078_auto_20251030_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='city',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='state',
        ),
    ]
