# Generated by Django 5.1 on 2025-11-17 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0078_auto_20251117_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='city',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='state',
        ),
    ]
