# Generated by Django 5.1 on 2025-10-30 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0079_remove_talent_city_remove_talent_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talent',
            old_name='city_obj',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='talent',
            old_name='state_obj',
            new_name='state',
        ),
    ]
