# Generated by Django 5.1 on 2025-11-17 14:21

from django.db import migrations
from django.db.models import Q, F, OuterRef, Exists

from apps.accounts.models import Experience


def update_talent_experience(apps, schema_editor):
    
    Talent = apps.get_model("accounts", "Talent")
    
    for talent in Talent.objects.annotate(
        has_experience=Exists(Experience.objects.filter(
            talent_id=OuterRef('id')
        ))).filter(has_experience=True).iterator():
        years, month = talent.calculate_years_of_experience()
        talent.years_of_experience = years
        talent.months_of_experience = month
        talent.save(update_fields=["years_of_experience", "months_of_experience"])
    
    
class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0080_rename_city_obj_talent_city_and_more'),
    ]

    operations = [
        migrations.RunPython(update_talent_experience)
    ]
