# Generated by Django 5.1 on 2025-10-31 16:07

from django.db import migrations


def update_roles(apps, schema_editor):
    from accounts.constants import DEPARTMENT_AND_SKILLS

    Industry = apps.get_model("accounts", "Industry")
    Department = apps.get_model("accounts", "Department")
    Role = apps.get_model("accounts", "Role")

    def clean_value(value):
        value = value.strip()
        if "\n" in value:
            return
        if value == "":
            return
        return value

    for obj in DEPARTMENT_AND_SKILLS:
        industry_value = clean_value(obj["Industry"])
        if not industry_value:
            continue

        industries = Industry.objects.filter(name__iexact=industry_value)
        industry = industries.first()
        if not industry:
            continue
        department_value = clean_value(obj["Department"])
        if not department_value:
            continue
        departments = Department.objects.filter(name__iexact=department_value, industry=industry)
        department = departments.first()
        if not department:
            continue

        for role_name in obj["Roles"].split("\n"):
            role_value = clean_value(role_name)
            if not role_value:
                continue

            role = Role.objects.filter(name__iexact=role_value, department=department).first()
            if not role:
                Role.objects.create(name=role_value, department=department)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0080_rename_city_obj_talent_city_and_more'),
    ]

    operations = [
        migrations.RunPython(update_roles)
    ]
