# Generated by Django 5.1 on 2025-11-17 14:21

from django.db import migrations
from django.db.models import OuterRef, Exists



def update_talent_experience(apps, schema_editor):
    print("done")
    
class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0081_auto_20251117_1521'),
    ]

    operations = [
        migrations.RunPython(update_talent_experience)
    ]
