# Generated by Django 5.1 on 2025-11-18 16:49

from django.db import migrations


def update_roles_and_department(apps, schema_editor):
    Department = apps.get_model("accounts", "Department")
    Industry = apps.get_model("accounts", "Industry")
    Role = apps.get_model("accounts", "Role")
    
    departments = {
        "Finance and Accounting": {
            "industry": "General Industries",
            "roles": [
                "Accounts Assistant",
                "Accounts Payable and Receivable Controller",
                "Accounts Payable Controller",
                "Accounts Payable Specialist",
                "Accounting Assistant",
                "Associate Accountant",
                "English Speaking - Senior Financial Accountant",
                "Management Accountant",
                "Senior Accountant"
            ]
        },
        
        "Sales and Marketing": {
            "industry": "General Industries",
            "roles": [
                "Account Manager",
                "B2B Sales Manager",
                "Business Development Representative",
                "CSR SEO & PPC Growth Manager",
                "Digital Marketing and Commercialization Specialist",
                "English Speaking Sales Account Manager",
                "Marketing Specialist",
                "Outbound Sales Executive (End-to-End Sales)",
                "Press Assistant",
                "Public Relations (PR) and Communications",
                "Media Relations Specialist Podcast",
                "Media Relations Strategist Liaison Podcast"
            ]
        },
        
        "Information Technology (IT)": {
            "industry": "General Industries",
            "roles": [
                "Acumatica ERP Specialist",
                "AI Developer",
                "Backend Engineer",
                "Backend Engineer (Application Support)",
                "Data Engineer (Data Warehouse)",
                "ERP Systems Analyst (Acumatica)",
                "Full Stack Engineer",
                "iOS Developer",
                "L1 Technician",
                "Systems Operations Architect"
            ]
        },
        
        "Operations / Supply Chain and Logistics": {
            "industry": "General Industries",
            "roles": [
                "Order Picker",
                "Supply Chain and Logistics",
                "Warehouse Assistant (Logistics Operator)",
                "Warehouse Operative",
                "Warehouse Worker"
            ]
        },
        
        "Customer Service / Support": {
            "industry": "General Industries",
            "roles": [
                "Call Center Representative",
                "Customer Service Representative",
                "Logistics Customer Support",
                "Prior Authorization Specialist",  # Borderline—but commonly used in insurance/claims, not medical.
                "Product Support Specialist"
            ]
        },
        
        "Operations (Digital Products)": {
            "industry": "General Industries",
            "roles": [
                "Data Enrichment Representative",
                "Online Arbitrage Specialist",
                "Virtual Assistant"
            ]
        },
        
        "Business Development": {
            "industry": "General Industries",
            "roles": [
                "Business Development Representative"
            ]
        },
        
        "Research and Development (R&D)": {
            "industry": "General Industries",
            "roles": [
                "Commodity Data Scientist",
                "Head of Information Operations & Insights",
                "Data Verification Analyst (Financial)"
            ]
        },
        
        "Compliance (Insurance)": {
            "industry": "Healthcare",  # Because Life & Health Insurance roles directly relate to health sector
            "roles": [
                "Licensed Insurance Representative",
                "Licensed P&C Commercial Insurance Producer",
                "Life and Health Insurance Advisor",
                "Life and Health Insurance Agent",
                "Life and Health Insurance Representative",
                "Life and Health Insurance Sales Agent",
                "Life and Health Insurance Seller",
                "Life and Health Insurance Specialist",
                "Spanish Bilingual Insurance Agent"
            ]
        },
        
        "Administration": {
            "industry": "General Industries",
            "roles": [
                "Operations Specialist"
            ]
        },
        
        "E-Commerce Operations": {
            "industry": "General Industries",
            "roles": [
                "E-Commerce Operations",
                "E-Commerce Operations Specialist",
                "Ecommerce Product Sourcing Specialist"
            ]
        }
    }
    
    for department in departments:
        department_obj = Department.objects.filter(name__iexact=department).first()
        if not department_obj:
            industry = Industry.objects.filter(name__iexact=departments[department]["industry"]).first()
            if not industry:
                industry = Industry.objects.create(name=departments[department]["industry"])
            department_obj = Department.objects.create(
                name=department, industry=industry
            )
        for role in departments[department]["roles"]:
            if not Role.objects.filter(
                    name__iexact=role, department=department_obj
            ).exists():
                Role.objects.create(
                    name=role, department=department_obj
                )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0082_auto_20251117_1521'),
    ]

    operations = [
        migrations.RunPython(update_roles_and_department)
    ]
