# Generated by Django 5.1 on 2025-11-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0082_auto_20251031_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='custom',
            field=models.BooleanField(default=False),
        ),
    ]
