# Generated by Django 5.1 on 2025-11-17 16:25

from django.db import migrations
from django.db.models import OuterRef, Exists


def update_talent_experience(apps, schema_editor):
    print("done")
    


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0083_role_custom_skill_custom'),
    ]

    operations = [
        migrations.RunPython(update_talent_experience)
    ]
