# Generated by Django 5.1 on 2025-11-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0085_auto_20251118_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentfilter',
            name='educational_levels',
            field=models.ManyToManyField(blank=True, related_name='educationlevel_talent_filter', to='accounts.educationlevel'),
        ),
        migrations.AddField(
            model_name='talentfilter',
            name='industries',
            field=models.ManyToManyField(blank=True, related_name='industries_talent_filter', to='accounts.industry'),
        ),
        migrations.AddField(
            model_name='talentfilter',
            name='locations',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='talentfilter',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='roles_talent_filter', to='accounts.role'),
        ),
        migrations.AlterField(
            model_name='talentfilter',
            name='skills',
            field=models.ManyToManyField(related_name='skills_talent_filter', to='accounts.skill'),
        ),
    ]
