# Generated by Django 5.1 on 2025-11-18 18:18

from django.db import migrations
from django.db.models import Exists, OuterRef


def fix_roles(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    Department = apps.get_model("accounts", "Department")
    
    customer_service1 = Department.objects.filter(name__iexact="Customer Service / Support").first()
    customer_service2 = Department.objects.filter(name__iexact="Customer Service/Support").first()
    
    compliance1 = Department.objects.filter(name__iexact="Compliance (Insurance)").first()
    compliance2 = Department.objects.filter(name__iexact="Compliance").first()
    
    if compliance1 and compliance2:
        roles = Role.objects.filter(department=compliance1).annotate(
            is_duplicate=Exists(Role.objects.filter(
                name__iexact=OuterRef("name"), department=compliance2
            ))
        )
        roles.filter(is_duplicate=False).update(department=compliance2)
        roles.filter(is_duplicate=True).delete()
        compliance1.delete()
    
    if customer_service1 and customer_service2:
        roles = Role.objects.filter(department=customer_service1).annotate(
            is_duplicate=Exists(Role.objects.filter(
                name__iexact=OuterRef("name"), department=customer_service2)))
        roles.filter(is_duplicate=False).update(department=customer_service2)
        roles.filter(is_duplicate=True).delete()
        customer_service1.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0085_auto_20251118_1726'),
    ]

    operations = [
        migrations.RunPython(fix_roles)
    ]
