# Generated by Django 5.1 on 2025-11-19 15:51

from django.db import migrations

def update_talent_filter(apps, schema_editor):
    TalentFilter = apps.get_model("accounts", "TalentFilter")
    for talent_filter in TalentFilter.objects.iterator():
        if talent_filter.role:
            talent_filter.roles.add(talent_filter.role)
        if talent_filter.educational_level:
            talent_filter.educational_levels.add(talent_filter.educational_level)
        if talent_filter.industry:
            talent_filter.industries.add(talent_filter.industries)
        if talent_filter.location:
            talent_filter.locations = [talent_filter.location]
        talent_filter.save()
        
class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0086_talentfilter_educational_levels_and_more'),
    ]

    operations = [
        migrations.RunPython(update_talent_filter)
    ]
