# Generated by Django 5.1 on 2025-11-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0088_auto_20251119_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentfilter',
            name='educational_level',
        ),
        migrations.RemoveField(
            model_name='talentfilter',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='talentfilter',
            name='location',
        ),
        migrations.RemoveField(
            model_name='talentfilter',
            name='role',
        ),
    ]
