# Generated by Django 5.1 on 2025-11-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0088_remove_talentfilter_educational_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='city_text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
