# Generated by Django 5.1 on 2025-11-28 10:59

from django.db import migrations
from django.db.models import F


def update_city_text(apps, schema_editor):
    Talent = apps.get_model("accounts", "Talent")
    JobPost = apps.get_model("jobs", "JobPost")
    
    for talent in Talent.objects.filter(city__isnull=False).iterator():
        talent.update(city_text=talent.city.name)
    for job_post in JobPost.objects.filter(city__isnull=False).iterator():
        job_post.update(city_text=job_post.city.name)
    
    
class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0089_talent_city_text'),
    ]

    operations = [
        migrations.RunPython(update_city_text)
    ]
