# Generated by Django 5.1 on 2025-11-28 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0090_auto_20251128_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='city',
        ),
    ]
