# Generated by Django 5.1 on 2025-11-28 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0091_remove_talent_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talent',
            old_name='city_text',
            new_name='city',
        ),
    ]
