# Generated by Django 5.1 on 2025-12-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0092_rename_city_text_talent_city'),
        ('jobs', '0105_jobpost_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentfilter',
            name='business_models',
            field=models.ManyToManyField(blank=True, related_name='businessmodels_talent_filter', to='jobs.businessmodel'),
        ),
    ]
