# Generated by Django 5.1 on 2025-12-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0093_talentfilter_business_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentfilter',
            name='completed_profiles',
            field=models.BooleanField(default=True),
        ),
    ]
