# Generated by Django 5.1 on 2025-12-11 22:14

from django.db import migrations

def update_role(apps, schema_editor):
    Department = apps.get_model("accounts", "Department")
    Role = apps.get_model("accounts", "Role")
    Industry = apps.get_model("accounts", "Industry")

    industry = Industry.objects.filter(name__iexact="Healthcare").first()
    if not industry:
        industry = Industry.objects.create(name="Healthcare")
    department = Department.objects.filter(name__iexact="Psychiatry", industry=industry).first()
    if not department:
        department = Department.objects.create(name="Psychiatry", industry=industry)
    role = Role.objects.filter(name__iexact="Mental Health Therapist", department=department).first()
    if not role:
        Role.objects.create(name="Mental Health Therapist", department=department)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0094_talentfilter_completed_profiles'),
    ]

    operations = [
        migrations.RunPython(update_role),
    ]
