# Generated by Django 5.1 on 2025-12-12 15:46

from django.db import migrations


def update_skill(apps, schema_editor):
    Skill = apps.get_model("accounts", "Skill")

    Skill.objects.filter(name__iexact="de").delete()
    Skill.objects.filter(name__iexact="and inclusion (DEI)").update(name="Diversity Equity and Inclusion (DEI)")

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0095_auto_20251211_2314'),
    ]

    operations = [
        migrations.RunPython(update_skill),
    ]
