# Generated by Django 5.1 on 2025-12-26 10:32

from django.db import migrations

def add_new_role(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    Industry = apps.get_model('accounts', 'Industry')
    Department = apps.get_model('accounts', 'Department')

    industry = Industry.objects.filter(name__iexact='General Industries').first()
    if not industry:
        industry = Industry.objects.create(name='General Industries')
    department = Department.objects.filter(name__iexact='Public Relations (PR) and Communications', industry=industry).first()
    if not department:
        department = Department.objects.create(name='Public Relations (PR) and Communications', industry=industry)
    role = Role.objects.filter(name__iexact="News Editor", department=department).first()
    if not role:
        role = Role.objects.create(name="News Editor", department=department)



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0096_auto_20251212_1646'),
    ]

    operations = [
        migrations.RunPython(add_new_role)
    ]
