# Generated by Django 5.1 on 2026-01-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0097_auto_20251226_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='certification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='major',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.CharField(max_length=100),
        ),
    ]
