# Generated by Django 5.1 on 2026-01-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0098_education_certification_alter_education_major_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('Prefer not to say', 'Prefer not to say'), ('others', 'others')], max_length=100, null=True),
        ),
    ]
