# Generated by Django 5.1 on 2026-02-17 13:59

from django.db import migrations


def add_more_roles_v2(apps, schema_editor):
    from accounts.constants import DEPARTMENT_AND_SKILLS
    Industry = apps.get_model("accounts", "Industry")
    Department = apps.get_model("accounts", "Department")
    Role = apps.get_model("accounts", "Role")

    for obj in DEPARTMENT_AND_SKILLS[:1]:
        industry, _ = Industry.objects.get_or_create(name=obj["Industry"].strip())
        department, _ = Department.objects.get_or_create(name=obj["Department"].strip(), industry=industry)
        for role_name in obj["Roles"].split("\n"):
            if Role.objects.filter(name__iexact=role_name.strip(), department=department).exists():
                continue
            Role.objects.create(name=role_name.strip(), department=department)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0099_alter_user_gender'),
    ]

    operations = [
        migrations.RunPython(add_more_roles_v2),
    ]
