# Generated by Django 5.1 on 2026-02-06 17:34

from django.db import migrations
from django.db.models.expressions import RawSQL
from accounts.schemas.talent import WorkStructureEnum


def fix_work_models(apps, schema_editor):
    Talent = apps.get_model("accounts", "Talent")

    invalid_talents = Talent.objects.annotate(
        has_invalid=RawSQL(
            """
            EXISTS (
                SELECT 1
                FROM jsonb_array_elements_text(work_models) AS elem
                WHERE elem NOT IN (%s, %s, %s)
            )
            """,
            (WorkStructureEnum.REMOTE.value,
            WorkStructureEnum.HYBRID.value,
            WorkStructureEnum.IN_OFFICE.value,)
        )
        ).filter(
            has_invalid=True
        )

    for talent in invalid_talents.iterator():
        talent.work_structure = [
            v for v in talent.work_models
            if v in {
                WorkStructureEnum.REMOTE.value,
                WorkStructureEnum.HYBRID.value,
                WorkStructureEnum.IN_OFFICE.value,
            }
        ]
        talent.save(update_fields=["work_models"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0099_alter_user_gender"),
    ]

    operations = [
        migrations.RunPython(fix_work_models, reverse_code=migrations.RunPython.noop),
    ]
