# Generated by Django 5.1 on 2026-02-17 12:41

from accounts.constants import DEPARTMENT_AND_SKILLS
from django.db import migrations


def add_more_roles(apps, schema_editor):
    Industry = apps.get_model("accounts", "Industry")
    Department = apps.get_model("accounts", "Department")
    Role = apps.get_model("accounts", "Role")

    for obj in DEPARTMENT_AND_SKILLS:
        industry, _ = Industry.objects.get_or_create(name=obj["Industry"].strip())
        department, _ = Department.objects.get_or_create(name=obj["Department"].strip(), industry=industry)
        # if roles count is greater than or equal to the number of roles in the list, skip
        if Role.objects.filter(department=department, custom=False).count() >= len(obj["Roles"].split("\n")):
            continue
        for role_name in obj["Roles"].split("\n"):
            if Role.filter(name__iexact=role_name.strip(), department=department).exists():
                continue
            Role.objects.create(name=role_name.strip().title(), department=department)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0099_alter_user_gender'),
    ]

    operations = [
        migrations.RunPython(add_more_roles),
    ]
