# Generated by Django 5.1 on 2026-03-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0100_auto_20260217_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='operating_system',
            field=models.CharField(choices=[('windows', 'windows'), ('macbook', 'macbook'), ('either mac or windows', 'either mac or windows')], max_length=100, null=True),
        ),
    ]
