# Generated by Django 5.1 on 2026-03-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0100_auto_20260217_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='certification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
