# Generated by Django 5.1 on 2026-02-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0100_auto_20260206_1734'),
        ('accounts', '0100_auto_20260217_1459'),
    ]

    operations = [
    ]
