# Generated by Django 5.1 on 2026-03-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0101_alter_education_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secondary_email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='secondary_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
