# Generated by Django 5.1 on 2026-03-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0101_experience_operating_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='operating_system',
        ),
        migrations.AddField(
            model_name='talent',
            name='operating_system',
            field=models.CharField(choices=[('windows', 'windows'), ('macbook', 'macbook'), ('either mac or windows', 'either mac or windows')], max_length=100, null=True),
        ),
    ]
