# Generated by Django 5.1 on 2026-03-02 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0101_experience_operating_system'),
        ('accounts', '0101_merge_0100_auto_20260206_1734_0100_auto_20260217_1459'),
    ]

    operations = [
    ]
