# Generated by Django 5.1 on 2026-03-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0102_user_secondary_email_user_secondary_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessuser',
            name='default_sender_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
