# Generated by Django 5.1 on 2026-04-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0102_bannedaccount_alter_businessclient_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='paused',
            field=models.BooleanField(default=False),
        ),
    ]
