# Generated by Django 5.1 on 2026-03-02 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0102_merge_20260302_1537'),
        ('accounts', '0102_remove_experience_operating_system_and_more'),
    ]

    operations = [
    ]
