# Generated by Django 5.1 on 2026-05-05 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0101_alter_education_certification'),
        ('accounts', '0102_remove_experience_operating_system_and_more'),
    ]

    operations = [
    ]
