# Generated by Django 5.1 on 2026-03-09 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0101_experience_description'),
        ('accounts', '0103_merge_20260302_1640'),
    ]

    operations = [
    ]
