# Generated by Django 5.1 on 2026-03-30 15:46

from django.db import migrations

def assign_default_sender_email(apps, schema_editor):
    BusinessUser = apps.get_model('accounts', 'BusinessUser')

    for user in BusinessUser.objects.filter(default_sender_email__isnull=True):
        user.default_sender_email = user.user.email
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0103_businessuser_default_sender_email'),
    ]

    operations = [
        migrations.RunPython(assign_default_sender_email)
    ]
