# Generated by Django 5.1 on 2026-05-05 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0101_experience_description'),
        ('accounts', '0103_merge_20260505_0806'),
    ]

    operations = [
    ]
