# Generated by Django 5.1 on 2026-03-12 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0101_alter_education_certification'),
        ('accounts', '0104_merge_20260309_1420'),
    ]

    operations = [
    ]
