# Generated by Django 5.1 on 2026-05-05 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0104_auto_20260330_1646'),
        ('accounts', '0104_merge_20260505_0814'),
    ]

    operations = [
    ]
