# Generated by Django 5.1 on 2026-03-27 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0103_businessuser_default_sender_email'),
        ('accounts', '0105_merge_20260312_1750'),
    ]

    operations = [
    ]
