# Generated by Django 5.1 on 2026-05-05 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0103_business_paused'),
        ('accounts', '0105_merge_20260505_0828'),
    ]

    operations = [
    ]
