# Generated by Django 5.1 on 2026-03-30 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0104_auto_20260330_1646'),
        ('accounts', '0106_merge_20260327_1155'),
    ]

    operations = [
    ]
