# Generated by Django 5.1 on 2026-05-06 09:35

import accounts.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0106_merge_0103_business_paused_0105_merge_20260505_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='job_type',
            field=models.CharField(choices=accounts.enums.TalentJobType.choices, default='Full Time Jobs', max_length=128),
        ),
    ]
