# Generated by Django 5.1 on 2026-04-28 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0102_bannedaccount_alter_businessclient_business_and_more'),
        ('accounts', '0107_merge_20260330_1726'),
    ]

    operations = [
    ]
