# Generated by Django 5.1 on 2026-06-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0107_talent_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='average_experience_tenure',
            field=models.FloatField(default=0, help_text='Average tenure in months'),
        ),
    ]
