# Generated by Django 5.1 on 2026-06-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0107_talent_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='talent_invite_last_sent',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='talent_invite_limit',
            field=models.IntegerField(default=0),
        ),
    ]
