# Generated by Django 5.1 on 2026-04-30 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0103_business_paused'),
        ('accounts', '0108_merge_20260428_1111'),
    ]

    operations = [
    ]
