# Generated by Django 5.1 on 2026-06-11 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0108_adminuserinvite_adminuser_last_activity'),
        ('accounts', '0108_talent_average_experience_tenure'),
    ]

    operations = [
    ]
