# Generated by Django 5.1 on 2026-04-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0108_merge_20260428_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='paused',
            field=models.BooleanField(default=False),
        ),
    ]
