# Generated by Django 5.1 on 2026-07-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0109_merge_20260611_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannedaccount',
            name='current_role',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='bannedaccount',
            name='fullname',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='bannedaccount',
            name='interested_in',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='bannedaccount',
            name='location',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
