# Generated by Django 5.1 on 2026-05-05 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0106_merge_0103_business_paused_0105_merge_20260505_0828'),
        ('accounts', '0109_merge_0103_business_paused_0108_merge_20260428_1111'),
    ]

    operations = [
    ]
