# Generated by Django 5.1 on 2026-06-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0109_merge_20260611_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='source',
            field=models.CharField(choices=[('Linkedin', 'Linkedin'), ('Indeed', 'Indeed'), ('Email', 'Email'), ('Others', 'Others')], default='Others', max_length=50),
        ),
    ]
