# Generated by Django 5.1 on 2026-06-30 14:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0109_merge_20260611_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='talents_viewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TalentViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_records', to='accounts.talent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_viewer_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('talent', 'user')},
            },
        ),
    ]
