# Generated by Django 5.1 on 2026-06-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0109_merge_20260611_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentfilter',
            name='interested_in',
            field=models.JSONField(default=list),
        ),
    ]
