# Generated by Django 5.1 on 2026-05-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0107_talent_job_type'),
        ('accounts', '0110_merge_20260505_1214'),
    ]

    operations = [
    ]
