# Generated by Django 5.1 on 2026-06-30 14:34

from django.db import migrations

def transfer_profile_views(apps, schema_editor):
    TalentViewer = apps.get_model('accounts', 'TalentViewer')
    Talent = apps.get_model('accounts', 'Talent')
    for talent in Talent.objects.prefetch_related("viewers"):
        TalentViewer.objects.bulk_create(
            [
                TalentViewer(
                    talent=talent,
                    user=user,
                )
                for user in talent.viewers.all()
            ],
            ignore_conflicts=True,
        )
class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0110_alter_talent_viewers_talentviewer'),
    ]

    operations = [
        migrations.RunPython(transfer_profile_views)
    ]
