# Generated by Django 5.1 on 2026-05-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0108_adminuserinvite_adminuser_last_activity'),
        ('accounts', '0111_merge_0107_talent_job_type_0110_merge_20260505_1214'),
    ]

    operations = [
    ]
