# Generated by Django 5.1 on 2026-06-30 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0111_auto_20260630_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='viewers',
        ),
        migrations.AlterField(
            model_name='talentviewer',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='accounts.talent'),
        ),
        migrations.AlterField(
            model_name='talentviewer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talents_viewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
