# Generated by Django 5.1 on 2026-06-10 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0108_talent_average_experience_tenure'),
        ('accounts', '0112_merge_20260518_1134'),
    ]

    operations = [
    ]
