# Generated by Django 5.1 on 2026-06-10 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0108_business_talent_invite_last_sent_and_more'),
        ('accounts', '0113_merge_20260610_1644'),
    ]

    operations = [
    ]
