# Generated by Django 5.1 on 2026-06-12 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0109_merge_20260611_1057'),
        ('accounts', '0113_merge_20260610_1644'),
    ]

    operations = [
    ]
