# Generated by Django 5.2.15 on 2026-06-16 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0114_merge_20260610_2146'),
        ('accounts', '0114_merge_20260612_1126'),
    ]

    operations = [
    ]
