# Generated by Django 5.1 on 2026-06-23 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0110_talent_source'),
        ('accounts', '0115_merge_20260616_1022'),
    ]

    operations = [
    ]
