# Generated by Django 5.1 on 2026-06-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0110_talentfilter_interested_in'),
        ('accounts', '0116_merge_0110_talent_source_0115_merge_20260616_1022'),
    ]

    operations = [
    ]
