# Generated by Django 5.1 on 2026-06-30 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0112_remove_talent_viewers_alter_talentviewer_talent_and_more'),
        ('accounts', '0117_merge_20260624_1453'),
    ]

    operations = [
    ]
