# Generated by Django 5.1 on 2026-07-01 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0110_bannedaccount_current_role_bannedaccount_fullname_and_more'),
        ('accounts', '0118_merge_20260630_1652'),
    ]

    operations = [
    ]
