JOB_LEVEL = [
    'entry level',
    'junior',
    'intermediate',
    'lead',
    'senior',
    'manager',
    'director',
    'vice president',
    'executive chief officer'
]


BUSINESS_MODELS = [
    "Advertising-Based",
    "Affiliate Marketing",
    "Agency Model",
    "Asset Sharing",
    "Auction Model",
    "B2B (Business-to-Business)",
    "B2G (Business-to-Government)",
    "Blockchain-Based Token Models",
    "Build-to-Order",
    "Circular Economy",
    "Co-Creation",
    "Consulting",
    "Content Subscription",
    "Crowdfunding",
    "Crowdsourcing",
    "DaaS (Data-as-a-Service)",
    "Data Monetization",
    "Direct Sales",
    "Direct-to-Consumer (DTC)",
    "Dropshipping",
    "E-Commerce",
    "Event-Based Revenue",
    "Franchise",
    "Freemium",
    "Hybrid Business Model",
    "IaaS (Infrastructure as a Service)",
    "Just-in-Time (JIT)",
    "License Fee",
    "Licensing",
    "Made-to-Order",
    "Manufacturer-to-Consumer (M2C)",
    "Marketplace",
    "Marketplace for Physical Goods",
    "Mobile App Monetization",
    "On-Demand Delivery",
    "Open Source Hardware",
    "PaaS (Platform as a Service)",
    "PaaS (Product-as-a-Service)",
    "Pay-What-You-Want",
    "Peer-to-Peer (P2P)",
    "Platform Cooperativism",
    "Product Bundling",
    "Razor and Blades",
    "SaaP (Service-as-a-Product)",
    "SaaS (Software as a Service)",
    "Social Enterprise",
    "Subscription",
    "Virtual Goods",
    "White Labeling"
]