# Generated by Django 5.1 on 2024-09-09 11:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='annaul_bonus_curreny',
            new_name='annual_bonus_currency',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='annaul_salary_curreny',
            new_name='annual_salary_currency',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='annaul_bonus_curreny',
            new_name='annual_bonus_currency',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='annaul_salary_curreny',
            new_name='annual_salary_currency',
        ),
        migrations.AddField(
            model_name='job',
            name='additional_hours_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='additional_hours_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='additional_hours_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='benefits',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='location_type',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='postal_code',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='province',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='recruiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiting_job_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='lunch_break',
            field=models.CharField(choices=[('paid', 'paid'), ('unpaid', 'unpaid')], max_length=16),
        ),
        migrations.AlterField(
            model_name='jobdraft',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RequiredAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScreeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=16)),
                ('text', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.screeningquestion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
