# Generated by Django 5.1 on 2024-09-11 05:22

import django.db.models.deletion
import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_annaul_bonus_curreny_job_annual_bonus_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='avaibility_timezone',
            field=timezone_field.fields.TimeZoneField(default='America/Vancouver'),
        ),
        migrations.AddField(
            model_name='job',
            name='technological_requirement',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='text',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='employmenttype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jobs.employmenttype'),
        ),
        migrations.AlterField(
            model_name='job',
            name='lunch_break',
            field=models.CharField(choices=[('PAID', 'paid'), ('UNPAID', 'unpaid')], max_length=16),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_structure',
            field=models.CharField(choices=[('REMOTE', 'remote'), ('HYBRID', 'hybrid'), ('IN_OFFICE', 'in office')]),
        ),
        migrations.AlterField(
            model_name='screeningquestion',
            name='type',
            field=models.CharField(choices=[('SINGLE_SELECT', 'single_select'), ('MULTI_SELECT', 'multi_select'), ('TEXT', 'text'), ('FILE', 'file')], max_length=16),
        ),
    ]
