# Generated by Django 5.1 on 2024-09-12 14:49

import django.db.models.deletion
import jobs.enums
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userlanguage_language_remove_talent_languages_and_more'),
        ('core', '0001_initial'),
        ('jobs', '0003_job_avaibility_timezone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='job',
            name='minimum_education_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.educationlevel'),
        ),
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.RemoveField(
            model_name='jobfilter',
            name='user',
        ),
        migrations.RemoveField(
            model_name='savedjob',
            name='job',
        ),
        migrations.RemoveField(
            model_name='savedjob',
            name='user',
        ),
        migrations.AddField(
            model_name='jobfilter',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department'),
        ),
        migrations.AddField(
            model_name='jobfilter',
            name='employment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.employmenttype'),
        ),
        migrations.AddField(
            model_name='jobfilter',
            name='location_type',
            field=models.CharField(choices=[('REMOTE', 'remote'), ('HYBRID', 'hybrid'), ('IN_OFFICE', 'in office')], default=jobs.enums.WorkStructureEnum['IN_OFFICE']),
        ),
        migrations.AddField(
            model_name='jobfilter',
            name='minimum_education_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.educationlevel'),
        ),
        migrations.AddField(
            model_name='jobfilter',
            name='office_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.country'),
        ),
        migrations.AddField(
            model_name='jobfilter',
            name='remove_applied_jobs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobfilter',
            name='talent',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.talent'),
        ),
        migrations.AddField(
            model_name='jobfilter',
            name='years_of_experience',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='requiredattribute',
            name='first_language',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requiredattribute',
            name='job_level',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requiredattribute',
            name='location',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requiredattribute',
            name='minimum_education_level',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requiredattribute',
            name='role',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requiredattribute',
            name='secondary_language',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requiredattribute',
            name='skills',
            field=models.ManyToManyField(to='accounts.skill'),
        ),
        migrations.AddField(
            model_name='requiredattribute',
            name='technological_requirement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requiredattribute',
            name='work_structure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requiredattribute',
            name='working_hours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='job_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobpost'),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='talent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.talent'),
        ),
        migrations.AddField(
            model_name='screeningquestion',
            name='is_knockout',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='additional_languages',
            field=models.ManyToManyField(related_name='jobs', to='core.language'),
        ),
        migrations.AlterField(
            model_name='job',
            name='first_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.language'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='stage',
            field=models.CharField(choices=[('SCREENING', 'screening'), ('INTERVIEW', 'interview'), ('INTERVIEW_2', 'interview 2'), ('HIRED', 'hired'), ('ONBOARDING', 'onboarding'), ('REJECTED', 'rejected')], max_length=16),
        ),
        migrations.AlterField(
            model_name='requiredattribute',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='screeningquestion',
            name='type',
            field=models.CharField(choices=[('SINGLE_SELECT', 'single select'), ('MULTI_SELECT', 'multi select'), ('TEXT', 'text'), ('FILE', 'file')], max_length=16),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobapplication')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.questionoption')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='job',
            name='business_models',
            field=models.ManyToManyField(to='jobs.businessmodel'),
        ),
        migrations.AddField(
            model_name='requiredattribute',
            name='business_model',
            field=models.ManyToManyField(to='jobs.businessmodel'),
        ),
        migrations.CreateModel(
            name='JobApplicationWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback', models.TextField()),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jobs.jobpost')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.talent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='EducationLevel',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='SkillCategory',
        ),
    ]
