# Generated by Django 5.1 on 2024-09-13 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_businessmodel_alter_job_minimum_education_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='avaibility_timezone',
            new_name='availability_timezone',
        ),
    ]
