# Generated by Django 5.1 on 2024-09-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_rename_avaibility_timezone_job_availability_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmenttype',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
