# Generated by Django 5.1 on 2024-09-14 10:04

from django.db import migrations

EMPLOYMENT_TYPES = [
    {
        "name":"Full-Time Independent Contractor" ,
        "description": "A contractor engaged by a company on a full-time basis under a contract for a specified duration, or on an ongoing basis depending on the needs of the client and the terms of the agreement. This role is of independent status, and no employee benefits are provided.",
        "children": []
    },
    {
        "name":"Part-Time Contractor" ,
        "description": "A contractor who works for a company to provide specific services on a contractual basis, or for a few hours per week depending on the agreement. This role is of independent status, and no employee benefits are provided.",
        "children": []
    },
    {
        "name":"Temporary Employee" ,
        "description": " A worker hired by a company on a short-term basis to fulfill specific needs. They are considered employees and may receive benefits depending on the company. In some cases, this can lead to permanent employment if the employee performs well and there is a need for a long-term role.",
        "children": []
    },
    {
        "name":"Full-Time Direct Employee" ,
        "description": "A worker who works a standard number of hours per week for the company. They are usually hired on an ongoing basis without a predetermined end date, indicating a long-term employment relationship. They are often eligible for a range of benefits provided by the company.",
        "children": [
            {
                "name":"1840 & Company’s Entity",
                "description":None,
                "children":[]
            },
            {
                "name":"Own Entity",
                "description":None,
                "children":[]
            }
        ]
    },
    {
        "name":"Contract Employee" ,
        "description": "An individual engaged to perform specific tasks or projects for a company under a contract agreement. This contract can be project-based or time-based.",
        "children": []
    }
]


def load_employment_types(apps, schema_editor):
    EmploymentType = apps.get_model("jobs", "EmploymentType")
    for obj in EMPLOYMENT_TYPES:
        parent = EmploymentType(
            name = obj["name"],
            description = obj["description"],
        )
        parent.save()
        for child_obj in obj["children"]:
            child = EmploymentType(
                name = child_obj["name"],
                description = child_obj["description"],
                parent = parent
            )
            child.save()



class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_employmenttype_description'),
    ]

    operations = [
        migrations.RunPython(load_employment_types)
    ]
