# Generated by Django 5.1 on 2024-09-16 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_department_job_role_job_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.employmenttype'),
        ),
        migrations.AlterField(
            model_name='job',
            name='hiring_company_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_structure',
            field=models.CharField(choices=[('REMOTE', 'remote'), ('HYBRID', 'hybrid'), ('IN_OFFICE', 'in office')], null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='years_of_experience',
            field=models.IntegerField(null=True),
        ),
    ]
