# Generated by Django 5.1 on 2024-09-16 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_job_about_alter_job_employment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availableday',
            name='user',
        ),
    ]
