# Generated by Django 5.1 on 2024-09-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_remove_availableday_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='annual_bonus_currency',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='annual_bonus_max',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='annual_bonus_min',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='annual_salary_currency',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='annual_salary_max',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='annual_salary_min',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
