# Generated by Django 5.1 on 2024-09-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_remove_jobapplication_job_jobapplication_job_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='annual_bonus_max',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='annual_bonus_min',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='annual_salary_max',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='annual_salary_min',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
