# Generated by Django 5.1 on 2024-09-20 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_talentskill_business_models_and_more'),
        ('jobs', '0013_alter_job_annual_bonus_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='annual_bonus_currency',
        ),
        migrations.RemoveField(
            model_name='job',
            name='annual_salary_currency',
        ),
        migrations.RemoveField(
            model_name='job',
            name='business',
        ),
        migrations.RemoveField(
            model_name='job',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='job',
            name='recruiter',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='annual_bonus_currency',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='annual_salary_currency',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='recruiter',
        ),
        migrations.AlterField(
            model_name='jobdraft',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.businessuser'),
        ),
    ]
