# Generated by Django 5.1 on 2024-09-20 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_talentskill_business_models_and_more'),
        ('core', '0002_auto_20240919_1803'),
        ('jobs', '0014_remove_job_annual_bonus_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='annual_bonus_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_with_bonus_currency', to='core.currency'),
        ),
        migrations.AddField(
            model_name='job',
            name='annual_salary_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_with_salary_currency', to='core.currency'),
        ),
        migrations.AddField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.businessuser'),
        ),
        migrations.AddField(
            model_name='job',
            name='recruiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruiting_jobs', to='accounts.businessuser'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='annual_bonus_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_posts_with_bonus_currency', to='core.currency'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='annual_salary_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_posts_with_salary_currency', to='core.currency'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='recruiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruiting_job_posts', to='accounts.businessuser'),
        ),
    ]
