# Generated by Django 5.1 on 2024-09-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_job_annual_bonus_currency_job_annual_salary_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='stage',
            field=models.CharField(choices=[('SCREENING', 'screening'), ('INTERVIEW', 'interview'), ('INTERVIEW_2', 'interview 2'), ('HIRED', 'hired'), ('ONBOARDING', 'onboarding'), ('REJECTED', 'rejected')], default=None, max_length=16, null=True),
        ),
    ]
