# Generated by Django 5.1 on 2024-10-10 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_auth_mode'),
        ('jobs', '0016_alter_jobapplication_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='same_job_post_recruiter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='recruiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.businessuser'),
        ),
        migrations.AlterField(
            model_name='jobfilter',
            name='location_type',
            field=models.CharField(choices=[('REMOTE', 'remote'), ('HYBRID', 'hybrid'), ('IN_OFFICE', 'in office')], default='in office'),
        ),
    ]
