# Generated by Django 5.1 on 2024-10-11 14:52

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_job_same_job_post_recruiter_jobapplication_recruiter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='applicant_years_of_experience',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='first_interview_timeline',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='onboarding_timeline',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='posted_timeline',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='screening_timeline',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='second_interview_timeline',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='stage_date_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='jobapplicationwithdrawal',
            name='feedback_type',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='date_posted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='days_to_hire',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('posted_timeline'), '+', models.F('screening_timeline')), '+', models.F('first_interview_timeline')), '+', models.F('second_interview_timeline')), '+', models.F('onboarding_timeline')), output_field=models.PositiveIntegerField()),
        ),
    ]
