# Generated by Django 5.1 on 2024-10-11 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_jobapplication_applicant_years_of_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='applicant_years_of_experience',
        ),
    ]
