# Generated by Django 5.1 on 2024-11-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_remove_jobapplication_applicant_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='match',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
