# Generated by Django 5.1 on 2024-11-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_alter_jobapplication_is_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_draft',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_paused',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='is_posted',
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'draft'), ('PAUSED', 'paused'), ('POSTED', 'posted'), ('CLOSED', 'closed')], default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'draft'), ('PAUSED', 'paused'), ('POSTED', 'posted'), ('CLOSED', 'closed')], default='draft', max_length=16),
        ),
    ]
