# Generated by Django 5.1 on 2024-11-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_remove_job_is_draft_remove_job_is_paused_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableday',
            name='day',
            field=models.CharField(choices=[('Monday', 'MONDAY'), ('Tuesday', 'TUESDAY'), ('Wednesday', 'WEDNESDAY'), ('Thursday', 'THURSDAY'), ('Friday', 'FRIDAY'), ('Saturday', 'SATURDAY'), ('Sunday', 'SUNDAY')], max_length=32),
        ),
        migrations.AlterField(
            model_name='job',
            name='lunch_break',
            field=models.CharField(choices=[('paid', 'PAID'), ('unpaid', 'UNPAID')], max_length=16),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'DRAFT'), ('paused', 'PAUSED'), ('posted', 'POSTED'), ('closed', 'CLOSED')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_structure',
            field=models.CharField(choices=[('remote', 'REMOTE'), ('hybrid', 'HYBRID'), ('in office', 'IN_OFFICE')], null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='stage',
            field=models.CharField(choices=[('screening', 'SCREENING'), ('interview', 'INTERVIEW'), ('interview 2', 'INTERVIEW_2'), ('hired', 'HIRED'), ('onboarding', 'ONBOARDING'), ('rejected', 'REJECTED')], default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='jobfilter',
            name='location_type',
            field=models.CharField(choices=[('remote', 'REMOTE'), ('hybrid', 'HYBRID'), ('in office', 'IN_OFFICE')], default='in office'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('draft', 'DRAFT'), ('paused', 'PAUSED'), ('posted', 'POSTED'), ('closed', 'CLOSED')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='screeningquestion',
            name='type',
            field=models.CharField(choices=[('single select', 'SINGLE_SELECT'), ('multi select', 'MULTI_SELECT'), ('text', 'TEXT'), ('file', 'FILE')], max_length=16),
        ),
    ]
