# Generated by Django 5.1 on 2024-11-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_alter_availableday_day_alter_job_lunch_break_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableday',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=32),
        ),
        migrations.AlterField(
            model_name='job',
            name='lunch_break',
            field=models.CharField(choices=[('paid', 'paid'), ('unpaid', 'unpaid')], max_length=16),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('paused', 'paused'), ('posted', 'posted'), ('closed', 'closed')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_structure',
            field=models.CharField(choices=[('remote', 'remote'), ('hybrid', 'hybrid'), ('in office', 'in office')], null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='stage',
            field=models.CharField(choices=[('screening', 'screening'), ('interview', 'interview'), ('interview 2', 'interview 2'), ('hired', 'hired'), ('onboarding', 'onboarding'), ('rejected', 'rejected')], default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='jobfilter',
            name='location_type',
            field=models.CharField(choices=[('remote', 'remote'), ('hybrid', 'hybrid'), ('in office', 'in office')], default='in office'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('paused', 'paused'), ('posted', 'posted'), ('closed', 'closed')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='screeningquestion',
            name='type',
            field=models.CharField(choices=[('single select', 'single select'), ('multi select', 'multi select'), ('text', 'text'), ('file', 'file')], max_length=16),
        ),
    ]
