# Generated by Django 5.1 on 2024-11-15 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_business_created_by_and_more'),
        ('jobs', '0023_alter_availableday_day_alter_job_lunch_break_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableday',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='employmenttype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.employmenttype'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.businessuser'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.joblevel'),
        ),
        migrations.AlterField(
            model_name='job',
            name='minimum_education_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.educationlevel'),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.qualification'),
        ),
        migrations.AlterField(
            model_name='jobapplicationwithdrawal',
            name='talent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.talent'),
        ),
        migrations.AlterField(
            model_name='jobdraft',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.businessuser'),
        ),
    ]
