# Generated by Django 5.1 on 2024-11-19 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_alter_availableday_job_alter_employmenttype_parent_and_more'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='days_to_hire',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='first_interview_timeline',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='second_interview_timeline',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_timeline',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.workflowstage'),
        ),
    ]
