# Generated by Django 5.1 on 2024-11-19 15:31

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_remove_jobapplication_days_to_hire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='days_to_hire',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('posted_timeline'), '+', models.F('screening_timeline')), '+', models.F('interview_timeline')), '+', models.F('onboarding_timeline')), output_field=models.PositiveIntegerField()),
        ),
    ]
