# Generated by Django 5.1 on 2024-11-21 16:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_businessuser_status'),
        ('jobs', '0026_jobapplication_days_to_hire'),
        ('settings', '0002_workflowstage_order_workflowstage_phase_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentApplicationStageTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timeline', models.PositiveSmallIntegerField(default=0)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobapplication')),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.role')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.workflowstage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
