# Generated by Django 5.1 on 2024-11-28 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_businessuser_status'),
        ('jobs', '0027_talentapplicationstagetimeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_by', to='accounts.businessuser'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='recruiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruiter', to='accounts.businessuser'),
        ),
    ]
