# Generated by Django 5.1 on 2024-11-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_jobpost_posted_by_alter_jobpost_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='jobs/logos'),
        ),
    ]
