# Generated by Django 5.1 on 2024-11-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_job_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='job',
            name='benefits',
            field=models.JSONField(default=list),
        ),
    ]
