# Generated by Django 5.1 on 2024-12-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0030_job_responsibilities_alter_job_benefits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='annual_bonus_currency',
        ),
        migrations.RemoveField(
            model_name='job',
            name='annual_bonus_max',
        ),
        migrations.RemoveField(
            model_name='job',
            name='annual_bonus_min',
        ),
        migrations.RemoveField(
            model_name='job',
            name='annual_salary_currency',
        ),
        migrations.RemoveField(
            model_name='job',
            name='annual_salary_max',
        ),
        migrations.RemoveField(
            model_name='job',
            name='annual_salary_min',
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('paused', 'paused'), ('posted', 'posted'), ('closed', 'closed')], default='posted', max_length=16),
        ),
    ]
