# Generated by Django 5.1 on 2024-12-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0031_remove_job_annual_bonus_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='additional_hours_max',
        ),
        migrations.RemoveField(
            model_name='job',
            name='additional_hours_min',
        ),
        migrations.RemoveField(
            model_name='job',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='job',
            name='recruiter',
        ),
        migrations.RemoveField(
            model_name='job',
            name='same_job_post_recruiter',
        ),
        migrations.RemoveField(
            model_name='job',
            name='share_compensation',
        ),
        migrations.RemoveField(
            model_name='job',
            name='status',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='location_type',
        ),
        migrations.AddField(
            model_name='job',
            name='additional_hours_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='additional_hours_start',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='flexible_availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='lunch_break_time',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='benefits',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='share_compensation',
            field=models.BooleanField(default=True),
        ),
    ]
