# Generated by Django 5.1 on 2024-12-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0032_remove_job_additional_hours_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='accept_privacy',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='is_available',
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('paused', 'paused'), ('posted', 'posted'), ('closed', 'closed')], default='draft', max_length=16),
        ),
    ]
