# Generated by Django 5.1 on 2024-12-10 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0033_remove_jobapplication_accept_privacy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requiredattribute',
            old_name='business_model',
            new_name='business_models',
        ),
    ]
