# Generated by Django 5.1 on 2024-12-12 07:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0034_rename_business_model_requiredattribute_business_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='option',
        ),
        migrations.AddField(
            model_name='answer',
            name='options',
            field=models.ManyToManyField(to='jobs.questionoption'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.screeningquestion'),
        ),
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='AnswerAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='answers')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.answer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='OtherSkill',
        ),
    ]
