# Generated by Django 5.1 on 2024-12-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0035_remove_answer_option_answer_options_answer_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='score',
        ),
        migrations.AddField(
            model_name='answer',
            name='files',
            field=models.JSONField(default=list),
        ),
    ]
