# Generated by Django 5.1 on 2024-12-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0036_remove_answer_score_answer_files'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerAttachment',
        ),
    ]
