# Generated by Django 5.1 on 2024-12-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0037_delete_answerattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='files',
            field=models.JSONField(default=list, null=True),
        ),
    ]
