# Generated by Django 5.1 on 2024-12-16 14:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_talent_months_of_experience'),
        ('jobs', '0038_alter_answer_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_email_shares', models.PositiveIntegerField(default=0)),
                ('job_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobpost')),
                ('weekly_viewers', models.ManyToManyField(blank=True, to='accounts.talent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
