# Generated by Django 5.1 on 2024-12-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0039_jobpostmetrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpostmetrics',
            name='weekly_viewers',
        ),
        migrations.AddField(
            model_name='jobpostmetrics',
            name='weekly_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
