# Generated by Django 5.1 on 2024-12-18 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0040_remove_jobpostmetrics_weekly_viewers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostmetrics',
            name='job_post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobpost'),
        ),
    ]
