# Generated by Django 5.1 on 2024-12-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0041_alter_jobpostmetrics_job_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='min_match_score',
            field=models.FloatField(null=True),
        ),
    ]
