# Generated by Django 5.1 on 2024-12-31 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0042_job_min_match_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='date_posted',
        ),
    ]
