# Generated by Django 5.1 on 2025-01-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0043_remove_jobpost_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='date_posted',
            field=models.DateTimeField(null=True),
        ),
    ]
