# Generated by Django 5.1 on 2025-02-17 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0043_remove_jobpost_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.qualification'),
        ),
        migrations.AlterField(
            model_name='job',
            name='responsibilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='job',
            name='technological_requirement',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_structure',
            field=models.CharField(blank=True, choices=[('remote', 'remote'), ('hybrid', 'hybrid'), ('in office', 'in office')], null=True),
        ),
    ]
