# Generated by Django 5.1 on 2025-02-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0044_alter_job_qualification_alter_job_responsibilities_and_more'),
        ('jobs', '0044_jobpost_date_posted'),
    ]

    operations = [
    ]
