# Generated by Django 5.1 on 2025-02-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0045_merge_20250217_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='business_models',
            field=models.ManyToManyField(blank=True, to='jobs.businessmodel'),
        ),
    ]
