# Generated by Django 5.1 on 2025-02-28 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_customercase_reason_alter_customercase_subject_and_more'),
        ('jobs', '0046_alter_job_business_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobpost'),
        ),
        migrations.AlterField(
            model_name='jobapplicationwithdrawal',
            name='job_post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobpost'),
        ),
        migrations.AlterField(
            model_name='jobapplicationwithdrawal',
            name='talent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.talent'),
        ),
        migrations.AlterField(
            model_name='jobpostmetrics',
            name='job_post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobpost'),
        ),
    ]
