# Generated by Django 5.1 on 2025-03-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0047_alter_jobapplication_job_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='postal_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
