# Generated by Django 5.1 on 2025-03-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0048_alter_jobpost_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='lunch_break',
            field=models.CharField(choices=[('paid', 'paid'), ('unpaid', 'unpaid')], max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='technological_requirement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('paused', 'paused'), ('posted', 'posted'), ('closed', 'closed')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='screeningquestion',
            name='type',
            field=models.CharField(choices=[('single select', 'single select'), ('multi select', 'multi select'), ('text', 'text'), ('file', 'file')], max_length=50),
        ),
    ]
