# Generated by Django 5.1 on 2025-03-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0050_alter_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='available_for_schedule',
            field=models.BooleanField(default=True),
        ),
    ]
