# Generated by Django 5.1 on 2025-04-22 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_alter_business_name'),
        ('jobs', '0051_jobapplication_available_for_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='benefits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_by', to='accounts.businessuser'),
        ),
    ]
