# Generated by Django 5.1 on 2025-04-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0052_jobfilter_job_level_alter_jobpost_benefits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
    ]
