# Generated by Django 5.1 on 2025-04-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0053_alter_job_qualification_delete_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfilter',
            name='location_type',
            field=models.CharField(choices=[('remote', 'remote'), ('hybrid', 'hybrid'), ('in office', 'in office')], default='in office', null=True),
        ),
        migrations.AlterField(
            model_name='jobfilter',
            name='years_of_experience',
            field=models.PositiveSmallIntegerField(default=1, null=True),
        ),
    ]
