# Generated by Django 5.1 on 2025-04-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0052_alter_jobpost_benefits_alter_jobpost_posted_by'),
        ('jobs', '0055_jobalert'),
    ]

    operations = [
    ]
