# Generated by Django 5.1 on 2025-05-12 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_talent_role_alter_talent_cv'),
        ('jobs', '0056_merge_20250422_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobfilter',
            name='department',
        ),
        migrations.RemoveField(
            model_name='jobfilter',
            name='role',
        ),
        migrations.AddField(
            model_name='jobfilter',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.business'),
        ),
        migrations.AddField(
            model_name='jobfilter',
            name='job_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role'),
        ),
        migrations.AlterField(
            model_name='jobfilter',
            name='years_of_experience',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
