# Generated by Django 5.1 on 2025-05-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0057_remove_jobfilter_department_remove_jobfilter_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfilter',
            name='location_type',
            field=models.CharField(choices=[('remote', 'remote'), ('hybrid', 'hybrid'), ('in office', 'in office')], default=None, null=True),
        ),
    ]
