# Generated by Django 5.1 on 2025-05-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_talent_role_alter_talent_cv'),
        ('jobs', '0058_alter_jobfilter_location_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobfilter',
            name='location_type',
        ),
        migrations.RemoveField(
            model_name='jobfilter',
            name='office_location',
        ),
        migrations.RemoveField(
            model_name='jobfilter',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='jobfilter',
            name='location',
            field=models.ManyToManyField(blank=True, to='accounts.country'),
        ),
        migrations.AddField(
            model_name='jobfilter',
            name='work_structure',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='jobfilter',
            name='yoe',
            field=models.JSONField(default=list),
        ),
        migrations.RemoveField(
            model_name='jobfilter',
            name='company',
        ),
        migrations.RemoveField(
            model_name='jobfilter',
            name='employment_type',
        ),
        migrations.RemoveField(
            model_name='jobfilter',
            name='job_level',
        ),
        migrations.RemoveField(
            model_name='jobfilter',
            name='job_role',
        ),
        migrations.RemoveField(
            model_name='jobfilter',
            name='minimum_education_level',
        ),
        migrations.AddField(
            model_name='jobfilter',
            name='company',
            field=models.ManyToManyField(blank=True, to='accounts.business'),
        ),
        migrations.AddField(
            model_name='jobfilter',
            name='employment_type',
            field=models.ManyToManyField(blank=True, to='jobs.employmenttype'),
        ),
        migrations.AddField(
            model_name='jobfilter',
            name='job_level',
            field=models.ManyToManyField(blank=True, to='jobs.joblevel'),
        ),
        migrations.AddField(
            model_name='jobfilter',
            name='job_role',
            field=models.ManyToManyField(blank=True, to='accounts.role'),
        ),
        migrations.AddField(
            model_name='jobfilter',
            name='minimum_education_level',
            field=models.ManyToManyField(blank=True, to='accounts.educationlevel'),
        ),
    ]
