# Generated by Django 5.1 on 2025-06-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0059_remove_jobfilter_location_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfilter',
            name='sort_by',
            field=models.JSONField(default=list),
        ),
    ]
