# Generated by Django 5.1 on 2025-06-11 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0060_jobfilter_sort_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobFilter',
        ),
    ]
