# Generated by Django 5.1 on 2025-06-17 18:28

from django.db import migrations


def load_business_models(apps, schema_editor):
    from jobs.constants import BUSINESS_MODELS
    BusinessModel = apps.get_model("jobs", "BusinessModel")
    business_models = list()
    for obj in BUSINESS_MODELS:
        business_models.append(BusinessModel(
            name = obj
        ))
    BusinessModel.objects.bulk_create(business_models)


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0061_delete_jobfilter'),
    ]

    operations = [
        migrations.RunPython(load_business_models)
    ]
