# Generated by Django 5.1 on 2025-06-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0062_auto_20250617_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='city',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='province',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
