# Generated by Django 5.1 on 2025-06-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0063_jobpost_city_alter_jobpost_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='additional_skills',
            field=models.TextField(null=True),
        ),
    ]
