# Generated by Django 5.1 on 2025-06-20 15:25

from django.db import migrations


def assign_items(apps, schema_editor):
    from accounts.constants import EDUCATION_LEVEL
    EducationLevel = apps.get_model("accounts", "EducationLevel")
    Industry = apps.get_model("accounts", "Industry")
    Skill = apps.get_model("accounts", "Skill")
    Experience = apps.get_model("accounts", "Experience")
    Role = apps.get_model("accounts", "Role")
    Job = apps.get_model("jobs", "Job")
    Department = apps.get_model("accounts", "Department")
    RequiredAttribute = apps.get_model("jobs", "RequiredAttribute")
    TalentApplicationStageTimeline = apps.get_model("jobs", "TalentApplicationStageTimeline")

    jobs = Job.objects.iterator()

    for job in jobs:
        skills = Skill.objects.order_by('?')[:5]
        job.skills.add(*skills)
        job.department = Department.objects.all().order_by('?').first()
        job.role = Role.objects.all().order_by('?').first()
        job.save()

    attrs = RequiredAttribute.objects.iterator()
    for attr in attrs:
        attr.role = Role.objects.all().order_by('?').first()

    timelines =  TalentApplicationStageTimeline.objects.iterator()
    for timeline in timelines:
        timeline.job_role = Role.objects.all().order_by('?').first()

    experiences = Experience.objects.iterator()
    for experience in experiences:
        experience.role = Role.objects.all().order_by('?').first()

    for level_dict in EDUCATION_LEVEL:
        industry = Industry.objects.filter(name__iexact=level_dict["industry"]).first()
        if industry:
            EducationLevel.objects.filter(level=level_dict["education"]).update(industry=industry)





class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0064_job_additional_skills'),
    ]

    operations = [
        migrations.RunPython(assign_items)
    ]
