# Generated by Django 5.1 on 2025-07-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0065_auto_20250620_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='office_address',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
