# Generated by Django 5.1 on 2025-07-16 18:33

from django.db import migrations

def update_business_models(apps, schema_editor):
    from jobs.constants import BUSINESS_MODELS
    BusinessModel = apps.get_model("jobs", "BusinessModel")
    bm_ids = list()
    for business_model in BUSINESS_MODELS:
        bm = BusinessModel.objects.filter(name__iexact=business_model).first()
        if bm:
            bm_ids.append(bm.id)
        else:
            bm = BusinessModel(name=business_model.title())
            bm.save()
            bm_ids.append(bm.id)
    BusinessModel.objects.exclude(id__in=bm_ids).delete()



class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0066_alter_job_office_address_alter_job_title'),
    ]

    operations = [
        migrations.RunPython(update_business_models),
    ]
