# Generated by Django 5.1 on 2025-07-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0067_auto_20250716_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='lunch_break',
            field=models.CharField(choices=[('paid', 'paid'), ('unpaid', 'unpaid')], max_length=50, null=True),
        ),
    ]
