# Generated by Django 5.1 on 2025-07-22 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0068_alter_job_lunch_break'),
        ('settings', '0003_alter_workflowstage_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='settings.workflowstage'),
        ),
    ]
