# Generated by Django 5.1 on 2025-07-23 09:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20250707_1850'),
        ('jobs', '0068_alter_job_lunch_break'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredSecondaryLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.language')),
                ('required_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.requiredattribute')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='requiredattribute',
            name='secondary_languages',
            field=models.ManyToManyField(through='jobs.RequiredSecondaryLanguage', to='core.language'),
        ),
    ]
