# Generated by Django 5.1 on 2025-07-23 15:59

from django.db import migrations

def migrate_required_skills_to_through_model(apps, schema_editor):
    RequiredSkill = apps.get_model("jobs", "RequiredSkill")
    Job = apps.get_model("jobs", "Job")
    all_jobs = Job.objects.all()
    for job in all_jobs:
        required_attribute = job.requiredattribute
        skills = required_attribute.skills.all()
        for skl in skills:
            RequiredSkill.objects.get_or_create(
                required_attribute=required_attribute,
                skill=skl
            )



class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0070_requiredskill_requiredattribute_skills2'),
    ]

    operations = [
        migrations.RunPython(migrate_required_skills_to_through_model)
    ]
