# Generated by Django 5.1 on 2025-07-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0071_jobinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='last_refreshed',
            field=models.DateTimeField(null=True),
        ),
    ]
