# Generated by Django 5.1 on 2025-07-24 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0071_auto_20250723_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requiredattribute',
            name='skills',
        ),
    ]
