# Generated by Django 5.1 on 2025-07-24 18:35
import logging

from django.db import migrations
from django.db.migrations import RunPython
from django.db.models import F


def update_job_post_last_refreshed(apps, schema_editor):
    JobPost = apps.get_model('jobs', 'JobPost')
    JobPost.objects.update(last_refreshed=F("created_at"))
    logging.info("Updated job_posts last_refreshed")
class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0072_jobpost_last_refreshed'),
    ]

    operations = [
        RunPython(update_job_post_last_refreshed)
    ]
