# Generated by Django 5.1 on 2025-07-24 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0072_remove_requiredattribute_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requiredattribute',
            old_name='skills2',
            new_name='skills',
        ),
    ]
