# Generated by Django 5.1 on 2025-07-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0073_auto_20250724_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='additional_hours_end',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='additional_hours_start',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
