# Generated by Django 5.1 on 2025-07-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0073_rename_skills2_requiredattribute_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableday',
            name='utc_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='availableday',
            name='utc_start_time',
            field=models.TimeField(null=True),
        ),
    ]
