# Generated by Django 5.1 on 2025-07-25 15:19

from django.db import migrations
from helpers.utils import to_utc


def add_timezones_to_availability(apps, schema_editor):
    AvailableDay = apps.get_model("jobs", "AvailableDay")
    available_days = AvailableDay.objects.all()
    for i in available_days:
        if i.start_time:
            i.utc_start_time = to_utc(i.start_time, tzinfo=i.job.availability_timezone.key)
        if i.end_time:
            i.utc_end_time = to_utc(i.end_time, tzinfo=i.job.availability_timezone.key)


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0074_availableday_utc_end_time_and_more'),
    ]

    operations = [
        migrations.RunPython(add_timezones_to_availability)
    ]
