# Generated by Django 5.1 on 2025-07-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0074_alter_job_additional_hours_end_and_more'),
        ('jobs', '0075_auto_20250725_1519'),
    ]

    operations = [
    ]
