# Generated by Django 5.1 on 2025-07-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20250723_1944'),
        ('jobs', '0076_merge_20250726_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='additional_languages',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='core.language'),
        ),
    ]
