# Generated by Django 5.1 on 2025-07-31 13:29

from django.db import migrations

def rename_employment_type(apps, schema_editor):
    EmploymentType = apps.get_model("jobs", "EmploymentType")
    EmploymentType.objects.filter(name__iexact="your entity").update(name="Own Entity")


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0077_alter_job_additional_languages'),
    ]

    operations = [
        migrations.RunPython(rename_employment_type),
    ]
