# Generated by Django 5.1 on 2025-08-06 10:24

from django.db import migrations
from django.db.models import F


def update_last_refreshed(apps, schema_editor):
    JobPost = apps.get_model('jobs', 'JobPost')
    JobPost.objects.filter(last_refreshed__isnull=True).update(last_refreshed=F("created_at"))

class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0078_auto_20250731_1429'),
    ]

    operations = [
        migrations.RunPython(update_last_refreshed),
    ]
