# Generated by Django 5.1 on 2025-08-08 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0079_auto_20250806_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='last_refreshed',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
