# Generated by Django 5.1 on 2025-08-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0080_alter_jobpost_last_refreshed'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentapplicationstagetimeline',
            name='exit_date',
            field=models.DateTimeField(null=True),
        ),
    ]
