# Generated by Django 5.1 on 2025-08-12 00:12
from datetime import timedelta

from django.db import migrations

def update_exit_date(apps, schema_editor):
    TalentApplicationStageTimeline = apps.get_model('jobs', 'TalentApplicationStageTimeline')
    for tast in TalentApplicationStageTimeline.objects.iterator():
        if tast.application.stage != tast.stage:
            tast.exit_date = tast.created_at + timedelta(days=tast.timeline)
            tast.save()
    return



class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0081_talentapplicationstagetimeline_exit_date'),
    ]

    operations = [
        migrations.RunPython(update_exit_date),
    ]
