# Generated by Django 5.1 on 2025-08-12 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0082_auto_20250812_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='days_to_hire',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='interview_timeline',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='onboarding_timeline',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='posted_timeline',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='screening_timeline',
        ),
    ]
