# Generated by Django 5.1 on 2025-08-12 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0083_remove_jobapplication_days_to_hire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentapplicationstagetimeline',
            name='timeline',
        ),
    ]
