# Generated by Django 5.1 on 2025-08-15 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0084_remove_talentapplicationstagetimeline_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableday',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_days', to='jobs.job'),
        ),
    ]
