# Generated by Django 5.1 on 2025-08-14 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20250801_1049'),
        ('jobs', '0084_remove_talentapplicationstagetimeline_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.state'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='suburb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city'),
        ),
    ]
