# Generated by Django 5.1 on 2025-08-14 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0085_jobpost_state_jobpost_suburb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='city',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='province',
        ),
    ]
