# Generated by Django 5.1 on 2025-08-14 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0086_remove_jobpost_city_remove_jobpost_province'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='suburb',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='state',
            new_name='province',
        ),
    ]
