# Generated by Django 5.1 on 2025-08-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0085_alter_availableday_job'),
        ('jobs', '0087_rename_suburb_jobpost_city_and_more'),
    ]

    operations = [
    ]
