# Generated by Django 5.1 on 2025-09-30 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0088_merge_20250818_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableday',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
    ]
