# Generated by Django 5.1 on 2025-10-01 12:21

import django.db.models.functions.comparison
import jobs.db_functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0089_alter_availableday_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='refresh_order',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.comparison.Coalesce(django.db.models.functions.comparison.Cast(jobs.db_functions.Epoch('last_refreshed'), models.IntegerField()), models.Value(0)), output_field=models.IntegerField()),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='last_refreshed',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
