# Generated by Django 5.1 on 2025-10-02 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0090_jobpost_refresh_order_alter_jobpost_last_refreshed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='match',
        ),
    ]
