# Generated by Django 5.1 on 2025-10-03 10:50

import django.db.models.functions.comparison
import jobs.db_functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0091_remove_jobapplication_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='posted_order',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.comparison.Coalesce(django.db.models.functions.comparison.Cast(jobs.db_functions.Epoch('date_posted'), models.IntegerField()), models.Value(0)), output_field=models.IntegerField()),
        ),
    ]
