# Generated by Django 5.1 on 2025-10-13 09:06

from django.db import migrations

def update_job_level(apps, schema_editor):
    JobLevel = apps.get_model('jobs', 'JobLevel')
    JobLevel.objects.filter(name__iexact="executive chief officer").update(name="chief executive officer")


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0092_jobpost_posted_order'),
    ]

    operations = [
        migrations.RunPython(update_job_level),
    ]
