# Generated by Django 5.1 on 2025-10-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0073_alter_talent_skills'),
        ('jobs', '0093_auto_20251013_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(blank=True, to='accounts.skill'),
        ),
        migrations.AlterField(
            model_name='requiredattribute',
            name='business_models',
            field=models.ManyToManyField(blank=True, to='jobs.businessmodel'),
        ),
    ]
