# Generated by Django 5.1 on 2025-10-21 16:23

import core.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0094_alter_job_skills_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='annual_bonus_currency',
            new_name='salary_bonus_currency',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='annual_bonus_max',
            new_name='salary_bonus_max',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='annual_bonus_min',
            new_name='salary_bonus_min',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='annual_salary_currency',
            new_name='salary_currency',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='annual_salary_max',
            new_name='salary_max',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='annual_salary_min',
            new_name='salary_min',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary_bonus_type',
            field=models.CharField(choices=[('Hourly', 'Hourly'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi-Weekly'), ('Monthly', 'Monthly'), ('Bi-Monthly', 'Bi-Monthly'), ('Annually', 'Annually')], default=core.enums.SalaryType['ANNUALLY'], max_length=50),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary_type',
            field=models.CharField(choices=[('Hourly', 'Hourly'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi-Weekly'), ('Monthly', 'Monthly'), ('Bi-Monthly', 'Bi-Monthly'), ('Annually', 'Annually')], default=core.enums.SalaryType['ANNUALLY'], max_length=50),
        ),
    ]
