# Generated by Django 5.1 on 2025-10-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0095_rename_annual_bonus_currency_jobpost_salary_bonus_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='salary_bonus_type',
            field=models.CharField(choices=[('Hourly', 'Hourly'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi-Weekly'), ('Monthly', 'Monthly'), ('Bi-Monthly', 'Bi-Monthly'), ('Annually', 'Annually')], default='Annually', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary_type',
            field=models.CharField(choices=[('Hourly', 'Hourly'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi-Weekly'), ('Monthly', 'Monthly'), ('Bi-Monthly', 'Bi-Monthly'), ('Annually', 'Annually')], default='Annually', max_length=50),
        ),
    ]
