# Generated by Django 5.1 on 2025-10-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0096_alter_jobpost_salary_bonus_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='salary_bonus_type',
            field=models.CharField(choices=[('Hourly', 'Hourly'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi-Weekly'), ('Monthly', 'Monthly'), ('Bi-Monthly', 'Bi-Monthly'), ('Annually', 'Annually')], default='Annually', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary_type',
            field=models.CharField(choices=[('Hourly', 'Hourly'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi-Weekly'), ('Monthly', 'Monthly'), ('Bi-Monthly', 'Bi-Monthly'), ('Annually', 'Annually')], default='Annually', max_length=50, null=True),
        ),
    ]
