# Generated by Django 5.1 on 2025-11-13 17:59

from django.db import migrations

def assign_role_to_jobs(apps, schema_editor):
    Job = apps.get_model("jobs", "Job")
    Role = apps.get_model("accounts", "Role")

    for job in Job.objects.filter(role__isnull=True).iterator():
        job.role = Role.objects.order_by("?").first()
        job.save()




class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0097_alter_jobpost_salary_bonus_type_and_more'),
    ]

    operations = [
        migrations.RunPython(assign_role_to_jobs)
    ]
