# Generated by Django 5.1 on 2025-11-20 11:02

from django.db import migrations
from django.db.models import F

from apps.jobs.enums import JobStatusType


def handle_null_date_posted_values(apps, schema_editor):
    JobPost = apps.get_model("jobs", "JobPost")
    JobPost.objects.filter(date_posted__isnull=True, status=JobStatusType.POSTED.value).update(date_posted=F("created_at"))
    
class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0098_auto_20251113_1859'),
    ]

    operations = [
        migrations.RunPython(handle_null_date_posted_values)
    ]
