# Generated by Django 5.1 on 2025-11-20 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0088_remove_talentfilter_educational_level_and_more'),
        ('jobs', '0099_auto_20251120_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='edited_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_job_posts', to='accounts.businessuser'),
        ),
    ]
