# Generated by Django 5.1 on 2025-11-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0100_jobpost_edited_at_jobpost_edited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='city_text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
