# Generated by Django 5.1 on 2025-11-28 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0101_jobpost_city_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='city',
        ),
    ]
