# Generated by Django 5.1 on 2025-11-28 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0102_remove_jobpost_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='city_text',
            new_name='city',
        ),
    ]
