# Generated by Django 5.1 on 2025-11-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0103_rename_city_text_jobpost_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='promotion_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
