# Generated by Django 5.1 on 2025-12-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0104_jobpost_promotion_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
