# Generated by Django 5.1 on 2025-12-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0105_jobpost_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='responsibilities_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
