# Generated by Django 5.1 on 2025-12-04 02:22

from django.db import migrations

def copy_responsibilities_to_text(apps, schema_editor):
    Job = apps.get_model('jobs', 'Job')
    for job in Job.objects.iterator():
        if job.responsibilities:
            job.responsibilities_text = f'<ul>{"".join(map(lambda x: f"<li>{x}</li>", job.responsibilities))}</ul>'
            job.save(update_fields=['responsibilities_text'])

class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0106_job_responsibilities_text'),
    ]

    operations = [
        migrations.RunPython(copy_responsibilities_to_text),
    ]
