# Generated by Django 5.1 on 2025-12-04 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0107_auto_20251203_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='responsibilities',
        ),
    ]
