# Generated by Django 5.1 on 2025-12-04 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0108_remove_job_responsibilities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='responsibilities_text',
            new_name='responsibilities',
        ),
    ]
