# Generated by Django 5.1 on 2026-01-09 12:01

from django.db import migrations

from jobs.enums import TechnologicalRequirementsEnum


def update_job_technological_requirements(apps, schema_editor):

    Job = apps.get_model("jobs", "Job")

    Job.objects.filter(technological_requirement__iexact="either").update(technological_requirement=TechnologicalRequirementsEnum.EITHER.value)


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0112_jobpostexport'),
    ]

    operations = [
        migrations.RunPython(update_job_technological_requirements)
    ]
