# Generated by Django 5.1 on 2026-01-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0113_auto_20260109_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='linked_in_tags',
            field=models.JSONField(default=list),
        ),
    ]
