# Generated by Django 5.1 on 2026-01-15 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0114_jobpost_linked_in_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='linked_in_tags',
            new_name='linkedin_tags',
        ),
    ]
