# Generated by Django 5.1 on 2026-01-16 18:27

from django.db import migrations, models
from django.db.models import Value, F
from django.db.models.functions import Concat


def update_job_responsibilities(apps, schema_editor):
    Job = apps.get_model('jobs', 'Job')
    Job.objects.filter(responsibilities__isnull=False).exclude(responsibilities__startswith="<ul>").update(
        responsibilities=Concat(Value("<ul>"), F("responsibilities"), Value("</ul>"), output_field=models.TextField())
    )
class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0115_rename_linked_in_tags_jobpost_linkedin_tags'),
    ]

    operations = [
        migrations.RunPython(update_job_responsibilities)
    ]
