# Generated by Django 5.1 on 2026-04-28 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0102_bannedaccount_alter_businessclient_business_and_more'),
        ('jobs', '0116_auto_20260116_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_job_posts', to='accounts.businessuser'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='recruiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_job_posts', to='accounts.businessuser'),
        ),
    ]
