# Generated by Django 5.1 on 2026-05-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0117_alter_jobpost_posted_by_alter_jobpost_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cv_required',
            field=models.BooleanField(default=True),
        ),
    ]
