# Generated by Django 5.1 on 2026-06-12 09:34

from django.db import migrations


def rename_employment_type(apps, schema_editor):
    EmploymentType = apps.get_model('jobs', 'EmploymentType')
    EmploymentType.objects.filter(name="Full-Time Direct Employee").update(name="Full-Time Employee")

class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0118_job_cv_required'),
    ]

    operations = [
        migrations.RunPython(rename_employment_type)
    ]
