# Generated by Django 5.1 on 2026-06-16 10:47

import django.db.models.deletion
import jobs.enums
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0109_merge_20260611_1057'),
        ('jobs', '0119_auto_20260612_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicationNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_note', models.TextField(blank=True, null=True)),
                ('interview_note', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.CharField(choices=jobs.enums.RejectionReasonType.choices, max_length=50)),
                ('rejection_note', models.TextField(blank=True, null=True)),
                ('application_note_at', models.DateTimeField(null=True)),
                ('interview_note_at', models.DateTimeField(null=True)),
                ('rejection_note_at', models.DateTimeField(null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='jobs.jobapplication')),
                ('application_note_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_notes', to='accounts.businessuser')),
                ('interview_note_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_notes', to='accounts.businessuser')),
                ('rejection_note_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejection_notes', to='accounts.businessuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
