# Generated by Django 5.1 on 2026-06-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0110_alter_talent_viewers_talentviewer'),
        ('jobs', '0119_auto_20260612_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewed_job_posts', to='accounts.talent'),
        ),
    ]
