# Generated by Django 5.1 on 2026-06-25 08:49

import jobs.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0120_jobapplicationnotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicationnotes',
            name='rejection_reason',
            field=models.CharField(choices=jobs.enums.RejectionReasonType.choices, max_length=50, null=True),
        ),
    ]
