# Generated by Django 5.1 on 2026-06-30 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0120_jobpost_viewers'),
        ('jobs', '0121_alter_jobapplicationnotes_rejection_reason'),
    ]

    operations = [
    ]
