# Generated by Django 5.1 on 2024-09-19 17:03

from django.db import migrations

from core.constants import CURRENCY


def load_currency(apps, schema_editor):
    Currency = apps.get_model("core", "Currency")
    for currency in CURRENCY:
        Currency.objects.create(
            name=currency["name"],
            abbreviation=currency["abbreviation"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_currency)
    ]


