# Generated by Django 5.1 on 2025-07-07 17:50

from django.db import migrations

from apps.core.constants import CURRENCY


def load_currency(apps, schema_editor):
    Currency = apps.get_model("core", "Currency")
    for currency in CURRENCY:
        Currency.objects.filter(
            name=currency["name"],
            abbreviation=currency["abbreviation"]
        ).update(symbol=currency["symbol"])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_currency_symbol'),
    ]

    operations = [
        migrations.RunPython(load_currency),
    ]
