# Generated by Django 5.1 on 2025-09-30 11:05

from django.db import migrations

from core.constants import CURRENCY


def update_currency(apps, schema_editor):
    Currency = apps.get_model('core', 'Currency')
    for currency in CURRENCY:
        curr = Currency.objects.filter(abbreviation__iexact=currency['code'])
        if curr.exists():
            curr.update(name=currency['name'], symbol=currency['symbol'], abbreviation=currency['code'])
        else:
            Currency.objects.create(name=currency['name'], symbol=currency['symbol'], abbreviation=currency['code'])
    return

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20250801_1049'),
    ]

    operations = [
        migrations.RunPython(update_currency),
    ]
