# Generated by Django 5.1 on 2025-09-30 11:18

from core.constants import CURRENCY
from django.db import migrations


def update_currency(apps, schema_editor):
    Currency = apps.get_model("core", "Currency")
    for currency in CURRENCY:
        curr = Currency.objects.filter(abbreviation__iexact=currency["abbreviation"]).first()
        if not curr:
            Currency.objects.create(**currency)
        else:
            curr.symbol = currency["symbol"]
            curr.abbreviation = currency["abbreviation"]
            curr.name = currency["name"]
            curr.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20250801_1049'),
    ]

    operations = [
        migrations.RunPython(update_currency),
    ]
