# Generated by Django 5.1 on 2025-10-02 13:03

from django.db import migrations

def remove_duplicate_currency(apps, schema_editor):
    Currency = apps.get_model('core', 'Currency')
    abbreviations = Currency.objects.values_list('abbreviation', flat=True).distinct()
    for abbreviation in abbreviations:
        count = Currency.objects.filter(abbreviation__iexact=abbreviation).count()
        if count > 1:
            last_currency = Currency.objects.filter(abbreviation__iexact=abbreviation).last()
            Currency.objects.filter(abbreviation__iexact=abbreviation).exclude(id=last_currency.id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20250930_1218'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_currency)
    ]
