# Generated by Django 5.1 on 2025-10-14 14:39

from django.db import migrations



def delete_duplicate_languages(apps, schema_editor):
    from core.constants import LANGUAGES
    Language = apps.get_model('core', 'Language')
    for language in LANGUAGES:
        languages = Language.objects.filter(name__istartswith=language)
        if languages.count() > 1:
            f = languages.filter(name__iexact=language).first()
            languages.exclude(id=f.id).delete()
        elif languages.count() == 0:
            Language.objects.create(name=language)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20251002_1428'),
    ]

    operations = [
        migrations.RunPython(delete_duplicate_languages)
    ]
