# Generated by Django 5.1 on 2025-11-16 10:33
import logging

from django.db import migrations, transaction

from helpers.utils import read_json_generator


def load_data_to_db(apps, schema_editor):
    """
    Optimized function to load large amounts of country, state, and city data from JSON into the database.

    Args:
        apps: Django apps registry
        schema_editor: Django schema editor
        batch_size (int): Number of objects to process in each batch (default: 5000)
    """
    batch_size = 5000

    Country = apps.get_model("accounts", "Country")
    State = apps.get_model("core", "State")
    City = apps.get_model("core", "City")

    # Pre-fetch existing objects in chunks to reduce memory usage
    def get_existing_objects(model, fields, chunk_size=10000):
        queryset = model.objects.all().only(*fields)
        for i in range(0, queryset.count(), chunk_size):
            yield from queryset[i:i + chunk_size]

    # Cache existing objects with composite keys
    existing_countries = {
        (c.name.lower(), c.code.lower()): c
        for c in get_existing_objects(Country, ['id', 'name', 'code', 'external_id'])
    }
    existing_states = {
        (s.country_id, s.name.lower(), s.code.lower() if s.code else None): s
        for s in get_existing_objects(State, ['id', 'country_id', 'name', 'code', 'external_id'])
    }
    existing_cities = {
        (c.state_id, c.name.lower()): c
        for c in get_existing_objects(City, ['id', 'state_id', 'name', 'external_id'])
    }

    # Lists for batch processing
    countries_to_create = []
    countries_to_update = []
    states_to_create = []
    cities_to_create = []

    location_data = read_json_generator("apps/core/location_seeder/countries+states+cities.json")

    def process_batch():
        """Helper function to process accumulated objects in a transaction."""
        with transaction.atomic():
            if countries_to_create:
                Country.objects.bulk_create(countries_to_create, batch_size=batch_size)
                logging.info(f"Created {len(countries_to_create)} countries")
                # Update existing_countries cache with newly created objects
                for country in countries_to_create:
                    existing_countries[(country.name.lower(), country.code.lower())] = country
                countries_to_create.clear()

            if countries_to_update:
                Country.objects.bulk_update(countries_to_update, ['external_id'], batch_size=batch_size)
                logging.info(f"Updated {len(countries_to_update)} countries")
                countries_to_update.clear()

            if states_to_create:
                State.objects.bulk_create(states_to_create, batch_size=batch_size)
                logging.info(f"Created {len(states_to_create)} states")
                # Update existing_states cache with newly created states
                for state in states_to_create:
                    existing_states[(state.country_id, state.name.lower(), state.code.lower() if state.code else None)] = state
                states_to_create.clear()

            if cities_to_create:
                City.objects.bulk_create(cities_to_create, batch_size=batch_size)
                logging.info(f"Created {len(cities_to_create)} cities")
                cities_to_create.clear()

    try:
        for data in location_data:
            country_key = (data["name"].lower(), data["iso2"].lower())

            # Handle Country
            if country_key not in existing_countries:
                country = Country(
                    name=data["name"],
                    code=data["iso2"],
                    external_id=data["id"],
                    phone_code=data['phonecode']
                )
                countries_to_create.append(country)
            else:
                country = existing_countries[country_key]
                country.external_id = data["id"]
                country.phone_code = data["phonecode"]
                countries_to_update.append(country)

            # Ensure country has an ID for state relationships
            country = existing_countries.get(country_key) or country

            # Handle States
            for state_data in data.get("states", []):
                if not state_data:
                    continue

                state_key = (
                country.id if country.id else None, state_data["name"].lower(), state_data["state_code"].lower() if state_data["state_code"] else None)

                if state_key not in existing_states:
                    state = State(
                        country=country,
                        name=state_data["name"],
                        code=state_data["state_code"],
                        external_id=state_data["id"]
                    )
                    states_to_create.append(state)

                # Ensure state has an ID for city relationships
                state = existing_states.get(state_key) or state

                # Handle Cities
                for city_data in state_data.get("cities", []):
                    if not city_data:
                        continue

                    city_key = (state.id if state.id else None, city_data["name"].lower())

                    if city_key not in existing_cities:
                        cities_to_create.append(
                            City(
                                state=state,
                                name=city_data["name"],
                                external_id=city_data["id"]
                            )
                        )

            # Process batch when any list reaches batch_size
            if (len(countries_to_create) >= batch_size or
                    len(countries_to_update) >= batch_size or
                    len(states_to_create) >= batch_size or
                    len(cities_to_create) >= batch_size):
                process_batch()

        # Process any remaining objects
        if any([countries_to_create, countries_to_update, states_to_create, cities_to_create]):
            process_batch()

    except Exception as e:
        logging.error(f"Error processing data: {str(e)}")
        raise

    logging.info("Data loading completed successfully")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20251014_1539'),
    ]

    operations = [
        migrations.RunPython(load_data_to_db)
    ]
