# Generated by Django 5.1 on 2025-11-16 10:54
import logging

from django.db import migrations

from helpers.utils import read_json_generator


def add_phone_code_to_countries(apps, schema_editor):
    Country = apps.get_model("accounts", "Country")

    # Pre-fetch existing objects in chunks to reduce memory usage

    location_data = read_json_generator("apps/core/location_seeder/countries+states+cities.json")

    for data in location_data:
        country = Country.objects.filter(name__iexact=data["name"]).first()
        if country:
            country.phone_code = data["phonecode"]
            country.save()

    logging.info("Data loading completed successfully")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20251116_1133'),
    ]

    operations = [
        migrations.RunPython(add_phone_code_to_countries)
    ]
