# Generated by Django 5.1 on 2025-11-19 08:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20251116_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='GTCSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_auth', models.BooleanField(default=True)),
                ('facebook_auth', models.BooleanField(default=True)),
                ('linkedin_auth', models.BooleanField(default=True)),
                ('google_auth', models.BooleanField(default=True)),
                ('apple_auth', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
