# Generated by Django 5.1 on 2025-11-19 08:59

from django.db import migrations


def create_settings(apps, schema_editor):
    GTCSettings = apps.get_model("core", "GTCSettings")
    GTCSettings.objects.create()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_gtcsettings'),
    ]

    operations = [
        migrations.RunPython(create_settings)
    ]