# Generated by Django 5.1 on 2025-11-29 12:25

from django.db import migrations
from django.db.models import Exists, OuterRef


def create_state_for_stateless_country(apps, schema_editor):
    Country = apps.get_model("accounts", "Country")
    State = apps.get_model("core", "State")
    
    for country in Country.objects.annotate(has_state=Exists(State.objects.filter(country_id=OuterRef('id')))).filter(
        has_state=False
    ).only("id", "name").iterator():
        State.objects.create(name=country.name, country_id=country.id)
    


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20251119_0859'),
    ]

    operations = [
        migrations.RunPython(create_state_for_stateless_country)
    ]
