# Generated by Django 5.1 on 2026-04-24 13:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20251129_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=255)),
                ('month', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('total_time', models.FloatField(default=0.0)),
            ],
            options={
                'unique_together': {('path', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PageMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=255)),
                ('month', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('total_time', models.FloatField(default=0.0)),
            ],
            options={
                'unique_together': {('path', 'month')},
            },
        ),
    ]
