# Generated by Django 5.1 on 2026-04-28 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_apimetric_pagemetric'),
        ('core', '0019_exports'),
    ]

    operations = [
    ]
