# Generated by Django 5.1 on 2024-09-12 14:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_type', models.CharField(choices=[('IMAGE', 'image'), ('DOCUMENT', 'document'), ('AUDIO', 'audio'), ('VIDEO', 'video')])),
                ('file', models.FileField(upload_to='chat_attachments')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.message')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
