# Generated by Django 5.1 on 2024-09-27 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_messageattachment'),
        ('jobs', '0016_alter_jobapplication_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='job',
        ),
        migrations.AddField(
            model_name='message',
            name='job_post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobpost'),
        ),
    ]
