# Generated by Django 5.1 on 2024-10-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_remove_message_job_message_job_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_message_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
