# Generated by Django 5.1 on 2024-11-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
