# Generated by Django 5.1 on 2024-11-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_conversation_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='last_message_time',
            field=models.DateTimeField(null=True),
        ),
    ]
