# Generated by Django 5.1 on 2024-11-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_alter_conversation_last_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='file_type',
            field=models.CharField(choices=[('image', 'IMAGE'), ('document', 'DOCUMENT'), ('audio', 'AUDIO'), ('video', 'VIDEO')]),
        ),
    ]
