# Generated by Django 5.1 on 2024-11-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_alter_messageattachment_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='file_type',
            field=models.CharField(choices=[('image', 'image'), ('document', 'document'), ('audio', 'audio'), ('video', 'video')]),
        ),
    ]
