"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import logging
import os
import sys
from datetime import timedelta
from pathlib import Path

import dj_database_url
import sentry_sdk
from django.conf.global_settings import EMAIL_BACKEND, APPEND_SLASH
from dotenv import load_dotenv
from sentry_sdk.integrations.logging import LoggingIntegration

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if os.environ['DEBUG'].lower() == "true" else False

ALLOWED_HOSTS = [
    "gtc-staging.1840andco.com",
    "gtc-production.1840andco.com",
    "127.0.0.1",
]


# Application definition

INSTALLED_APPS = [
    "daphne",
    "channels",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_q',

    #local
    'accounts',
    'jobs',
    'chats',
    "core",
    "notification",
    "settings",
    "config",

    #3rd party
    "corsheaders",

]

MIDDLEWARE = [
    'django.middleware.gzip.GZipMiddleware',
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'config.middlewares.RequestTimingMiddleware',
    'config.middlewares.DatabaseConnectionMiddleware',
    'config.middlewares.LogUserLastLoginConnectionMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["templates/html", "templates/text"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

CORS_ALLOW_ALL_ORIGINS = True

# # cors settings
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "https://localhost:3000",
#     "http://127.0.0.1:3000",
#      "https://1840gtc.netlify.app"
# ]
#
# CORS_ORIGIN_WHITELIST = [
#     "http://localhost:3000",
#     "https://localhost:3000",
#     "http://127.0.0.1:3000",
#      "https://1840gtc.netlify.app"
# ]

CORS_ALLOW_CREDENTIALS = True



# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


DATABASES = {
    'default': {**dj_database_url.config(
        conn_max_age=60,
        conn_health_checks=True,
    )}
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = "static"
STATIC_DIR = (os.path.join(BASE_DIR.parent, "static"),)
STATICFILES_DIRS = (os.path.join(BASE_DIR, "templates/assets"),)
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

USE_AWS_S3 = False if os.environ.get('USE_AWS_S3', "false").lower() == "false" else True

if USE_AWS_S3:
    STORAGES = {
        "default": {
            "BACKEND": "core.storages.MediaStorage",
            "OPTIONS": {
            },
        },
        "staticfiles": {
            "BACKEND": "core.storages.StaticStorage",
        },
    }

    DEFAULT_FILE_STORAGE = "core.storages.MediaStorage"
    STATICFILES_STORAGE = "core.storages.StaticStorage"

AWS_STORAGE_BUCKET_NAME = os.environ["AWS_STORAGE_BUCKET_NAME"]
AWS_ACCESS_KEY_ID = os.environ['AWS_ACCESS_KEY_ID']
AWS_SECRET_ACCESS_KEY = os.environ['AWS_SECRET_ACCESS_KEY']
AWS_S3_REGION_NAME = 'us-east-1' 
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"
AWS_S3_FILE_OVERWRITE = True
STATICFILES_LOCATION = "static"
STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{STATICFILES_LOCATION}/" if USE_AWS_S3 else STATIC_URL


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "accounts.User"

if "test" in sys.argv:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = "smtp.office365.com"
EMAIL_PORT = 587
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = f"1840 GTC <{EMAIL_HOST_USER}>"


NINJA_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days= 365 * 5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=365 * 5),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

GOOGLE_CLIENT_ID = os.environ["GOOGLE_CLIENT_ID"]
GOOGLE_CLIENT_SECRET = os.environ["GOOGLE_CLIENT_SECRET"]
GOOGLE_REDIRECT_URI = os.environ["GOOGLE_REDIRECT_URI"]
LINKEDIN_CLIENT_ID = os.environ["LINKEDIN_CLIENT_ID"]
LINKEDIN_CLIENT_SECRET =  os.environ["LINKEDIN_CLIENT_SECRET"]
LINKEDIN_REDIRECT_URI = os.environ["LINKEDIN_REDIRECT_URI"]
FACEBOOK_APP_ID= os.environ["FACEBOOK_APP_ID"]
FACEBOOK_APP_SECRET = os.environ["FACEBOOK_APP_SECRET"]
FACEBOOK_APP_ID_ANDROID = os.environ["FACEBOOK_APP_ID_ANDROID"]
FACEBOOK_APP_SECRET_ANDROID = os.environ["FACEBOOK_APP_SECRET_ANDROID"]
FACEBOOK_APP_ID_WEB = os.environ["FACEBOOK_APP_ID_WEB"]
FACEBOOK_APP_SECRET_WEB = os.environ["FACEBOOK_APP_SECRET_WEB"]
FACEBOOK_APP_ID_IOS = os.environ["FACEBOOK_APP_ID_IOS"]
FACEBOOK_APP_SECRET_IOS = os.environ["FACEBOOK_APP_SECRET_IOS"]


REDIS_HOST = os.environ.get("REDIS_HOST", "localhost")
REDIS_PORT = int(os.environ.get("REDIS_PORT", "6379"))

Q_CLUSTER = {
    'name': 'DjangoQCluster',
    'workers': 4,
    'recycle': 500,
    'timeout': -1,
    'save_limit': 250,
    'queue_limit': 500,
    'cpu_affinity': 1,
    'label': 'Django Q',
    # 'orm': 'default',  # Use Django ORM as a fallback for result persistence
    # 'broker': "amqp://guest:guest@localhost:5672/",
    'redis': {
        'host': REDIS_HOST,
        'port': REDIS_PORT,
        'db': 3,
    }
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [f"redis://{REDIS_HOST}:{REDIS_PORT}/2"],
        },
    },
}
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join("media")

# email rendering service
FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:3000")
COMPANY_NAME = "1840 GTC"


WEB_URL = os.environ.get("WEB_URL", "http://localhost:8000")
ZOOM_CLIENT_ID = os.environ.get("ZOOM_CLIENT_ID")
ZOOM_CLIENT_SECRET = os.environ.get("ZOOM_CLIENT_SECRET")

TEAMS_CLIENT_ID = os.environ.get("TEAMS_CLIENT_ID")
TEAMS_CLIENT_SECRET = os.environ.get("TEAMS_CLIENT_SECRET")
USE_SENTRY = True if os.environ.get('USE_SENTRY', "false").lower() == "true" else False

if USE_SENTRY:
    sentry_logging = LoggingIntegration(
        level=logging.INFO,        # Capture INFO and above as breadcrumbs
        event_level=logging.ERROR  # Send ERROR and CRITICAL as full events
    )
    sentry_sdk.init(
        dsn=os.environ.get("SENTRY_DSN"),
        # Set traces_sample_rate to 1.0 to capture 100%
        # of transactions for tracing.
        traces_sample_rate=1.0,
        _experiments={
            # Set continuous_profiling_auto_start to True
            # to automatically start the profiler on when
            # possible.
            "continuous_profiling_auto_start": True,
        },
    )

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        '': {  # Root logger, capturing all messages.
            'handlers': ['console'],
            'level': 'INFO' if DEBUG else 'CRITICAL',
            'propagate': False,
        },
        'config.middlewares.RequestTimingMiddleware': { # Specifically for our middleware.
            'handlers': ['console'],
            'level': 'INFO' if DEBUG else 'CRITICAL',
            'propagate': False,
        },
    },
}

EIGHTEEN_FORTY_EMAIL = os.environ.get("EIGHTEEN_FORTY_EMAIL", None)
EIGHTEEN_FORTY_PASSWORD = os.environ.get("EIGHTEEN_FORTY_PASSWORD", None)

INDEED_CLIENT_ID = os.environ.get("INDEED_CLIENT_ID", None)
INDEED_CLIENT_SECRET = os.environ.get("INDEED_CLIENT_SECRET", None)
INDEED_REDIRECT_URI = os.environ.get("INDEED_REDIRECT_URI", None)

BACKEND_URL = os.environ.get("BACKEND_URL", None)
INDEED_EMAIL=os.environ.get("INDEED_EMAIL", "contact@1840andco.com")

INDEED_APPLY_API_TOKEN=os.environ.get('INDEED_APPLY_API_TOKEN', '')

APPLE_CONFIG = {
    "APPLE_KEY_ID": os.environ["APPLE_KEY_ID"],
    "APPLE_TEAM_ID": os.environ["APPLE_TEAM_ID"],
    "APPLE_CLIENT_ID": os.environ["APPLE_CLIENT_ID"],
    "APPLE_PRIVATE_KEY": os.environ["APPLE_PRIVATE_KEY"],
    "APPLE_REDIRECT_URL": os.environ["APPLE_REDIRECT_URL"],
    "APPLE_SCOPE": ["name", "email"],
    "RESPONSE_HANDLER_CLASS": "users.services.AppleSignInResponseHandler",
}

AI_SERVICE_BASE_URL = os.environ["AI_SERVICE_BASE_URL"]