# Generated by Django 5.1 on 2024-11-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstage',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='phase_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
