# Generated by Django 5.1 on 2025-04-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_workflowstage_order_workflowstage_phase_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstage',
            name='phase',
            field=models.CharField(choices=[('new', 'new'), ('screening', 'screening'), ('interview', 'interview'), ('onboarding', 'onboarding'), ('hired', 'hired'), ('rejected', 'rejected')], max_length=100),
        ),
    ]
