# Generated by Django 5.1 on 2025-07-23 10:31

from django.db import migrations
from django.db.migrations import RunPython

from jobs.enums import PhaseType


def update_workflow_phase_order(apps, schema_editor):
    WorkFlowStage = apps.get_model("settings", "WorkFlowStage")
    for workflow in WorkFlowStage.objects.iterator():
        workflow.phase_order = PhaseType.get_index(workflow.phase)
        workflow.save()
    return


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_workflowstage_phase'),
    ]

    operations = [
        RunPython(update_workflow_phase_order)
    ]
