# Generated by Django 5.1 on 2025-07-24 13:57
import logging

from django.db import migrations
from django.db.migrations import RunPython


def update_all_stages_name_to_title_case(apps, schema_editor):
    WorkFlowStage = apps.get_model("settings", "WorkFlowStage")
    for workflow in WorkFlowStage.objects.iterator():
        workflow.name = str(workflow.name).title()
    logging.info("updated all workflow names to titlecase")



class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20250723_1131'),
    ]

    operations = [
        RunPython(update_all_stages_name_to_title_case)
    ]
