# Generated by Django 5.1 on 2025-08-01 09:38
import logging

from django.db import migrations



def update_defined_stages_to_title_case(apps, schema_editor):
    from jobs.enums import PhaseType
    WorkFlowStage = apps.get_model("settings", "WorkFlowStage")
    for workflow in WorkFlowStage.objects.filter(phase__in=[PhaseType.NEW.value, PhaseType.REJECTED.value, PhaseType.HIRED.value]).iterator():
        workflow.name = str(workflow.name).title()
    logging.info("updated defined workflow names to titlecase")


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_auto_20250724_1457'),
    ]

    operations = [
        migrations.RunPython(update_defined_stages_to_title_case),
    ]
