# Generated by Django 5.1 on 2025-08-05 17:13

from django.db import migrations

from jobs.enums import PhaseType


def update_workflow_phase_order(apps, schema_editor):
    WorkFlowStage = apps.get_model("settings", "WorkFlowStage")
    for workflow in WorkFlowStage.objects.iterator():
        workflow.phase_order = PhaseType.get_index(workflow.phase)
        workflow.save()
    return


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_auto_20250801_1038'),
    ]

    operations = [
        migrations.RunPython(update_workflow_phase_order),
    ]
