# Generated by Django 5.1 on 2025-11-17 12:34

from django.db import migrations



def correct_stage_phases(apps, schema_editor):
    from jobs.enums import PhaseType
    
    WorkFlowStage = apps.get_model("settings", "WorkFlowStage")
    
    WorkFlowStage.objects.filter(phase=PhaseType.HIRED.value).update(phase_order=PhaseType.values().index(PhaseType.HIRED.value))
    WorkFlowStage.objects.filter(phase=PhaseType.REJECTED.value).update(phase_order=PhaseType.values().index(PhaseType.REJECTED.value))


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_auto_20250805_1813'),
    ]

    operations = [
        migrations.RunPython(correct_stage_phases)
    ]
