# Generated by Django 5.1 on 2025-11-27 20:39

from django.db import migrations


def update_new_stages(apps, schema_editor):
    from jobs.enums import PhaseType
    
    Business = apps.get_model("accounts", "Business")
    WorkFlowStage = apps.get_model("settings", "WorkFlowStage")
    JobApplication = apps.get_model("jobs", "JobApplication")
    
    for business in Business.objects.only("id").iterator():
        new_stage = WorkFlowStage.objects.filter(created_by__business_id=business.id, phase=PhaseType.NEW.value).first()
        if new_stage:
            JobApplication.objects.filter(stage__phase__iexact=PhaseType.NEW.value,
                                          job_post__job__created_by__business_id=business.id).update(stage=new_stage)


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_auto_20251127_1854'),
    ]

    operations = [
        migrations.RunPython(update_new_stages)
    ]
