# Generated by Django 5.1 on 2025-12-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_auto_20251127_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='is_html',
            field=models.BooleanField(default=False),
        ),
    ]
