# Generated by Django 5.1 on 2024-11-13 17:47

import accounts.enums
import django.db.models.deletion
import notification.enums
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0020_businessuser_status_alter_businessuser_added_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicants_notification', models.BooleanField(default=True)),
                ('matching_notification', models.BooleanField(default=True)),
                ('sharing_notification', models.BooleanField(default=True)),
                ('performance_notification', models.BooleanField(default=True)),
                ('user_notification', models.BooleanField(default=True)),
                ('assignment_notification', models.BooleanField(default=True)),
                ('business_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.businessuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('action', models.CharField(choices=notification.enums.EntityActionType.choices, max_length=100, null=True)),
                ('entity', models.CharField(choices=notification.enums.EntityType.choices, max_length=100, null=True)),
                ('entity_uid', models.UUIDField(default=None, null=True)),
                ('entity_str', models.CharField(max_length=100, null=True)),
                ('recipient_groups', models.JSONField(default=list)),
                ('notification_type', models.CharField(choices=notification.enums.NotificationType.choices, max_length=100, null=True)),
                ('role', models.CharField(choices=accounts.enums.BusinessUserRoleType.choices, max_length=100, null=True)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.business')),
                ('recipient_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('viewers', models.ManyToManyField(blank=True, related_name='viewers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
