# Generated by Django 5.1 on 2024-11-15 15:31

import accounts.enums
import notification.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=notification.enums.EntityActionType.choices, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='entity',
            field=models.CharField(choices=notification.enums.EntityType.choices, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='entity_str',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=notification.enums.NotificationType.choices, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='role',
            field=models.CharField(choices=accounts.enums.BusinessUserRoleType.choices, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
