# Generated by Django 5.1 on 2025-07-01 14:56

from django.db import migrations



def update_notification_action(apps, schema_editor):
    Notification = apps.get_model('notification', 'Notification')
    from notification.enums import EntityActionType

    notifications = Notification.objects.exclude(action__in=(EntityActionType.values())).iterator()
    for notification in notifications:
        notification.action = EntityActionType.get(str(notification.action).split(".")[-1]) if notification.action else None
        notification.save()


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_title'),
    ]

    operations = [
        migrations.RunPython(update_notification_action),
    ]
