# Generated by Django 5.1 on 2025-08-08 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20250701_1556'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='all_recipients',
            field=models.ManyToManyField(blank=True, related_name='all_recipients', to=settings.AUTH_USER_MODEL),
        ),
    ]
