# Generated by Django 5.2.15 on 2026-06-15 22:42

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIApplicationInsight',
            fields=[
                ('application_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('talent_id', models.BigIntegerField()),
                ('jobpost_id', models.BigIntegerField(blank=True, null=True)),
                ('job_id', models.BigIntegerField(blank=True, null=True)),
                ('content_hash', models.TextField(blank=True, null=True)),
                ('model_id', models.TextField(blank=True, null=True)),
                ('prompt_version', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='pending')),
                ('summary', models.TextField(blank=True, null=True)),
                ('strengths', models.JSONField(blank=True, null=True)),
                ('weaknesses', models.JSONField(blank=True, null=True)),
                ('red_flags', models.JSONField(blank=True, null=True)),
                ('raw_output', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ai_application_insight',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AIMatchJobEmbedding',
            fields=[
                ('job_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('source_hash', models.TextField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ai_match_job_embedding',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AIMatchScore',
            fields=[
                ('talent_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('job_id', models.BigIntegerField()),
                ('raw_cosine', models.FloatField()),
                ('score', models.IntegerField()),
                ('top_percent', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ai_match_score',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AIMatchTalentEmbedding',
            fields=[
                ('talent_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('source_hash', models.TextField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ai_match_talent_embedding',
                'managed': False,
            },
        ),
    ]
