
LANGUAGES = ['Afrikaans', 'Akan', 'Albanian', 'Ambo', 'Amharic', 'Arabic', 'Armenian', 'Awak', 'Aymara', 'Azerbaijani',
             'Balinese', 'Balochi', 'Bamum', 'Bayang', 'Bemba', 'Bengali', 'Berber', 'Bete', 'Bilen', 'Bislama',
             'Bhojpuri', 'Bosnian', 'Boulou', 'Bulgarian', 'Burmese', 'Cape Verdean Creole (Kriolu)', 'Catalan',
             'Chichewa', 'Chinese', 'Comorian', 'Creole', 'Croatian', 'Danish', 'Dari (Persian)',
             'Dhivehi (Maldivian)', 'Duala', 'Dutch', 'Dzongkha', 'English', 'Estonian', 'Ewe', 'Fang', 'Fijian',
             'Filipino (Tagalog)', 'Finnish', 'French', 'Fula', 'Ga', 'Gbaya', 'Georgian', 'German', 'Greek', 'Guarani',
             'Haitian Creole (Kreyòl Ayisyen)', 'Hakka', 'Hausa', 'Hebrew', 'Hindi', 'Hokkien', 'Hungarian', 'Icelandic',
             'Igbo', 'Inari Sámi', 'Indonesian', 'IsiNdebele', 'IsiXhosa', 'IsiZulu', 'Italian', 'Jamaican Patois',
             'Japanese', 'Javanese', 'Kanuri', 'Kazakh', 'Khmer', 'Kinyarwanda', 'Kiribati', 'Krio', 'Kringa', 'Korean',
             'Kurdish', 'Lao', 'Latin', 'Latvian', 'Lithuanian', 'Luganda', 'Luxembourgish', 'Macedonian', 'Maithili',
             'Malagasy', 'Malay', 'Maldivian', 'Maltese', 'Mandarin Chinese', 'Mandinka', 'Maori', 'Marathi',
             'Marshallese', 'Mauritian Creole', 'Mongolian', 'Montenegrin', 'Mwani', 'Ndebele', 'Nepali', 'Ngumbete',
             'Northern Sámi', 'Norwegian', 'Oshiwambo', 'Otjiherero', 'Pashto', 'Pedi', 'Persian', 'Persian (Farsi)',
             'Polish', 'Portuguese', 'Punjabi', 'Quechua', 'Romanian', 'Romansh', 'Rundi', 'Russian', 'Saho', 'Sámi',
             'Samali', 'Samoan', 'Sepedi', 'Serbian', 'Sesotho', 'Sesotho sa Leboa', 'Setswana', 'Shangaan', 'Shona',
             'Shomp', 'Sindhi', 'Sinhala', 'Slovak', 'Slovene', 'Somali', 'Sotho', 'Spanish', 'Sranan', 'Sundanese',
             'Swahili', 'Swazi', 'Swedish', 'Tagalog', 'Tajik', 'Tamil', 'Telugu', 'Thai', 'Tigre', 'Tigrinya',
             'Tongan', 'Tsonga', 'Tswana', 'Turkish', 'Tshivenda', 'Twi', 'Udmurt', 'Ukrainian', 'Urdu', 'Uzbek',
             'Venda', 'Vietnamese', 'Wolof', 'Xhosa', 'Yoruba', 'Zulu']









CURRENCY = [
    {"name": "United States Dollar", "abbreviation": "USD", "symbol": "$"},
    {"name": "Euro", "abbreviation": "EUR", "symbol": "€"},
    {"name": "Japanese Yen", "abbreviation": "JPY", "symbol": "¥"},
    {"name": "British Pound Sterling", "abbreviation": "GBP", "symbol": "£"},
    {"name": "Australian Dollar", "abbreviation": "AUD", "symbol": "A$"},
    {"name": "Canadian Dollar", "abbreviation": "CAD", "symbol": "C$"},
    {"name": "Swiss Franc", "abbreviation": "CHF", "symbol": "CHF"},
    {"name": "Chinese Yuan Renminbi", "abbreviation": "CNY", "symbol": "¥"},
    {"name": "Swedish Krona", "abbreviation": "SEK", "symbol": "kr"},
    {"name": "New Zealand Dollar", "abbreviation": "NZD", "symbol": "NZ$"},
    {"name": "Mexican Peso", "abbreviation": "MXN", "symbol": "$"},
    {"name": "Singapore Dollar", "abbreviation": "SGD", "symbol": "S$"},
    {"name": "Hong Kong Dollar", "abbreviation": "HKD", "symbol": "HK$"},
    {"name": "Norwegian Krone", "abbreviation": "NOK", "symbol": "kr"},
    {"name": "South Korean Won", "abbreviation": "KRW", "symbol": "₩"},
    {"name": "Turkish Lira", "abbreviation": "TRY", "symbol": "₺"},
    {"name": "Indian Rupee", "abbreviation": "INR", "symbol": "₹"},
    {"name": "Brazilian Real", "abbreviation": "BRL", "symbol": "R$"},
    {"name": "South African Rand", "abbreviation": "ZAR", "symbol": "R"},
    {"name": "Russian Ruble", "abbreviation": "RUB", "symbol": "₽"},
    {"name": "Malaysian Ringgit", "abbreviation": "MYR", "symbol": "RM"},
    {"name": "Indonesian Rupiah", "abbreviation": "IDR", "symbol": "Rp"},
    {"name": "Philippine Peso", "abbreviation": "PHP", "symbol": "₱"},
    {"name": "Thai Baht", "abbreviation": "THB", "symbol": "฿"},
    {"name": "Israeli Shekel", "abbreviation": "ILS", "symbol": "₪"},
    {"name": "Chilean Peso", "abbreviation": "CLP", "symbol": "$"},
    {"name": "Saudi Riyal", "abbreviation": "SAR", "symbol": "ر.س"},
    {"name": "UAE Dirham", "abbreviation": "AED", "symbol": "د.إ"},
    {"name": "Argentine Peso", "abbreviation": "ARS", "symbol": "$"},
    {"name": "Colombian Peso", "abbreviation": "COP", "symbol": "$"},
    {"name": "Nigerian Naira", "abbreviation": "NGN", "symbol": "₦"},
    {"name": "Egyptian Pound", "abbreviation": "EGP", "symbol": "£"},
    {"name": "Kenyan Shilling", "abbreviation": "KES", "symbol": "KSh"},
    {"name": "Vietnamese Dong", "abbreviation": "VND", "symbol": "₫"},
    {"name": "Pakistani Rupee", "abbreviation": "PKR", "symbol": "₨"},
    {"name": "Bangladeshi Taka", "abbreviation": "BDT", "symbol": "৳"},
    {"name": "Peruvian Sol", "abbreviation": "PEN", "symbol": "S/."},
    {"name": "Venezuelan Bolivar", "abbreviation": "VES", "symbol": "Bs."},
    {"name": "Polish Zloty", "abbreviation": "PLN", "symbol": "zł"},
    {"name": "Hungarian Forint", "abbreviation": "HUF", "symbol": "Ft"},
    {"name": "Czech Koruna", "abbreviation": "CZK", "symbol": "Kč"},
    {"name": "Romanian Leu", "abbreviation": "RON", "symbol": "lei"},
    {"name": "Croatian Kuna", "abbreviation": "HRK", "symbol": "kn"},
    {"name": "Bulgarian Lev", "abbreviation": "BGN", "symbol": "лв"},
    {"name": "Danish Krone", "abbreviation": "DKK", "symbol": "kr"},
    {"name": "Icelandic Krona", "abbreviation": "ISK", "symbol": "kr"},
    {"name": "Ukrainian Hryvnia", "abbreviation": "UAH", "symbol": "₴"},
    {"name": "Kazakhstani Tenge", "abbreviation": "KZT", "symbol": "₸"},
    {"name": "Qatari Riyal", "abbreviation": "QAR", "symbol": "ر.ق"},
    {"name": "Omani Rial", "abbreviation": "OMR", "symbol": "ر.ع."},
    {"name": "Other", "abbreviation": "OTHER", "symbol": ""}
]