
LANGUAGES = ['Afrikaans', 'Akan', 'Albanian', 'Ambo', 'Amharic', 'Arabic', 'Armenian', 'Awak', 'Aymara', 'Azerbaijani',
             'Balinese', 'Balochi', 'Bamum', 'Bayang', 'Bemba', 'Bengali', 'Berber', 'Bete', 'Bilen', 'Bislama',
             'Bhojpuri', 'Bosnian', 'Boulou', 'Bulgarian', 'Burmese', 'Cape Verdean Creole (Kriolu)', 'Catalan',
             'Chichewa', 'Chinese', 'Comorian', 'Creole', 'Croatian', 'Danish', 'Dari (Persian)',
             'Dhivehi (Maldivian)', 'Duala', 'Dutch', 'Dzongkha', 'English', 'Estonian', 'Ewe', 'Fang', 'Fijian',
             'Filipino (Tagalog)', 'Finnish', 'French', 'Fula', 'Ga', 'Gbaya', 'Georgian', 'German', 'Greek', 'Guarani',
             'Haitian Creole (Kreyòl Ayisyen)', 'Hakka', 'Hausa', 'Hebrew', 'Hindi', 'Hokkien', 'Hungarian', 'Icelandic',
             'Igbo', 'Inari Sámi', 'Indonesian', 'IsiNdebele', 'IsiXhosa', 'IsiZulu', 'Italian', 'Jamaican Patois',
             'Japanese', 'Javanese', 'Kanuri', 'Kazakh', 'Khmer', 'Kinyarwanda', 'Kiribati', 'Krio', 'Kringa', 'Korean',
             'Kurdish', 'Lao', 'Latin', 'Latvian', 'Lithuanian', 'Luganda', 'Luxembourgish', 'Macedonian', 'Maithili',
             'Malagasy', 'Malay', 'Maldivian', 'Maltese', 'Mandarin Chinese', 'Mandinka', 'Maori', 'Marathi',
             'Marshallese', 'Mauritian Creole', 'Mongolian', 'Montenegrin', 'Mwani', 'Ndebele', 'Nepali', 'Ngumbete',
             'Northern Sámi', 'Norwegian', 'Oshiwambo', 'Otjiherero', 'Pashto', 'Pedi', 'Persian', 'Persian (Farsi)',
             'Polish', 'Portuguese', 'Punjabi', 'Quechua', 'Romanian', 'Romansh', 'Rundi', 'Russian', 'Saho', 'Sámi',
             'Samali', 'Samoan', 'Sepedi', 'Serbian', 'Sesotho', 'Sesotho sa Leboa', 'Setswana', 'Shangaan', 'Shona',
             'Shomp', 'Sindhi', 'Sinhala', 'Slovak', 'Slovene', 'Somali', 'Sotho', 'Spanish', 'Sranan', 'Sundanese',
             'Swahili', 'Swazi', 'Swedish', 'Tagalog', 'Tajik', 'Tamil', 'Telugu', 'Thai', 'Tigre', 'Tigrinya',
             'Tongan', 'Tsonga', 'Tswana', 'Turkish', 'Tshivenda', 'Twi', 'Udmurt', 'Ukrainian', 'Urdu', 'Uzbek',
             'Venda', 'Vietnamese', 'Wolof', 'Xhosa', 'Yoruba', 'Zulu']






import json

# Full ISO 4217 active currency dataset (127 entries)
CURRENCY = [
    {"abbreviation": "AED", "name": "United Arab Emirates Dirham", "symbol": "د.إ"},
    {"abbreviation": "AFN", "name": "Afghan Afghani", "symbol": "؋"},
    {"abbreviation": "ALL", "name": "Albanian Lek", "symbol": "Lek"},
    {"abbreviation": "AMD", "name": "Armenian Dram", "symbol": "֏"},
    {"abbreviation": "ANG", "name": "Netherlands Antillean Guilder", "symbol": "ƒ"},
    {"abbreviation": "AOA", "name": "Angolan Kwanza", "symbol": "Kz"},
    {"abbreviation": "ARS", "name": "Argentine Peso", "symbol": "$"},
    {"abbreviation": "AUD", "name": "Australian Dollar", "symbol": "A$"},
    {"abbreviation": "AWG", "name": "Aruban Florin", "symbol": "ƒ"},
    {"abbreviation": "AZN", "name": "Azerbaijani Manat", "symbol": "₼"},
    {"abbreviation": "BAM", "name": "Bosnia-Herzegovina Convertible Mark", "symbol": "KM"},
    {"abbreviation": "BBD", "name": "Barbados Dollar", "symbol": "Bds$"},
    {"abbreviation": "BDT", "name": "Bangladeshi Taka", "symbol": "৳"},
    {"abbreviation": "BGN", "name": "Bulgarian Lev", "symbol": "лв"},
    {"abbreviation": "BHD", "name": "Bahraini Dinar", "symbol": ".د.ب"},
    {"abbreviation": "BIF", "name": "Burundian Franc", "symbol": "FBu"},
    {"abbreviation": "BMD", "name": "Bermudian Dollar", "symbol": "BD$"},
    {"abbreviation": "BND", "name": "Brunei Dollar", "symbol": "B$"},
    {"abbreviation": "BOB", "name": "Boliviano", "symbol": "Bs."},
    {"abbreviation": "BRL", "name": "Brazilian Real", "symbol": "R$"},
    {"abbreviation": "BSD", "name": "Bahamian Dollar", "symbol": "B$"},
    {"abbreviation": "BTN", "name": "Bhutanese Ngultrum", "symbol": "Nu."},
    {"abbreviation": "BWP", "name": "Botswana Pula", "symbol": "P"},
    {"abbreviation": "BYN", "name": "Belarusian Ruble", "symbol": "Br"},
    {"abbreviation": "BZD", "name": "Belize Dollar", "symbol": "BZ$"},
    {"abbreviation": "CAD", "name": "Canadian Dollar", "symbol": "C$"},
    {"abbreviation": "CDF", "name": "Congolese Franc", "symbol": "FC"},
    {"abbreviation": "CHF", "name": "Swiss Franc", "symbol": "CHF"},
    {"abbreviation": "CLP", "name": "Chilean Peso", "symbol": "$"},
    {"abbreviation": "CNY", "name": "Chinese Yuan", "symbol": "¥"},
    {"abbreviation": "COP", "name": "Colombian Peso", "symbol": "$"},
    {"abbreviation": "CRC", "name": "Costa Rican Colón", "symbol": "₡"},
    {"abbreviation": "CUP", "name": "Cuban Peso", "symbol": "$"},
    {"abbreviation": "CVE", "name": "Cape Verdean Escudo", "symbol": "Esc"},
    {"abbreviation": "CZK", "name": "Czech Koruna", "symbol": "Kč"},
    {"abbreviation": "DJF", "name": "Djiboutian Franc", "symbol": "Fdj"},
    {"abbreviation": "DKK", "name": "Danish Krone", "symbol": "kr"},
    {"abbreviation": "DOP", "name": "Dominican Peso", "symbol": "RD$"},
    {"abbreviation": "DZD", "name": "Algerian Dinar", "symbol": "دج"},
    {"abbreviation": "EGP", "name": "Egyptian Pound", "symbol": "E£"},
    {"abbreviation": "ERN", "name": "Eritrean Nakfa", "symbol": "Nfk"},
    {"abbreviation": "ETB", "name": "Ethiopian Birr", "symbol": "Br"},
    {"abbreviation": "EUR", "name": "Euro", "symbol": "€"},
    {"abbreviation": "FJD", "name": "Fijian Dollar", "symbol": "FJ$"},
    {"abbreviation": "FKP", "name": "Falkland Islands Pound", "symbol": "£"},
    {"abbreviation": "GBP", "name": "Pound Sterling", "symbol": "£"},
    {"abbreviation": "GEL", "name": "Georgian Lari", "symbol": "₾"},
    {"abbreviation": "GHS", "name": "Ghanaian Cedi", "symbol": "₵"},
    {"abbreviation": "GIP", "name": "Gibraltar Pound", "symbol": "£"},
    {"abbreviation": "GMD", "name": "Gambian Dalasi", "symbol": "D"},
    {"abbreviation": "GNF", "name": "Guinean Franc", "symbol": "FG"},
    {"abbreviation": "GTQ", "name": "Guatemalan Quetzal", "symbol": "Q"},
    {"abbreviation": "GYD", "name": "Guyanese Dollar", "symbol": "GY$"},
    {"abbreviation": "HKD", "name": "Hong Kong Dollar", "symbol": "HK$"},
    {"abbreviation": "HNL", "name": "Honduran Lempira", "symbol": "L"},
    {"abbreviation": "HRK", "name": "Croatian Kuna", "symbol": "kn"},
    {"abbreviation": "HTG", "name": "Haitian Gourde", "symbol": "G"},
    {"abbreviation": "HUF", "name": "Hungarian Forint", "symbol": "Ft"},
    {"abbreviation": "IDR", "name": "Indonesian Rupiah", "symbol": "Rp"},
    {"abbreviation": "ILS", "name": "Israeli New Shekel", "symbol": "₪"},
    {"abbreviation": "INR", "name": "Indian Rupee", "symbol": "₹"},
    {"abbreviation": "IQD", "name": "Iraqi Dinar", "symbol": "ع.د"},
    {"abbreviation": "IRR", "name": "Iranian Rial", "symbol": "﷼"},
    {"abbreviation": "ISK", "name": "Icelandic Króna", "symbol": "kr"},
    {"abbreviation": "JMD", "name": "Jamaican Dollar", "symbol": "J$"},
    {"abbreviation": "JOD", "name": "Jordanian Dinar", "symbol": "JD"},
    {"abbreviation": "JPY", "name": "Japanese Yen", "symbol": "¥"},
    {"abbreviation": "KES", "name": "Kenyan Shilling", "symbol": "KSh"},
    {"abbreviation": "KGS", "name": "Kyrgyzstani Som", "symbol": "с"},
    {"abbreviation": "KHR", "name": "Cambodian Riel", "symbol": "៛"},
    {"abbreviation": "KMF", "name": "Comorian Franc", "symbol": "CF"},
    {"abbreviation": "KRW", "name": "South Korean Won", "symbol": "₩"},
    {"abbreviation": "KWD", "name": "Kuwaiti Dinar", "symbol": "KD"},
    {"abbreviation": "KYD", "name": "Cayman Islands Dollar", "symbol": "CI$"},
    {"abbreviation": "KZT", "name": "Kazakhstani Tenge", "symbol": "₸"},
    {"abbreviation": "LAK", "name": "Lao Kip", "symbol": "₭"},
    {"abbreviation": "LBP", "name": "Lebanese Pound", "symbol": "ل.ل"},
    {"abbreviation": "LKR", "name": "Sri Lankan Rupee", "symbol": "Rs"},
    {"abbreviation": "LRD", "name": "Liberian Dollar", "symbol": "L$"},
    {"abbreviation": "LSL", "name": "Lesotho Loti", "symbol": "L"},
    {"abbreviation": "LYD", "name": "Libyan Dinar", "symbol": "LD"},
    {"abbreviation": "MAD", "name": "Moroccan Dirham", "symbol": "DH"},
    {"abbreviation": "MDL", "name": "Moldovan Leu", "symbol": "L"},
    {"abbreviation": "MGA", "name": "Malagasy Ariary", "symbol": "Ar"},
    {"abbreviation": "MKD", "name": "Macedonian Denar", "symbol": "ден"},
    {"abbreviation": "MMK", "name": "Myanmar Kyat", "symbol": "Ks"},
    {"abbreviation": "MNT", "name": "Mongolian Tögrög", "symbol": "₮"},
    {"abbreviation": "MOP", "name": "Macanese Pataca", "symbol": "MOP$"},
    {"abbreviation": "MRU", "name": "Mauritanian Ouguiya", "symbol": "UM"},
    {"abbreviation": "MUR", "name": "Mauritian Rupee", "symbol": "₨"},
    {"abbreviation": "MVR", "name": "Maldivian Rufiyaa", "symbol": "Rf"},
    {"abbreviation": "MWK", "name": "Malawian Kwacha", "symbol": "MK"},
    {"abbreviation": "MXN", "name": "Mexican Peso", "symbol": "Mex$"},
    {"abbreviation": "MYR", "name": "Malaysian Ringgit", "symbol": "RM"},
    {"abbreviation": "MZN", "name": "Mozambican Metical", "symbol": "MT"},
    {"abbreviation": "NAD", "name": "Namibian Dollar", "symbol": "N$"},
    {"abbreviation": "NGN", "name": "Nigerian Naira", "symbol": "₦"},
    {"abbreviation": "NIO", "name": "Nicaraguan Córdoba", "symbol": "C$"},
    {"abbreviation": "NOK", "name": "Norwegian Krone", "symbol": "kr"},
    {"abbreviation": "NPR", "name": "Nepalese Rupee", "symbol": "₨"},
    {"abbreviation": "NZD", "name": "New Zealand Dollar", "symbol": "NZ$"},
    {"abbreviation": "OMR", "name": "Omani Rial", "symbol": "﷼"},
    {"abbreviation": "PAB", "name": "Panamanian Balboa", "symbol": "B/."},
    {"abbreviation": "PEN", "name": "Peruvian Sol", "symbol": "S/."},
    {"abbreviation": "PGK", "name": "Papua New Guinean Kina", "symbol": "K"},
    {"abbreviation": "PHP", "name": "Philippine Peso", "symbol": "₱"},
    {"abbreviation": "PKR", "name": "Pakistani Rupee", "symbol": "₨"},
    {"abbreviation": "PLN", "name": "Polish Zloty", "symbol": "zł"},
    {"abbreviation": "PYG", "name": "Paraguayan Guarani", "symbol": "₲"},
    {"abbreviation": "QAR", "name": "Qatari Riyal", "symbol": "﷼"},
    {"abbreviation": "RON", "name": "Romanian Leu", "symbol": "lei"},
    {"abbreviation": "RSD", "name": "Serbian Dinar", "symbol": "дин."},
    {"abbreviation": "RUB", "name": "Russian Ruble", "symbol": "₽"},
    {"abbreviation": "RWF", "name": "Rwandan Franc", "symbol": "FRw"},
    {"abbreviation": "SAR", "name": "Saudi Riyal", "symbol": "﷼"},
    {"abbreviation": "SBD", "name": "Solomon Islands Dollar", "symbol": "SI$"},
    {"abbreviation": "SCR", "name": "Seychellois Rupee", "symbol": "SRe"},
    {"abbreviation": "SDG", "name": "Sudanese Pound", "symbol": "ج.س."},
    {"abbreviation": "SEK", "name": "Swedish Krona", "symbol": "kr"},
    {"abbreviation": "SGD", "name": "Singapore Dollar", "symbol": "S$"},
    {"abbreviation": "SHP", "name": "Saint Helena Pound", "symbol": "£"},
    {"abbreviation": "SLL", "name": "Sierra Leonean Leone", "symbol": "Le"},
    {"abbreviation": "SOS", "name": "Somali Shilling", "symbol": "Sh.So."},
    {"abbreviation": "SRD", "name": "Surinamese Dollar", "symbol": "SRD$"},
    {"abbreviation": "SSP", "name": "South Sudanese Pound", "symbol": "£"},
    {"abbreviation": "STN", "name": "São Tomé and Príncipe Dobra", "symbol": "Db"},
    {"abbreviation": "SYP", "name": "Syrian Pound", "symbol": "£S"},
    {"abbreviation": "SZL", "name": "Eswatini Lilangeni", "symbol": "L"},
    {"abbreviation": "THB", "name": "Thai Baht", "symbol": "฿"},
    {"abbreviation": "TJS", "name": "Tajikistani Somoni", "symbol": "SM"},
    {"abbreviation": "TMT", "name": "Turkmenistani Manat", "symbol": "T"},
    {"abbreviation": "TND", "name": "Tunisian Dinar", "symbol": "DT"},
    {"abbreviation": "TOP", "name": "Tongan Paʻanga", "symbol": "T$"},
    {"abbreviation": "TRY", "name": "Turkish Lira", "symbol": "₺"},
    {"abbreviation": "TTD", "name": "Trinidad and Tobago Dollar", "symbol": "TT$"},
    {"abbreviation": "TWD", "name": "New Taiwan Dollar", "symbol": "NT$"},
    {"abbreviation": "TZS", "name": "Tanzanian Shilling", "symbol": "TSh"},
    {"abbreviation": "UAH", "name": "Ukrainian Hryvnia", "symbol": "₴"},
    {"abbreviation": "UGX", "name": "Ugandan Shilling", "symbol": "USh"},
    {"abbreviation": "USD", "name": "United States Dollar", "symbol": "$"},
    {"abbreviation": "UYU", "name": "Uruguayan Peso", "symbol": "$U"},
    {"abbreviation": "UZS", "name": "Uzbekistan Som", "symbol": "лв"},
    {"abbreviation": "VES", "name": "Venezuelan Bolívar", "symbol": "Bs.S"},
    {"abbreviation": "VND", "name": "Vietnamese Dong", "symbol": "₫"},
    {"abbreviation": "VUV", "name": "Vanuatu Vatu", "symbol": "VT"},
    {"abbreviation": "WST", "name": "Samoan Tala", "symbol": "WS$"},
    {"abbreviation": "XAF", "name": "CFA Franc BEAC", "symbol": "FCFA"},
    {"abbreviation": "XCD", "name": "East Caribbean Dollar", "symbol": "EC$"},
    {"abbreviation": "XOF", "name": "CFA Franc BCEAO", "symbol": "CFA"},
    {"abbreviation": "XPF", "name": "CFP Franc", "symbol": "₣"},
    {"abbreviation": "YER", "name": "Yemeni Rial", "symbol": "﷼"},
    {"abbreviation": "ZAR", "name": "South African Rand", "symbol": "R"},
    {"abbreviation": "ZMW", "name": "Zambian Kwacha", "symbol": "ZK"},
    {"abbreviation": "ZWL", "name": "Zimbabwean Dollar", "symbol": "Z$"}
]
