EDUCATION_LEVEL = [
    {"industry": "General Industries", "education": "Associates"},
    {"industry": "General Industries", "education": "Bachelors"},
    {"industry": "General Industries", "education": "Masters"},
    {"industry": "General Industries", "education": "Doctorate"},
    {"industry": "General Industries", "education": "Certificate"},
    {"industry": "General Industries", "education": "Diploma"},
    {"industry": "General Industries", "education": "Graduate Certificate"},
    {"industry": "General Industries", "education": "Trade/Technical Certificate"},
    {"industry": "General Industries", "education": "Postgraduate Certificate"},
    {"industry": "General Industries", "education": "Higher National Diploma (HND)"},
    {"industry": "General Industries", "education": "Advanced Diploma"},
    {"industry": "General Industries", "education": "Professional Degree"},
    {"industry": "General Industries", "education": "Non-Degree Programs"},
    {"industry": "Healthcare", "education": "Residency/Internship"},
    {"industry": "Healthcare", "education": "Fellowship"},
    {"industry": "Healthcare", "education": "Advanced Practice Registered Nurse (APRN) Certification"},
    {"industry": "Healthcare", "education": "Board Certification"},
    {"industry": "Healthcare", "education": "Licensure"},
    {"industry": "Healthcare", "education": "Professional Certifications"},
    {"industry": "Healthcare", "education": "Continuing Education Units (CEUs)"}
]
DEPARTMENT_AND_SKILLS = [
    {
        "Industry": "General Industries",
        "Department": "Information Technology (IT)",
        "Roles": "Chief Information Officer (CIO)\nChief Technology Officer (CTO)\nIT Manager/Director\nSystem Administrator/Network Administrator\nDatabase Administrator (DBA)\nIT Security Specialist/Information Security Analyst\nSoftware Developer/Programmer\nBusiness Analyst\nHelp Desk/Support Technician\nIT Project Manager\nProduct Manager\nQuality Assurance (QA) Analyst/Tester\nData Analyst\nCloud Architect/Administrator\nAI/ML Engineer\nNetwork Engineer\nIT Support Specialist\nIT Auditor\nDesktop Support Technician\nIT Trainer\nTelecommunications Specialist"
                 "\nSystems Analyst\nWeb Developer\nDevOps Engineer\nCybersecurity Analyst\nEnterprise Architect\nIT Consultant\nMobile App Developer\nIT Operations Manager\nData Scientist\nIT Compliance Officer\nDigital Transformation Manager\nUser Interface (UI) Designer\nUser Experience (UX) Designer\nIT Procurement Specialist\nIT Risk Analyst\nIT Governance Specialist\nIT Change Manager\nIT Financial Analyst\nIT Vendor Manager\nIT Communications SpecialistSoftware Architect\nTechnical Architect\nSolution Architect\nSystems Architect\nApplication Architect\n"
                 "Engineering Manager\nSoftware Development Manager\nSenior Engineering Manager\nDirector of Engineering\nPlatform Architect\nCloud Architect\nInfrastructure Architect\nEnterprise Architect\nSenior Software Architect\nPrincipal Architect\nLead Architect\nChief Architect\nMobile Architect\niOS Architect\nAndroid Architect\nData Architect\nSecurity Architect\nAI Architect\nIntegration Architect\nAPI Architect\nBlockchain Architect\nSoftware Developer Engineer\nHead of Engineering"
                 "\nTechnology Director\nDigital Transformation Lead\nPlatform Director\nSolutions Director\nHead of Architecture\nHead of Platform\nHead of Mobile\nSoftware development Engineer Lead\nLead Software Engineer\nEngineer I\nEngineer II\nEngineer III\nFrontend Engineer\nBackend Engineer",
        "Tools/Platforms": "Jira, ServiceNow, Microsoft Azure, Group Policy, AWS Management Console, Virtualization Platforms, Google Cloud Console, Docker, Kubernetes, Jenkins, Git, Wireshark, Nagios, SolarWinds, Splunk, Chef, Puppet, Visual Studio Code, Eclipse, PyCharm, IntelliJ IDEA, GitHub, GitLab, Slack, Microsoft Teams, Asana, Crucible, Microsoft Windows Server, GitHub Pull Requests, Travis CI, CircleCI, AWS, Azure, GCP, Prometheus, Grafana, React, Angular, Vuejs, MySQL Workbench, MongoDB Compass, Nmap, Microsoft 365, Windows, Visual Studio, NET Framework, NET Core, Azure DevOps, Active Directory, SQL Server, Dynamics 365, Xbox, Azure IoT, Azure Ai, Domain Name System (DNS)",
        "Common Methodologies/Frameworks": "Agile, Scrum, ITIL, SAFe (Scaled Agile Framework), Lean Six Sigma, TOGAF (The Open Group Architecture Framework), COBIT (Control Objectives for Information and Related Technologies), PMBOK (Project Management Body of Knowledge), Kanban, Waterfall, RUP (Rational Unified Process), PRINCE2 (Projects IN Controlled Environments), Lean IT, JavaScript, Python, Java, TypeScript, C#, PHP, HTML, CSS, SQL, Ruby, Swift, Kotlin, Go, C++, Shell scripting (Bash), MATLAB, R, Scala, Groovy, Perl, PowerShell, Objective-C, Apex, Visualforce",
        "General Skills": "IT Infrastructure Management, Cybersecurity, Cloud Computing, Database Management, Software Development, IT Project Management, Data Science, Machine Learning, DevOps, Network Security, System Administration, IT Governance, Agile Methodology, Big Data Analytics, Virtualization, Blockchain, Mobile App Development, Web Development, Artificial Intelligence, Robotics, Scripting and Automation, Network Infrastructure, Server Knowledge",
        "Soft Skills": "Problem Solving, Analytical Skills, Attention to Detail, Adaptability, Collaboration, Continuous Learning, Technical Proficiency, Troubleshooting, Creativity, Communication"
    },
    {
        "Industry": "General Industries",
        "Department": "Human Resources (HR)",
        "Roles": "HR Manager\nHR Director\nRecruitment Specialist/Recruiter\nHuman Resources Generalist\nHR Coordinator/Administrator\nEmployee Relations Specialist\nTraining and Development Specialist\nCompensation and Benefits Specialist\nHR Business Partner\nHRIS (Human Resource Information System) Specialist\nLabor Relations Specialist\nOrganizational Development Specialist\nDiversity, Equity, and Inclusion (DEI) Specialist\nCompensation Analyst\nBenefits Administrator\nPerformance Management Specialist\nWellness Coordinator\nHR Compliance Specialist\nTalent Acquisition Manager\nEmployee Engagement Specialist\nChange Management Specialist",
        "Tools/Platforms": "Workday, ADP, BambooHR, Greenhouse, Namely, Paycom, Zenefits, UltiPro, Kronos, PeopleSoft, Bullhorn, Gusto, JazzHR, SmartRecruiters, Lever, Indeedcom, Linkedin Recruiter",
        "Common Methodologies/Frameworks": "HR Analytics, HRIS (Human Resource Information System), Employee Life Cycle Models, Workforce Planning Models, Succession Planning Models, Diversity and Inclusion Frameworks, Employee Wellness Models, Recruitment and Selection Models, HR Compliance Frameworks",
        "General Skills": "Legal and Compliance, Employee Benefits, Compensation Management, Performance Management, Employee Training and Development, Talent Management, Employee Engagement, Diversity Equity and Inclusion (DEI), Employee Relations, Change Management, Strategic HR Planning, Health and Safety, Labor Relations, Technology Adoption",
        "Soft Skills": "Empathy, Conflict Resolution, Interpersonal Skills, Confidentiality, Recruitment Skills, Emotional Intelligence, Time Management, Organizational Skills"
    },
    {
        "Industry": "General Industries",
        "Department": "Finance and Accounting",
        "Roles": "Chief Financial Officer (CFO)\nController\nFinancial Analyst\nAccountant\nAccounts Payable Specialist\nAccounts Receivable Specialist\nPayroll Specialist\nInternal Auditor\nTax Accountant\nBudget Analyst\nTreasury Analyst\nFinance Manager\nCredit Analyst\nCost Accountant\nBookkeeper\nFinancial Planning and Analysis (FP&A) Analyst\nBilling Specialist\nRisk Analyst\nInvestment Analyst",
        "Tools/Platforms": "QuickBooks, SAP, Oracle Financials, Xero, FreshBooks, NetSuite, Wave, Zoho Books, Sage Intacct, Bench, Tally, Expensify, Concur, Stripe, PayPal",
        "Common Methodologies/Frameworks": "GAAP, IFRS, Double-Entry Accounting, Cash Flow Analysis, Cost Accounting, Activity-Based Costing (ABC), Budgeting and Forecasting Models, Financial Modeling, Financial Statement Analysis, Internal Controls, Taxation Frameworks, Auditing Standards, Sarbanes-Oxley Compliance (SOX), Financial Risk Management, Economic Value Added (EVA)",
        "General Skills": "Financial Planning and Analysis, Budgeting, Forecasting, Financial Reporting, Taxation, Audit and Compliance, Risk Management, Treasury Management, Management Accounting, Cash Flow Management, Regulatory Compliance, Financial Systems, Payroll Processing, Expense Management, Procurement, Vendor Management",
        "Soft Skills": "Integrity, Numerical Competence, Decision Making, Accuracy"
    },
    {
        "Industry": "General Industries",
        "Department": "Sales and Marketing",
        "Roles": "Sales Representative\nAccount Executive\nSales Manager\nMarketing Coordinator\nMarketing Specialist\nDigital Marketing Manager\nContent Marketing Manager\nSocial Media Manager\nBrand Manager\nMarketing Analyst\nMarket Research Analyst\nSales Operations Analyst\nPublic Relations Specialist\nEvent Coordinator\nInside Sales Representative\nCRM Administrator\nEmail Marketing Specialist\nSEO Specialist\nAdvertising Manager",
        "Tools/Platforms": "Salesforce, HubSpot, Mailchimp, Marketo, Pardot, Google Analytics, SEMrush, Ahrefs, Moz, Buffer, Canva, Hootsuite, Sprout Social, Adobe Creative Cloud, LinkedIn Sales Navigator",
        "Common Methodologies/Frameworks": "Inbound Marketing, Outbound Marketing, Content Marketing, Social Media Marketing, Email Marketing, Search Engine Optimization (SEO), Search Engine Marketing (SEM), Pay-Per-Click (PPC), Market Research, SWOT Analysis, Sales Funnel Management, Lead Generation, Branding Strategies, Competitive Analysis, Public Relations (PR) Strategies, Campaign Management, Influencer Marketing",
        "General Skills": "Sales Strategy, Customer Relationship Management (CRM), Sales Enablement, Sales Forecasting, Account Management, Negotiation, Product Knowledge, Brand Management, Digital Marketing, Marketing Analytics, Advertising, Public Relations, Event Management, Customer Segmentation",
        "Soft Skills": "Persuasion, Relationship Building, Negotiation Skills, Presentation Skills, Active Listening, Teamwork"
    },
    {
        "Industry": "General Industries",
        "Department": "Operations (Physical Products)",
        "Roles": "Operations Manager\nSupply Chain Manager\nLogistics Manager\nWarehouse Manager\nProduction Manager\nQuality Assurance Manager\nDemand Planner\nProcurement Manager\nOperations Analyst\nInventory Manager\nProduct Development Manager\nDistribution Center Manager\nE-commerce Operations Manager\nManufacturing Engineer\nOperations Compliance Manager",
        "Tools/Platforms": "Trello, Mondaycom, Wrike, Smartsheet, Airtable, Basecamp, ClickUp, TeamViewer, Notion, Evernote, Confluence",
        "Common Methodologies/Frameworks": "Lean Manufacturing, Six Sigma, 5S, Total Quality Management (TQM), Theory of Constraints (TOC), Just-in-Time (JIT), Kaizen, Value Stream Mapping, Manufacturing Resource Planning (MRP II), Statistical Process Control (SPC), Root Cause Analysis, Process Mapping, Failure Mode and Effects Analysis (FMEA), Design for Manufacturability (DFM)",
        "General Skills": "Supply Chain Management, Logistics Planning, Inventory Optimization, Distribution, Strategic Sourcing, Contract Negotiation, International Trade, Customs Compliance, Risk Mitigation, Manufacturing Processes, Inventory Management, Automation, Process Optimization, Industrial Engineering, CAD/CAM, Machine Operation, Safety Protocols, Materials Handling, Equipment Maintenance, Project Management, ISO Standards, Process Improvement, Facilities Management",
        "Soft Skills": "Organization, Strategic Thinking, Critical Thinking, Leadership"
    },
    {
        "Industry": "General Industries",
        "Department": "Operations (Digital Products)",
        "Roles": "Digital Operations Manager\nProduct Manager (Digital)\nAgile Project Manager\nScrum Master\nRelease Manager\nData Operations Analyst\nCloud Operations Engineer\nDigital Content Manager\nUser Experience (UX) Manager\nCustomer Support Manager (Digital)\nDigital Marketing Operations Manager\nCybersecurity Operations Manager\nDigital IT Compliance Analyst",
        "Tools/Platforms": "Git/GitHub, AWS (Amazon Web Services), Google Cloud Platform (GCP), New Relic, Zendesk",
        "Common Methodologies/Frameworks": "Continuous Integration/Continuous Deployment (CI/CD), Lean Software Development, Feature-Driven Development (FDD), Extreme Programming (XP), Test-Driven Development (TDD), Behavior-Driven Development (BDD), Lean Startup, Design Thinking",
        "General Skills": "Strategic Planning, Resource Allocation, Quality Assurance, Performance Monitoring, Data Analysis",
        "Soft Skills": "Team Management, Problem-Solving, Decision-Making"
    },
    {
        "Industry": "General Industries",
        "Department": "Customer Service/Support",
        "Roles": "Customer Service Representative\nCustomer Support Specialist\nCall Center Supervisor\nCustomer Success Manager\nTechnical Support Engineer\nHelp Desk Analyst\nLive Chat Support Agent\nCustomer Experience Manager\nSupport Team Lead\nClient Services Coordinator\nEscalation Specialist\nService Desk Manager\nContact Center Manager\nCustomer Service Trainer\nSocial Media Customer Support Specialist",
        "Tools/Platforms": "Freshdesk, Intercom, Help Scout, Salesforce Service Cloud, LiveChat, Zoho Desk, Kayako, HappyFox, Front, Jitbit, Deskcom, TeamSupport, Freshservice, Gorgias",
        "Common Methodologies/Frameworks": "HDIT, CRM, KCS (Knowledge-Centered Service), Agile Service Management, Lean Service Management, ISO 18295, COBIT, Customer Effort Score (CES), Net Promoter Score (NPS), Quality Assurance (QA) Frameworks, Call Center Reporting and Analytics, VoC (Voice of the Customer) Programs, COPC (Customer Operations Performance Center) Standards, Service Level Agreements (SLAs)",
        "General Skills": "Technical Support, Call Center Operations, Ticketing Systems, Customer Feedback Analysis, Customer Satisfaction, Service Level Agreements (SLA), Escalation Handling, Cross-functional Collaboration, Training and Development, Quality Assurance in Customer Service, Service Recovery",
        "Soft Skills": "Patience, Flexibility, Positive Attitude, Agile Mindset, Team Collaboration, Innovation"
    },
    {
        "Industry": "General Industries",
        "Department": "Research and Development (R&D)",
        "Roles": "Research Scientist\nR&D Manager\nProduct Development Engineer\nResearch Analyst\nInnovation Specialist\nLaboratory Technician\nBiomedical Engineer\nDesign Engineer\nResearch and Development Coordinator\nClinical Research Associate\nR&D Project Manager\nQuality Assurance Analyst (R&D)\nResearch and Development Director",
        "Tools/Platforms": "LabVIEW, Autodesk, ANSYS, SolidWorks, CATIA, Altium Designer, PTC Creo, COMSOL Multiphysics, Mendeley, EndNote, RefWorks, OriginPro, NVivo, SciFinder, Tableau, Power BI, SAS, Apache Hadoop, Apache Spark, KNIME Analytics Platform, Alteryx, JMP, QlikView, Qlik Sense, IBM SPSS Statistics, D3js, Looker",
        "Common Methodologies/Frameworks": "Agile Modeling, Joint Application Development (JAD), Design Sprint, Waterfall Model, Stage-Gate Model, Spiral Model, RAD (Rapid Application Development), Prototype Model, Incremental Model, V-Model, Big Design Up Front (BDUF)",
        "General Skills": "Experimental Design, Statistical Analysis, Prototyping, Intellectual Property Management, Research Methodologies, Scientific Writing, Data Interpretation, Literature Review, Hypothesis Testing, Laboratory Techniques, Patent Analysis, Quality Control",
        "Soft Skills": "Analytical Thinking, Research Skills, Scientific Method"
    },
    {
        "Industry": "General Industries",
        "Department": "Production/Manufacturing",
        "Roles": "Production Supervisor\nManufacturing Engineer\nProduction Operator\nQuality Control Inspector\nAssembly Line Worker\nProcess Engineer\nPlant Manager\nCNC Machinist\nIndustrial Engineer\nMaintenance Technician\nProduction Planner\nOperations Technician\nPackaging Technician\nWelder\nFabrication Manager",
        "Tools/Platforms": "SAP ERP, Oracle ERP, MES (Manufacturing Execution System), Plex Systems, Infor CloudSuite Industrial, Epicor ERP, QAD, Fishbowl Manufacturing, IQMS, JobBOSS, Odoo Manufacturing, E2 Manufacturing System, Prodsmart, 3D EXPERIENCE by Dassault Systèmes, FactoryLogix MES",
        "Common Methodologies/Frameworks": "Just-In-Time (JIT), Computer-Aided Design (CAD), Computer-Aided Manufacturing (CAM), Manufacturing Execution System (MES), Computer Numerical Control (CNC), Materials Requirement Planning (MRP), Process Failure Mode and Effects Analysis (PFMEA), Rapid Prototyping, Continuous Improvement, Robotics and Automation",
        "General Skills": "Production Planning, Safety Compliance, Manufacturing Documentation, CNC Machining, Assembly Line Operations, Welding Techniques, Robotics Programming, Automation Technologies, Supply Chain Optimization, Kaizen Principles, 5S Methodology, CAD/CAM Software, Manufacturing Execution Systems (MES), Facility Layout Planning, Fixture Design, Injection Molding, Plastics Processing, Metal Stamping, ISO Standards Compliance",
        "Soft Skills": "Precision, Technical Skills"
    },
    {
        "Industry": "General Industries",
        "Department": "Supply Chain and Logistics",
        "Roles": "Logistics Coordinator\nProcurement Specialist\nInventory Analyst\nFreight Coordinator\nSupply Chain Analyst\nCustoms Compliance Specialist\nTransportation Planner\nReverse Logistics Coordinator\nImport/Export Coordinator\nOrder Fulfillment Specialist",
        "Tools/Platforms": "SAP SCM (Supply Chain Management), Oracle SCM Cloud, Blue Yonder (formerly JDA Software), Kinaxis RapidResponse, Manhattan Associates, Logility, E2open, Elemica, MercuryGate, Llamasoft, Slyncio, FourKites, Transporeon, project44, SAP Integrated Business Planning (IBP)",
        "Common Methodologies/Frameworks": "Lean Supply Chain, Agile Supply Chain, Demand Planning, Capacity Planning, Warehouse Management System (WMS), Transportation Management System (TMS), Supplier Relationship Management (SRM), Radio-Frequency Identification (RFID), Global Trade Management (GTM), Order Fulfillment, Network Design and Optimization, Reverse Logistics, Cross-Docking, Freight Consolidation, Last-Mile Delivery Optimization, Route Planning and Optimization",
        "General Skills": "Logistics Coordination, Transportation Management, Supplier Relationship Management, Warehouse Management, Distribution Planning, International Trade Regulations, Route Optimization, Cost Reduction Strategies, Vendor Negotiation",
        "Soft Skills": ""
    },
    {
        "Industry": "General Industries",
        "Department": "Legal",
        "Roles": "Lawyer\nLegal Assistant\nParalegal\nLegal Secretary\nCorporate Counsel\nLegal Consultant\nContract Specialist\nIntellectual Property Attorney\nImmigration Lawyer\nEnvironmental Attorney\nTax Attorney\nFamily Law Attorney\nCourt Clerk\nLegal Researcher",
        "Tools/Platforms": "Clio, LegalZoom, Westlaw, LexisNexis, MyCase, CaseMap, Thomson Reuters Practical Law, Bloomberg Law, ContractSafe, eDiscovery, CaseFleet, LawPay, Zola Suite, DocuSign, Adobe Sign, HelloSign, PandaDoc, SignEasy, SignNow, OneSpan Sign, RightSignature, SignRequest, KeepSolid Sign, Zoho Sign, Signable, CocoSign, Formstack Sign, Sertifi",
        "Common Methodologies/Frameworks": "Legal Research Methodologies, Case Management Systems, Document Management Systems, Contract Management Frameworks, E-Discovery Frameworks, Legal Project Management Frameworks, Compliance Management Frameworks, Intellectual Property Management Frameworks, Legal Billing Frameworks, Legal Analytics Frameworks, Legal Process Outsourcing (LPO) Frameworks, Litigation Support Frameworks, Regulatory Compliance Management Frameworks",
        "General Skills": "Legal Research, Contract Drafting, Legal Writing, Litigation Support, Case Management, Compliance Management, Regulatory Affairs, Due Diligence, Legal Documentation, Corporate Governance, Legal Analysis, Arbitration and Mediation, Legal Project Management",
        "Soft Skills": "Legal Knowledge, Ethics"
    },
    {
        "Industry": "General Industries",
        "Department": "Quality Assurance (QA) or Quality Control (QC)",
        "Roles": "Quality Assurance (QA) Manager\nQuality Control (QC) Inspector\nQuality Assurance (QA) Analyst\nQuality Control (QC) Technician\nQuality Assurance (QA) Engineer\nQuality Control (QC) Supervisor\nQuality Assurance (QA) Tester\nQuality Control (QC) Analyst\nQuality Assurance (QA) Auditor\nQuality Control (QC) Engineer\nQuality Assurance (QA) Specialist\nQuality Control (QC) Coordinator\nQuality Assurance (QA) Consultant\nQuality Control (QC) Lab Technician\nQuality Assurance (QA) Trainer",
        "Tools/Platforms": "TestRail, Zephyr, qTest, Tricentis Tosca, Selenium, Appium, Postman, LoadRunner, TestComplete, Katalon Studio, Ranorex, Miro, Bitbucket",
        "Common Methodologies/Frameworks": "Call Center Quality Assurance Frameworks, Voice of the Customer (VoC) Programs, Customer Satisfaction (CSAT), First Call Resolution (FCR), Average Handling Time (AHT), Quality Monitoring, Speech Analytics, Customer Journey Mapping, Customer Feedback Loops, Agent Performance Metrics, Lean, Agile Testing, Acceptance Test-Driven Development (ATDD), Continuous Testing, Shift-Left Testing, Exploratory Testing, Risk-Based Testing, Model-Based Testing, Usability Testing, Performance Testing, Security Testing, Compliance Testing, Regression Testing",
        "General Skills": "Quality Inspection, Auditing, Testing Methodologies, Calibration, Documentation Control, Non-Destructive Testing (NDT)",
        "Soft Skills": ""
    },
    {
        "Industry": "General Industries",
        "Department": "Administration",
        "Roles": "Virtual Assistant\nAdministrative Assistant\nExecutive Assistant\nOffice Manager\nAdministrative Coordinator\nReceptionist\nSecretary\nOffice Administrator\nData Entry Clerk\nPersonal Assistant\nFront Desk Coordinator\nClerical Assistant\nAdministrative Specialist\nOffice Clerk\nRecords Coordinator\nAdministrative Support Manager",
        "Tools/Platforms": "Microsoft Office Suite, Google Workspace, Zoom, Adobe Acrobat, Dropbox, Microsoft SharePoint, Calendly",
        "Common Methodologies/Frameworks": "ISO 9001, Lean Administration, ISO 27001, Agile Administration, Business Process Reengineering (BPR), Governance Frameworks, Regulatory Compliance Frameworks",
        "General Skills": "Office Management, Calendar Management, Record Keeping, Filing Systems, Data Entry, Event Planning, Travel Coordination, Report Generation, Meeting Coordination, Budget Management, Office Equipment Maintenance, Facilities Coordination, Procurement and Purchasing",
        "Soft Skills": "Multitasking, Initiative"
    },
    {
        "Industry": "General Industries",
        "Department": "Facilities Management",
        "Roles": "Facilities Manager\nFacilities Coordinator\nFacility Maintenance Technician\nBuilding Manager\nProperty Manager\nFacilities Engineer\nMaintenance Supervisor\nFacility Planner\nEnvironmental Health and Safety (EHS) Coordinator\nGroundskeeper\nSpace Planner\nHVAC Technician\nFacilities Operations Manager\nCustodial Supervisor\nEnergy Manager",
        "Tools/Platforms": "IBM TRIRIGA, Archibus, ServiceChannel, UpKeep, FMX, Hippo CMMS, Maintenance Connection, Fiix, AssetWorks, Planon, AkitaBox, OfficeSpace Software, iOFFICE, OfficeMaps, Robin",
        "Common Methodologies/Frameworks": "ISO 41001, CMMS (Computerized Maintenance Management System), IWMS (Integrated Workplace Management System), Lean Management, Agile Facilities Management, Building Information Modeling (BIM), Environmental Management Systems (EMS), Risk Management Frameworks, Energy Management Systems (EnMS), Sustainability Reporting Standards",
        "General Skills": "Building Maintenance, Space Planning, Health and Safety Compliance, Emergency Preparedness, Sustainability Initiatives, Budgeting for Facilities, Energy Management, Project Management for Facility Upgrades, HVAC Systems Knowledge, Security Systems Management, Workplace Ergonomics, Waste Management, Lease Management, Renovation Planning",
        "Soft Skills": "Planning"
    },
    {
        "Industry": "General Industries",
        "Department": "Public Relations (PR) and Communications",
        "Roles": "Public Relations Manager\nCommunications Specialist\nPR Coordinator\nMedia Relations Manager\nCorporate Communications Manager\nPublicist\nContent Writer\nPress Secretary\nCommunications Director\nCopywriter\nCrisis Communications Specialist\nInternal Communications Manager\nNews Editor",
        "Tools/Platforms": "Meltwater, Cision, Mention, TrendKite (now Cision), LinkedIn, Facebook, Instagram, TikTok, Twitter",
        "Common Methodologies/Frameworks": "Crisis Communication Plans, Media Relations Strategies, Social Media Management, Stakeholder Analysis, Reputation Management, Integrated Marketing Communication (IMC), Thought Leadership, Public Affairs",
        "General Skills": "Media Relations, Crisis Communication, Brand Development, Content Creation, Press Release Writing, Public Speaking, Social Media Strategy, Stakeholder Engagement, Speechwriting, Community Outreach, Corporate Communication, Editing and Proofreading",
        "Soft Skills": "Writing Skills, Networking"
    },
    {
        "Industry": "General Industries",
        "Department": "Business Development",
        "Roles": "Business Development Manager\nBusiness Development Executive\nRelationship Manager\nPartnership Manager\nAccount Manager\nSales Consultant\nLead Generation Specialist\nBusiness Development Coordinator\nStrategic Partnerships Manager\nSales Development Representative (SDR)\nCorporate Development Manager",
        "Tools/Platforms": "ZoomInfo, HubSpot CRM, Pipedrive, Zoho CRM, Gongio, Outreach, Yesware, Crystal, Leadfeeder",
        "Common Methodologies/Frameworks": "PESTLE Analysis, Business Model Canvas, Porter's Five Forces, Ansoff Matrix, BANT Criteria, Blue Ocean Strategy, Competitive Intelligence, Value Proposition Canvas, McKinsey 7S Framework, SMART Criteria, Market Entry Strategies, Customer Acquisition Cost (CAC), Customer Lifetime Value (CLV), Sales Funnel Analysis, Lead Scoring",
        "General Skills": "Partnership Development, Contract Management, Financial Analysis, Customer Acquisition, Proposal Writing, Market Entry Strategy",
        "Soft Skills": "Sales Skills"
    },
    {
        "Industry": "General Industries",
        "Department": "Compliance",
        "Roles": "Compliance Officer\nCompliance Manager\nRegulatory Affairs Specialist\nCompliance Analyst\nRisk and Compliance Manager\nAML (Anti-Money Laundering) Analyst\nCompliance Consultant\nEthics and Compliance Officer\nPrivacy Officer\nFinancial Compliance Analyst\nCorporate Compliance Specialist\nQuality Assurance and Compliance Manager\nLegal and Compliance Coordinator\nCompliance Investigator",
        "Tools/Platforms": "Compliancy Group, LogicGate, ZenGRC, Reciprocity ZenQMS, MetricStream, ComplianceBridge, Lockpath, Qualys, NAVEX Global, HighBond by Galvanize, VComply, ComplyAssistant, 360factors Predict360, Resolver, Compli",
        "Common Methodologies/Frameworks": "SO 19600:2014, ISO 31000:2018, GDPR, SOX, PCI DSS, HIPAA, NERC CIP, NIST Cybersecurity Framework, FISMA, ISO 37001, Whistleblower Protection Programs, Compliance Auditing and Monitoring",
        "General Skills": "Risk Assessment, Policy Development, Data Privacy Compliance, Anti-Money Laundering (AML) Compliance, Ethical Decision-Making, Investigation Skills, Contract Compliance, Compliance Reporting",
        "Soft Skills": "Ethical Decision Making"
    },
    {
        "Industry": "General Industries",
        "Department": "Risk Management",
        "Roles": "Risk Manager\nRisk Analyst\nCredit Risk Analyst\nOperational Risk Manager\nEnterprise Risk Manager\nRisk Consultant\nRisk Assurance Specialist\nFinancial Risk Analyst\nQuantitative Risk Analyst\nInsurance Risk Manager\nMarket Risk Analyst\nCyber Risk Analyst\nRisk Modeling Analyst\nFraud Risk Manager",
        "Tools/Platforms": "RiskWatch, Riskon, IBM OpenPages, Sphera, Riskonnect, LogicManager, Predict360 by 360factors, RiskCloud by LogicGate, NAVEX Global RiskRate",
        "Common Methodologies/Frameworks": "COSO ERM, FAIR, PMI Risk Management Framework, FERMA Risk Management Standard, NIST Risk Management Framework, RIMS Risk Maturity Model, M_o_R, ISO 27005:2018, AS/NZS 4360:2004, CIA Triad, Bowtie Methodology, Fault Tree Analysis, FMEA, Scenario Analysis, Monte Carlo Simulation",
        "General Skills": "Quantitative Analysis, Risk Mitigation Strategies, Crisis Management, Business Continuity Planning, Insurance Analysis, Contract Risk Management, Fraud Detection, Decision-Making under Uncertainty, Enterprise Risk Management (ERM), Incident Response Planning, Market Risk Analysis",
        "Soft Skills": ""
    },
    {
        "Industry": "Healthcare",
        "Department": "Emergency Department (ED)",
        "Roles": "Emergency Physician\nEmergency Nurse\nParamedics/EMTs\nED Technician\nED Manager",
        "Tools/Platforms": "Electronic Health Records (EHR), Clinical Decision Support Systems (CDSS), Medical Imaging Systems, Emergency Department Information Systems (EDIS), Telemedicine Platforms, Patient Monitoring Systems, Medication Administration Systems, Clinical Communication Tools, Charting Software, Mobile Data Terminals (MDTs), Electronic Patient Care Reporting (ePCR), Medical Equipment, Navigation Systems, Radio Communication Systems, Clinical Equipment, Medical Equipment Management Systems, Inventory Management Systems, Healthcare Management Software, Scheduling and Staffing Tools, Performance Metrics Dashboards, Communication and Collaboration Tools",
        "Common Methodologies/Frameworks": "Advanced Trauma Life Support (ATLS), Basic Life Support (BLS), Advanced Cardiac Life Support (ACLS), Clinical Pathways and Protocols, Emergency Nursing Core Competencies, Triage Systems (eg, Emergency Severity Index - ESI), Trauma Nursing Core Course (TNCC), Patient Safety Protocols, Pre-Hospital Care Protocols, Advanced Life Support (ALS), National EMS Education Standards, Standard Operating Procedures (SOPs), Emergency Care Protocols, Infection Control Procedures, Quality Improvement Frameworks, Patient Flow Optimization Models, Operational Efficiency Strategies",
        "General Skills": "Clinical Assessment, Emergency Response, Patient Care, Communication Skills, Documentation, Medical Knowledge, Stress Management, Patient Advocacy, Patient Education",
        "Soft Skills": ""
    },
    {
        "Industry": "Healthcare",
        "Department": "Internal Medicine",
        "Roles": "Internist\nMedical Resident\nMedical Assistant\nClinical Coordinator",
        "Tools/Platforms": "Practice Management Software, Patient Portals, Medical Charting Software, Scheduling Software, Laboratory Information Systems (LIS), Prescription Management Systems",
        "Common Methodologies/Frameworks": "Clinical Pathways, Evidence-Based Medicine, Patient-Centered Care, Integrated Care Models, Chronic Disease Management Protocols, Preventive Care Guidelines, Care Coordination Models",
        "General Skills": "Diagnosis and Treatment Planning, Coordination of Care",
        "Soft Skills": ""
    },
    {
        "Industry": "Healthcare",
        "Department": "Surgery",
        "Roles": "Surgeon\nSurgical Nurse\nSurgical Technician\nAnesthesiologist",
        "Tools/Platforms": "Surgical Instrumentation, Anesthesia Delivery Systems, Operating Room Management Software, Surgical Navigation Systems, Sterilization Equipment, Surgical Safety Checklists, Electronic Anesthesia Records",
        "Common Methodologies/Frameworks": "Surgical Protocols, Evidence-Based Surgery Guidelines, Patient Safety Standards, Surgical Checklists (eg, WHO Surgical Safety Checklist), Perioperative Care Models, Pain Management Protocols, Enhanced Recovery After Surgery (ERAS)",
        "General Skills": "Surgical Techniques, Intraoperative Monitoring, Anesthesia Management",
        "Soft Skills": ""
    },
    {
        "Industry": "Healthcare",
        "Department": "Pediatrics",
        "Roles": "Pediatrician\nPediatric Nurse\nPediatric Resident\nChild Life Specialist",
        "Tools/Platforms": "Pediatric Medical Equipment, Growth and Development Tracking Tools, Pediatric Imaging Systems, Pediatric Care Management Software, Immunization Registries, Pediatric Charting Software, Pediatric Medication Management Systems",
        "Common Methodologies/Frameworks": "Pediatric Clinical Guidelines, Growth and Development Milestones, Evidence-Based Pediatric Care, Pediatric Assessment Protocols, Child-Friendly Communication Techniques, Family-Centered Care Models, Preventive Pediatric Care Guidelines, Pediatric Pain Management Protocols",
        "General Skills": "Pediatric Care, Patient and Family Education, Growth and Development Monitoring, Emotional Support",
        "Soft Skills": "Compassion"
    },
    {
        "Industry": "Healthcare",
        "Department": "Obstetrics and Gynecology (OB/GYN)",
        "Roles": "OB/GYN Physician\nLabor and Delivery Nurse\nGynecologic Surgeon\nPerinatologist",
        "Tools/Platforms": "Obstetric and Gynecologic Imaging Systems, Labor and Delivery Management Software, Fetal Monitoring Systems, Ultrasound Machines, Electronic Medical Records (EMR), Maternal Health Tracking Tools",
        "Common Methodologies/Frameworks": "Obstetric and Gynecologic Clinical Guidelines, Evidence-Based Practice Protocols, Labor and Delivery Protocols, Prenatal and Postnatal Care Models, Maternal-Fetal Medicine Guidelines, Gynecologic Surgical Protocols, Risk Assessment Models",
        "General Skills": "Obstetric and Gynecologic Care, Labor and Delivery Management",
        "Soft Skills": ""
    },
    {
        "Industry": "Healthcare",
        "Department": "Cardiology",
        "Roles": "Cardiologist\nCardiac Nurse\nElectrophysiologist\nCardiac Technician",
        "Tools/Platforms": "Cardiac Imaging Systems, Electrocardiogram (ECG) Machines, Cardiac Monitoring Systems, Cardiac Catheterization Equipment, Stress Testing Systems, Pacemakers and Defibrillators, Cardiology Information Systems, Holter Monitors",
        "Common Methodologies/Frameworks": "Cardiac Care Guidelines, Evidence-Based Cardiovascular Medicine, Heart Failure Management Protocols, Electrophysiology Protocols, Clinical Pathways for Cardiovascular Diseases, Preventive Cardiology Guidelines",
        "General Skills": "Cardiac Assessment, Electrophysiological Analysis, Monitoring and Interpretation",
        "Soft Skills": ""
    },
    {
        "Industry": "Healthcare",
        "Department": "Oncology",
        "Roles": "Oncologist\nOncology Nurse\nRadiation Therapist\nOncology Pharmacist",
        "Tools/Platforms": "Oncology Information Systems, Chemotherapy Management Software, Radiation Therapy Planning Software, Infusion Pumps, Chemotherapy Administration Systems, Patient Treatment Planning Systems, Drug Interaction Software, Pharmacy Information Systems",
        "Common Methodologies/Frameworks": "Evidence-Based Oncology Guidelines, Cancer Care Pathways, Tumor Board Protocols, Radiation Therapy Protocols, Evidence-Based Radiation Oncology Guidelines, Chemotherapy Administration Guidelines, Symptom Management Protocols, Drug Interaction Management, Safety and Quality Assurance Protocols",
        "General Skills": "Cancer Management, Symptom Management, Chemotherapy Administration, Treatment Planning, Medication Management",
        "Soft Skills": ""
    },
    {
        "Industry": "Healthcare",
        "Department": "Radiology",
        "Roles": "Radiologist\nRadiologic Technologist\nUltrasound Technician\nRadiology Nurse",
        "Tools/Platforms": "Picture Archiving and Communication Systems (PACS), Radiology Information Systems (RIS), CT Scanners, MRI Machines, Radiology Workstations, Image Analysis Software",
        "Common Methodologies/Frameworks": "Imaging Protocols, Evidence-Based Imaging Guidelines, Quality Assurance Protocols, Radiation Safety Standards, Image Interpretation Frameworks, Diagnostic Accuracy Protocols",
        "General Skills": "Imaging Techniques, Diagnostic Imaging Interpretation, Equipment Operation, Image Analysis",
        "Soft Skills": ""
    },
    {
        "Industry": "Healthcare",
        "Department": "Pathology",
        "Roles": "Pathologist\nMedical Laboratory Technician\nCytotechnologist\nHistotechnologist",
        "Tools/Platforms": "Microscopes, Imaging Systems, Pathology Information Systems, Slide Scanners, Automated Stainers, Tissue Processors, Cytology Preparation Equipment, Data Analysis Software",
        "Common Methodologies/Frameworks": "Pathology Protocols, Evidence-Based Diagnostic Guidelines, Quality Assurance Procedures, Diagnostic Accuracy Frameworks, Laboratory Safety Standards, Cytology and Histology Techniques, Accreditation Standards",
        "General Skills": "Diagnostic Interpretation, Tissue and Cell Analysis",
        "Soft Skills": ""
    },
    {
        "Industry": "Healthcare",
        "Department": "Pharmacy",
        "Roles": "Pharmacist\nPharmacy Technician\nClinical Pharmacist\nPharmacy Manager",
        "Tools/Platforms": "Pharmacy Management Systems, Automated Dispensing Systems, Inventory Management Software",
        "Common Methodologies/Frameworks": "Evidence-Based Pharmacotherapy Guidelines, Medication Safety Protocols, Pharmaceutical Care Models, Clinical Pharmacy Guidelines, Inventory Management Standards",
        "General Skills": "Drug Interaction Analysis, Patient Counseling, Inventory Control, Prescription Processing, Coordination with Healthcare Team",
        "Soft Skills": ""
    },
    {
        "Industry": "Healthcare",
        "Department": "Nursing",
        "Roles": "Registered Nurse (RN)\nNurse Practitioner (NP)\nLicensed Practical Nurse (LPN)\nNurse Manager",
        "Tools/Platforms": "Nursing Documentation Software, Telehealth Platforms, Healthcare Management Systems, Clinical Workflow Tools",
        "Common Methodologies/Frameworks": "Evidence-Based Practice Guidelines, Nursing Care Plans, Preventive Health Guidelines, Risk Management Procedures",
        "General Skills": "",
        "Soft Skills": ""
    },
    {
        "Industry": "Healthcare",
        "Department": "Physical Therapy",
        "Roles": "Physical Therapist (PT)\nPhysical Therapy Assistant (PTA)\nRehabilitation Aide",
        "Tools/Platforms": "Rehabilitation Management Software, Patient Assessment Tools, Exercise Equipment, Manual Therapy Tools, Gait Analysis Systems, Treatment Planning Software, Modalities Equipment (eg, TENS units)",
        "Common Methodologies/Frameworks": "Rehabilitation Protocols, Patient-Centered Care Models, Functional Independence Measure (FIM), Outcome Measurement Tools, Therapeutic Exercise Guidelines",
        "General Skills": "Patient Assessment, Exercise Therapy, Manual Therapy Techniques, Rehabilitation Techniques",
        "Soft Skills": "Motivation"
    },
    {
        "Industry": "Healthcare",
        "Department": "Psychiatry",
        "Roles": "Psychiatrist\nClinical Psychologist\nMental Health Nurse\nPsychiatric Social Worker\nMental Health Therapist",
        "Tools/Platforms": "Psychological Assessment Tools, Mental Health Management Software, Cognitive Behavioral Therapy (CBT) Tools, Diagnostic and Statistical Manual of Mental Disorders (DSM), Psychotherapy Documentation Software",
        "Common Methodologies/Frameworks": "Cognitive Behavioral Therapy (CBT) Protocols, Psychotherapy Techniques, Mental Health Assessment Frameworks, Crisis Intervention Models",
        "General Skills": "Psychotherapy, Crisis Intervention, Therapeutic Techniques",
        "Soft Skills": ""
    },
    {
        "Industry": "Healthcare",
        "Department": "Public Health",
        "Roles": "Public Health Administrator\nEpidemiologist\nHealth Educator\nCommunity Health Worker",
        "Tools/Platforms": "Public Health Management Software, Epidemiology Data Analysis Tools, Health Information Systems, Community Health Platforms, Survey and Data Collection Tools, Health Promotion Software, Geographic Information Systems (GIS), Statistical Analysis Software",
        "Common Methodologies/Frameworks": "Evidence-Based Public Health Guidelines, Epidemiological Methods, Community Health Assessment Frameworks, Health Promotion Models, Risk Assessment Frameworks, Preventive Health Protocols",
        "General Skills": "Community Health Assessment, Health Education, Program Development, Epidemiological Research, Public Health Policy, Patient and Community Engagement, Health Promotion",
        "Soft Skills": ""
    },
    {
        "Industry": "Healthcare",
        "Department": "Administration",
        "Roles": "Healthcare Administrator\nHealthcare Office Manager\nMedical Secretary\nHealthcare Executive Director",
        "Tools/Platforms": "Practice Management Systems, Financial Management Software, Human Resources Systems, Compliance and Regulatory Tools, Communication Platforms",
        "Common Methodologies/Frameworks": "Healthcare Management Protocols, Financial Management Standards, Human Resources Policies, Compliance Guidelines, Operational Efficiency Models",
        "General Skills": "Financial Management, Patient and Staff Coordination, Scheduling",
        "Soft Skills": ""
    }
]

university_list = [
    "University of Andorra",
    "Abu Dhabi University",
    "Ajman University of Science & Technology",
    "Alain University of Science and Technology",
    "Al Ghurair University",
    "Alhosn University",
    "Al Khawarizmi International College",
    "American College Of Dubai",
    "American University in Dubai",
    "American University in the Emirates",
    "American University of Sharjah",
    "British University in Dubai",
    "Dubai Medical College for Girls",
    "Dubai Pharmacy College",
    "Etisalat University College",
    "Gulf Medical University",
    "Hamdan Bin Mohammed e-University",
    "Higher Colleges of Technology",
    "Ittihad University",
    "Jumeira University",
    "Khalifa University",
    "Khalifa University of Science, Technology and Research",
    "Masdar University Of Science And Technology",
    "New York University, Abu Dhabi",
    "Paris-Sorbonne University Abu Dhabi",
    "Rak Medical & Health Sciences University",
    "Rochester Institute of Technology, Dubai",
    "Skyline University College, Sharjah",
    "Synergy University, Dubai Campus",
    "The Emirates Academy of Hotel Managment",
    "The Petroleum Institute",
    "United Arab Emirates University",
    "University Of Dubai",
    "University of Jazeera",
    "University of Sharjah",
    "University of Wollongong - Dubai Campus",
    "Zayed University",
    "Afghan University",
    "Al-Birony University",
    "American University of Afghanistan",
    "Aria Institute of Higher Education",
    "Badakhshan University",
    "Baghlan University",
    "Bakhtar University",
    "Balkh University",
    "Bamiyan University",
    "Bost University",
    "Dawat University",
    "Dunya Institute of Higher Education",
    "Faryab Higher Education Institute",
    "Ghazni University",
    "Herat University",
    "Ibn Sina University",
    "Jawzjan University",
    "Kaboora Institute of Higher Education",
    "Kabul Education University",
    "Kabul Health Sciences Institute",
    "Kabul Medical University",
    "Kabul University",
    "Kandahar University",
    "Kardan University",
    "Karwan Institute of Higher Education",
    "Kateb Institute of Higher Education",
    "Khana-e-Noor Institute of Higher Education",
    "Khurasan University",
    "Maryam Institute of Higher Education",
    "Nangarhar University",
    "National Military Academy of Afghanistan",
    "Paktia University",
    "Pamir University",
    "Parwan University",
    "Polytechnical University of Kabul",
    "Rana Institute of Higher Education",
    "Sadat Institute of Higher Education",
    "Salam University",
    "Shaikh Zayed University",
    "Taj Institute of Higher Education",
    "Takhar University",
    "American University of Antigua",
    "University of Health Sciences Antigua",
    "Academy of Arts",
    "Academy of Sports and Physical Training",
    "Agricultural University of Tirane",
    "American University of Tirana",
    "Beder University",
    "Epoka University",
    "Polytechnic University of Tirane",
    "University of Elbasan \"Aleksander Xhuvani\"",
    "University of Gjirokstra \"Eqerem Cabej\"",
    "University of Korca \"Fan Noli\"",
    "University of New York Tirana",
    "University of Shkodra \"Luigj Gurakuqi\"",
    "University of Tirana",
    "University of Vlora \"Ismail Qemali\"",
    "University â€œPavaresiaâ€ Vlore",
    "American University of Armenia",
    "Armenian State Agrarian University",
    "Armenian State University of Economics",
    "Eurasia International University",
    "European Regional Educational Academy of Armenia",
    "French University in Armenia (UFAR)",
    "Mehrabyan Medical Institute and Medical College",
    "Russian-Armenian (Slavonic) State University",
    "State Engineering University of Armenia",
    "Yerevan Haibusak University",
    "Yerevan State Medical University",
    "Yerevan State University",
    "American University of the Caribbean, Sint Maarten",
    "International University School of Medicine (IUSOM)",
    "St.James's School of Medicine, Bonaire",
    "University of Sint Eustatius School of Medicine",
    "University of the Netherlands Antilles, Curacao",
    "Universidade CatÃ³lica de Angola",
    "Universidade Gregorio Semedo",
    "Universidade Independente de Angola",
    "Universidade LusÃ­ada de Angola",
    "Universidade Metodista de Angola",
    "Universidade Metropolitana de Angola",
    "Universidade Tecnica de Angola",
    "Univesidade Agostinho Neto",
    "Instituto de EnseÃ±anza Superior del EjÃ©rcito",
    "Instituto Nacional de EducaciÃ³n FÃ­sica \"General Manuel Belgrano\"",
    "Instituto TecnolÃ³gico de Buenos Aires",
    "Instituto Universitario AeronÃ¡utico",
    "Instituto Universitario CEMA",
    "Instituto Universitario de Ciencias de la Salud FundaciÃ³n H.A. BarcelÃ³",
    "Instituto Universitario de Estudios Navales y MarÃ­timos",
    "Instituto Universitario de la Policia Federal",
    "Instituto Universitario Nacional del Arte",
    "Universidad Abierta Interamericana",
    "Universidad Adventista del Plata",
    "Universidad Argentina de la Empresa",
    "Universidad Argentina \"John F. Kennedy\"",
    "Universidad Atlantida Argentina",
    "Universidad Austral Buenos Aires",
    "Universidad AutÃ³noma de Entre RÃ­os",
    "Universidad Blas Pascal",
    "Universidad CAECE, Buenos Aires",
    "Universidad CatÃ³lica Argentina Santa Maria de los Buenos Aires",
    "Universidad CatÃ³lica de CÃ³rdoba",
    "Universidad CatÃ³lica de Cuyo",
    "Universidad CatÃ³lica de La Plata",
    "Universidad CatÃ³lica de Salta",
    "Universidad CatÃ³lica de Santa FÃ©",
    "Universidad CatÃ³lica de Santiago del Estero",
    "Universidad Champagnat",
    "Universidad de Belgrano",
    "Universidad de Bologna - RepresentaciÃ³n en Buenos Aires",
    "Universidad de Buenos Aires",
    "Universidad de Ciencias Empresariales y Sociales",
    "Universidad de ConcepciÃ³n del Uruguay",
    "Universidad de Congreso",
    "Universidad de Flores - Buenos Aires",
    "Universidad del Aconcagua",
    "Universidad de la Cuenca del Plata",
    "Universidad de la Fraternidad de Agrupaciones Santo Tomas de Aquino (FASTA)",
    "Universidad de la Marina Mercante",
    "Universidad del Centro Educativo Latinoamericano Rosario",
    "Universidad del Cine - Buenos Aires",
    "Universidad del Museo Social Argentino",
    "Universidad del Norte \"Santo TomÃ¡s de Aquino\"",
    "Universidad del Salvador",
    "Universidad de Mendoza",
    "Universidad de MorÃ³n",
    "Universidad de Palermo",
    "Universidad de San Andres",
    "Universidad Empresarial Siglio 21",
    "Universidad ISALUD",
    "Universidad \"Juan AgustÃ­n Maza\"",
    "Universidad MaimÃ³nides",
    "Universidad Nacional de Catamarca",
    "Universidad Nacional de CÃ³rdoba",
    "Universidad Nacional de Cuyo",
    "Universidad Nacional de Entre RÃ­os",
    "Universidad Nacional de Formosa",
    "Universidad Nacional de General San MartÃ­n",
    "Universidad Nacional de General Sarmiento",
    "Universidad Nacional de Jujuy",
    "Universidad Nacional de La Matanza",
    "Universidad Nacional de Lanus",
    "Universidad Nacional de La Pampa",
    "Universidad Nacional de la Patagonia Austral",
    "Universidad Nacional de la Patagonia \"San Juan Bosco\"",
    "Universidad Nacional de La Plata",
    "Universidad Nacional de La Rioja",
    "Universidad Nacional del Centro de la Provincia de Buenos Aires",
    "Universidad Nacional del Comahue",
    "Universidad Nacional del Littoral",
    "Universidad Nacional del Nordeste",
    "Universidad Nacional del Noroeste de la Provincia de Buenos Aires",
    "Universidad Nacional de Lomas de Zamora",
    "Universidad Nacional del Sur",
    "Universidad Nacional de LujÃ¡n",
    "Universidad Nacional de Mar del Plata",
    "Universidad Nacional de Misiones",
    "Universidad Nacional de Quilmes",
    "Universidad Nacional de RÃ­o Cuarto",
    "Universidad Nacional de Rosario",
    "Universidad Nacional de Salta",
    "Universidad Nacional de San Juan",
    "Universidad Nacional de San Luis",
    "Universidad Nacional de Santiago del Estero",
    "Universidad Nacional de Tres de Febrero",
    "Universidad Nacional de TucumÃ¡n",
    "Universidad Nacional de Villa MarÃ­a",
    "Universidad Notarial Argentina",
    "Universidad TecnolÃ³gica Nacional",
    "Universidad Torcuato di Tella",
    "Akademie der bildenden KÃ¼nste Wien",
    "Donau-UniversitÃ¤t Krems",
    "Fachhochschule Burgenland",
    "Fachhochschule fÃ¼r Bank- und Finanzwirtschaft",
    "Fachhochschule JOANNEUM",
    "Fachhochschule KÃ¤rnten",
    "Fachhochschule Krems",
    "Fachhochschule Kufstein (Tirol)",
    "Fachhochschule Salzburg",
    "Fachhochschule St. PÃ¶lten",
    "Fachhochschule Vorarlberg",
    "Fachhochschule Wiener Neustadt",
    "FachhochschulstudiengÃ¤nge der Wiener Wirtschaft",
    "FachhochschulstudiengÃ¤nge Hagenberg",
    "FachhochschulstudiengÃ¤nge Krems IMC",
    "FachhochschulstudiengÃ¤nge Steyr",
    "FachhochschulstudiengÃ¤nge Wels",
    "Institute of Science and Technology",
    "Katholisch-Theologische PrivatuniversitÃ¤t Linz",
    "MCI-Management Center Innsbruck",
    "Medizinische UniversitÃ¤t Graz",
    "Medizinische UniversitÃ¤t Innsbruck",
    "Medizinische UniversitÃ¤t Wien",
    "MontanuniversitÃ¤t Leoben",
    "Private UniversitÃ¤t fÃ¼r Medizinische Informatik und Technik Tirol",
    "Technikum Wien",
    "Technische UniversitÃ¤t Graz",
    "Technische UniversitÃ¤t Wien",
    "UniversitÃ¤t fÃ¼r angewandte Kunst Wien",
    "UniversitÃ¤t fÃ¼r Bodenkultur Wien",
    "UniversitÃ¤t fÃ¼r kÃ¼nstlerische und industrielle Gestaltung Linz",
    "UniversitÃ¤t fÃ¼r Musik und darstellende Kunst Graz",
    "UniversitÃ¤t fÃ¼r Musik und darstellende Kunst  Wien",
    "UniversitÃ¤t Graz",
    "UniversitÃ¤t Innsbruck",
    "UniversitÃ¤t Klagenfurt",
    "UniversitÃ¤t Linz",
    "UniversitÃ¤t Mozarteum Salzburg",
    "UniversitÃ¤t Salzburg",
    "UniversitÃ¤t Vienna",
    "VeterinÃ¤rmedizinische UniversitÃ¤t Wien",
    "Webster University, Vienna",
    "WirtschaftsuniversitÃ¤t Wien",
    "Australian Catholic University",
    "Australian Correspondence Schools",
    "Australian Defence Force Academy",
    "Australian Lutheran College",
    "Australian Maritime College",
    "Australian National University",
    "Avondale College",
    "Batchelor Institute of Indigenous Tertiary Education",
    "Blue Mountains Hotel School",
    "Bond University",
    "Central Queensland University",
    "Charles Darwin University",
    "Charles Sturt University",
    "Curtin University of Technology",
    "Deakin University",
    "Edith Cowan University",
    "Flinders University of South Australia",
    "Griffith University",
    "Holmes Institute",
    "Institute Of Technology, Australia",
    "International College of Tourism and Hotel Management",
    "James Cook University of North Queensland",
    "La Trobe University",
    "Macquarie University",
    "Marcus Oldham College",
    "Monash University",
    "Murdoch University",
    "Queensland University of Technology",
    "Royal Melbourne Institute of Technology",
    "Southern Cross University",
    "Swinburne University of Technology",
    "University of Adelaide",
    "University of Ballarat",
    "University of Canberra",
    "University of Divinity",
    "University of Melbourne",
    "University of Newcastle",
    "University of New England",
    "University of New South Wales",
    "University of Notre Dame Australia",
    "University of Queensland",
    "University of South Australia",
    "University of Southern Queensland",
    "University of Sydney",
    "University of Tasmania",
    "University of Technology Sydney",
    "University of the Sunshine Coast",
    "University of Western Australia",
    "University of Western Sydney",
    "University of Wollongong",
    "Academy of Public Administration",
    "Azerbaijan Diplomatic Academy",
    "Azerbaijan International University",
    "Azerbaijan Medical University",
    "Azerbaijan National Conservatorie",
    "Azerbaijan State Economic University",
    "Azerbaijan State Oil Academy",
    "Azerbaijan Technical University",
    "Azerbaijan Technology University",
    "Azerbaijan Toursim Institute",
    "Azerbaijan University",
    "Azerbaijan University ol Languages",
    "Baki Business University",
    "Baku Slavic University",
    "Baku State University",
    "Ganja State University",
    "Khazar University",
    "Lankaran State University",
    "Nakhchivan Private University",
    "Nakhchivan State University",
    "National Aviation Academy",
    "Odlar Yurdu University",
    "Police Academy",
    "Qafqaz University",
    "Sumgait State University",
    "Western University",
    "American University",
    "International Burch University",
    "International University of Sarajevo",
    "International University of Travnik",
    "Sarajevo Film Academy",
    "Slobomir P Univerzitet",
    "University of Banja Luka",
    "University of Bihac",
    "University of East Srarajevo",
    "University of Mostar",
    "University of Sarajevo",
    "University of Tuzla",
    "University of Zenica",
    "University Vitez In Travnik",
    "Univerzitet u Mostaru \"Dzemal Bijedic\"",
    "University of the West Indies, Cave Hill",
    "Ahsanullah University of Science & Technology",
    "American International University - Bangladesh",
    "Asa University Bangladesh",
    "Asian University of Bangladesh",
    "Atish Dipankar University",
    "Bangabandhu Sheikh Mujibur Rahman Agricultural University",
    "Bangabandhu Sheikh Mujibur Rahman Medical University",
    "Bangladesh Agricultural University",
    "Bangladesh Open University",
    "Bangladesh University",
    "Bangladesh University of Business & Technology",
    "Bangladesh University of Engineering and Technology",
    "Bangladesh University of Professionals",
    "Bangladesh University of Textiles",
    "Begum Rokeya University, Rangpur",
    "BGC Trust University, Bangladesh",
    "Brac University",
    "Chittagong Independent University",
    "Chittagong University of Engineering and Technology",
    "City University",
    "Comilla University",
    "Daffodil International University",
    "Darul Ihsan University",
    "Dhaka International University",
    "Dhaka University of Engineering and Technology",
    "East Delta University",
    "Eastern University",
    "East West University",
    "East-West University, Mohakhali",
    "Green University of Bangladesh",
    "Hajee Mohammad Danesh Science and Technology University",
    "IBAIS University",
    "Independent University, Bangladesh",
    "International Culture University",
    "International Islamic University Chittagong",
    "International University of Business Agriculture and Technology",
    "Islamic University Kushtia",
    "Islamic University of Technology",
    "Jagannath University",
    "Jahangirnagar University",
    "Jatiya Kabi Kazi Nazrul Islam University",
    "Khulna University",
    "Khulna University of Engineering And Technology",
    "Leading University",
    "Manarat International University",
    "Mawlana Bhashani Science And Technology University",
    "Metropolitan University",
    "Military Institute of Science and Technology",
    "National University",
    "Noakhali University of Science and Technology",
    "North East University Bangladesh",
    "Northern University Bangladesh",
    "North South University",
    "Pabna University of Science and Technology",
    "Patuakhali Science and Technology University",
    "People's University of Bangladesh",
    "Premier University",
    "Presidency University",
    "Queens University",
    "Rajshahi University of Engineering and Technology",
    "Shahjalal University of Science and Technology",
    "Southeast University",
    "Southern University Bangladesh",
    "Stamford University",
    "Sylhet Agricultural University",
    "Sylhet Engineering College",
    "Sylhet International University",
    "United International University",
    "University of Asia Pacific, Dhanmondi",
    "University of Chittagong",
    "University of Development Alternative",
    "University of Dhaka",
    "University of Information Technology & Sciences",
    "University of Liberal Arts",
    "University of Rajshahi",
    "University of Science & Technology Chittagong",
    "World University of Bangladesh",
    "Brexgata University Academy",
    "Brussels Management School (ICHEC)",
    "Brussels School of International Studies",
    "College of Europe",
    "Continental Theological Seminary",
    "ECAM - Institut SupÃ©rieur Industriel",
    "EHSAL - Europese Hogeschool Brussel",
    "Erasmushogeschool Brussel",
    "European Carolus Magnus University",
    "European International University",
    "Evangelische Theologische Faculteit, Leuven",
    "FacultÃ© Polytechnique de Mons",
    "FacultÃ©s Universitaires Catholiques de Mons",
    "FacultÃ©s Universitaires Notre-Dame de la Paix",
    "FacultÃ©s Universitaires Saint-Louis",
    "FacultÃ© Universitaire des Sciences Agronomiques de Gembloux",
    "Fondation Universitaire Luxembourgeoise",
    "Hasselt University",
    "Hogere Zeevaartschool - Maritime Academy",
    "Hogeschool Antwerpen",
    "Hogeschool voor Wetenschap en Kunst (VLEKHO), Brussel",
    "Hogeschool voor Wetenschap & Kunst",
    "Hogeschool West-Vlaanderen (TU)",
    "Karel De Grote Hogeschool",
    "Katholieke Hogeschool Kempen",
    "Katholieke Hogeschool Leuven",
    "Katholieke Hogeschool Limburg",
    "Katholieke Universiteit Brussel",
    "Katholieke Universiteit Leuven",
    "Katholieke Universiteit Leuven, Campus Kortrijk",
    "Royal Military Academy",
    "Thierry Graduate School of Leadership",
    "United Business Institute",
    "UniversitÃ© Catholique de Louvain",
    "UniversitÃ© de LiÃ¨ge",
    "UniversitÃ© de Mons-Hainaut",
    "Universiteit Antwerpen",
    "Universiteit Antwerpen Management School",
    "Universiteit Antwerpen, UFSIA",
    "Universiteit Gent",
    "UniversitÃ© Libre de Bruxelles",
    "Vesalius College",
    "Vlerick Leuven Gent Management School",
    "Vrije Universiteit Brussel",
    "UniversitÃ© de Ouagadougou",
    "Academy of Economics \"Dimitur A. Tscenov\"",
    "Academy of Music, Dance and Fine Arts",
    "Agricultural University of Plovdiv",
    "American University in Bulgaria",
    "Bourgas Free University",
    "Bourgas University \"Prof. Assen Zlatarov\"",
    "City University Programs in Bulgaria",
    "International University College",
    "Medical University of Sofia",
    "Medical University Pleven",
    "Medical University Plovdiv",
    "Medical University Varna",
    "Military University Shoumen",
    "National Academy for Theatre and Film Arts \"Krustju Sarafov\"",
    "National Academy of Arts",
    "National Academy of Music \"Pantcho Vladigerov\"",
    "National Sports Academy Sofia",
    "New Bulgarian University",
    "Shoumen University \"Konstantin Preslavski\"",
    "Sofia University \"St. Kliment Ohridski\"",
    "South-West University \"Neofit Rilski\"",
    "Technical University of Gabrovo",
    "Technical University of Sofia",
    "Technical University of Varna",
    "Trakia University Stara Zagora",
    "University of Architecture, Civil Engineering and Geodesy",
    "University of Chemical Technology and Metallurgy",
    "University of Economics Varna",
    "University of Food Technology",
    "University of Forestry Sofia",
    "University of Mining and Geology \"St. Ivan Rils\"",
    "University of National and World Economy",
    "University of Plovdiv",
    "University of Rousse",
    "Varna Free University",
    "Veliko Turnovo University \"Cyril and Methodius\"",
    "Al Ahlia University",
    "Ama International University",
    "Applied Science University",
    "Arabian Gulf University",
    "Arab Open University",
    "Bahrain Polytechnic",
    "Gulf University College",
    "New York Instiute of Technology",
    "RCSI-Medical University of Bahrain",
    "The Kingdom University",
    "University College Bahrain",
    "University of Bahrain",
    "Hope Africa University",
    "UniversitÃ© du Burundi",
    "UniversitÃ© LumiÃ¨re de Bujumbura",
    "Espam Formation University",
    "Houdegbe North American University Benin",
    "UniversitÃ© d'Abomey-Calavi (UAC)",
    "Bermuda College",
    "Institut Teknologi Brunei",
    "Universiti Islam Sultan Sharif Ali",
    "University of Brunei Darussalam",
    "Escuela Militar de IngenierÃ­a",
    "Universidad Adventista de Bolivia",
    "Universidad Amazonica de Pando",
    "Universidad Andina SimÃ³n Bolivar",
    "Universidad AutÃ³noma del Beni \"JosÃ© BalliviÃ¡n\"",
    "Universidad AutÃ³noma Gabriel RenÃ© Moreno",
    "Universidad AutÃ³noma Juan Misael Saracho",
    "Universidad AutÃ³noma TomÃ¡s FrÃ­as",
    "Universidad CatÃ³lica Boliviana, Cochabamba",
    "Universidad CatÃ³lica Boliviana, La Paz",
    "Universidad CatÃ³lica Boliviana, Santa Cruz",
    "Universidad CatÃ³lica Boliviana, Tarija",
    "Universidad Central",
    "Universidad de Aquino Bolivia",
    "Universidad Domingo Savio",
    "Universidad Empresarial Mateo Kuljis",
    "Universidad Juan Misael Saracho",
    "Universidad Los Andes",
    "Universidad Mayor de San AndrÃ©s",
    "Universidad Mayor de San SimÃ³n",
    "Universidad Nacional Siglo XX Llallagua",
    "Universidad Nuestra Senora de La Paz",
    "Universidad NUR",
    "Universidad Privada Abierta Latinoamericana",
    "Universidad Privada Boliviana",
    "Universidad Privada del Valle",
    "Universidad Privada de Santa Cruz de la Sierra",
    "Universidad Privada Franz Tamayo (UNIFRANZ)",
    "Universidad Salesiana de Bolivia",
    "Universidad San Francisco Xavier",
    "Universidad San Francisco Xavier de Chuquisaca",
    "Universidad TÃ©cnica de Oruro",
    "Centro Regional UniversitÃ¡rio de EspirÃ­to Santo do Pinhal",
    "Centro UniversitÃ¡rio Adventista de SÃ£o Paulo",
    "Centro UniversitÃ¡rio Barao de Maua",
    "Centro UniversitÃ¡rio Claretiano",
    "Centro UniversitÃ¡rio de Araraquara",
    "Centro UniversitÃ¡rio de JoÃ£o Pessoa",
    "Centro UniversitÃ¡rio Monte Serrat",
    "Centro UniversitÃ¡rio Newton Paiva",
    "Centro UniversitÃ¡rio Plinio Leite",
    "Centro UniversitÃ¡rio Senac",
    "Centro UniversitÃ¡rio Serra dos Ã“rgÃ£os",
    "EMESCAM - Escola Superior de CiÃªncias da Santa Casa de MisericÃ³rdia de VitÃ³ria",
    "FAAP - FundaÃ§Ã£o Armando Alvares Penteado",
    "University of Arkansas at Little Rock",
    "University of Arkansas at Monticello",
    "University of Arkansas at Pine Bluff",
    "University of Arkansas for Medical Sciences",
    "University of Arkansas (System)",
    "University of Baltimore",
    "University of Bridgeport",
    "University of California, Berkeley",
    "University of California, Davis",
    "University of California, Hastings College of Law",
    "University of California, Irvine",
    "University of California, Los Angeles",
    "University of California, Merced",
    "University of California, Oakland",
    "University of California, Riverside",
    "University of California, San Diego",
    "University of California, San Francisco",
    "University of California, Santa Barbara",
    "University of California, Santa Cruz",
    "University of California System",
    "University of Central Arkansas",
    "University of Central Florida",
    "University of Central Missouri",
    "University of Central Oklahoma",
    "University of Central Texas",
    "University of Charleston",
    "University of Charleston South Carolina",
    "University of Chicago",
    "University of Cincinnati",
    "University of Colorado at Boulder",
    "University of Colorado at Colorado Springs",
    "University of Colorado at Denver",
    "University of Colorado Health Sciences Center",
    "University of Connecticut",
    "University of Connecticut at Avery Point",
    "University of Connecticut at Hartford",
    "University of Connecticut at Stamford",
    "University of Connecticut at Waterbury",
    "University of Connecticut Health Center",
    "University of Dallas",
    "University of Dayton",
    "University of Delaware",
    "University of Denver",
    "University of Detroit Mercy",
    "University of Dubuque",
    "University of Evansville",
    "University of Findlay",
    "University of Florida",
    "University of Georgia",
    "University of Great Falls",
    "University of Hartford",
    "University of Hawaii - Hilo",
    "University of Hawaii - Manoa",
    "University Of Hawaii - System",
    "University of Hawaii - West Oahu",
    "University of Health Sciences",
    "University of Houston",
    "University of Houston, Clear Lake",
    "University of Houston, Downtown",
    "University of Houston, Victoria",
    "University of Idaho",
    "University of Illinois",
    "University of Illinois at Chicago",
    "University of Illinois at Springfield",
    "University of Illinois at Urbana-Champaign",
    "University of Indianapolis",
    "University of Iowa",
    "University of Kansas",
    "University of Kentucky",
    "University of La Verne",
    "University of Louisiana at Lafayette",
    "University of Louisiana at Monroe",
    "University of Louisville",
    "University of Maine, Augusta",
    "University of Maine, Farmington",
    "University of Maine, Fort Kent",
    "University of Maine, Machias",
    "University of Maine, Orono",
    "University of Maine, Presque Isle",
    "University of Maine (System)",
    "University of Management & Technology",
    "University of Mary",
    "University of Mary Hardin-Baylor",
    "University of Maryland at Baltimore",
    "University of Maryland at College Park",
    "University of Maryland Baltimore County",
    "University of Maryland Eastern Shore",
    "University of Maryland Medicine",
    "University of Maryland (System)",
    "University of Maryland University College",
    "University of Massachusetts at Amherst",
    "University of Massachusetts at Boston",
    "University of Massachusetts at Dartmouth",
    "University of Massachusetts at Lowell",
    "University of Massachusetts Medical Center at Worcester",
    "University of Massachusetts (System)",
    "University of Medicine and Dentistry of New Jersey",
    "University of Memphis",
    "University of Miami",
    "University of Michigan - Ann Arbor",
    "University of Michigan - Dearborn",
    "University of Michigan - Flint",
    "University of Minnesota - Crookston",
    "University of Minnesota - Duluth",
    "University of Minnesota - Morris",
    "University of Minnesota - Twin Cities Campus",
    "University of Mississippi",
    "University of Mississippi Medical Center",
    "University of Missouri - Columbia",
    "University of Missouri - Kansas City",
    "University of Missouri - Saint Louis",
    "University of Mobile",
    "University of Montana",
    "University of Montana Western",
    "University of Montevallo",
    "University of Nebraska - Kearney",
    "University of Nebraska - Lincoln",
    "University of Nebraska Medical Center",
    "University of Nebraska - Omaha",
    "University of Nebraska (System)",
    "University of Nevada - Las Vegas",
    "University of Nevada - Reno",
    "University of New England",
    "University of New England, Westbrook College Campus",
    "University of New Hampshire",
    "University of New Hampshire - Manchester",
    "University of New Haven",
    "University of New Mexico",
    "University of New Orleans",
    "University of North Alabama",
    "University of North America",
    "University of North Carolina at Asheville",
    "University of North Carolina at Chapel Hill",
    "University of North Carolina at Charlotte",
    "University of North Carolina at Greensboro",
    "University of North Carolina at Pembroke",
    "University of North Carolina at Wilmington",
    "University of North Dakota",
    "University of Northern Colorado",
    "University of Northern Iowa",
    "University of Northern Virginia",
    "University of Northern Washington",
    "University of North Florida",
    "University of North Texas",
    "University of North Texas Health Science Center at Fort Worth",
    "University of NorthWest",
    "University of Notre Dame",
    "University of Oklahoma",
    "University of Oklahoma Health Sciences Center",
    "University of Oregon",
    "University of Osteopathic Medicine and Health Science",
    "University of Pennsylvania",
    "University of Phoenix",
    "University of Pittsburgh",
    "University of Pittsburgh at Bradford",
    "University of Pittsburgh at Greensburg",
    "University of Pittsburgh at Johnstown",
    "University of Portland",
    "University of Puget Sound",
    "University of Redlands",
    "University of Rhode Island",
    "University of Richmond",
    "University of Rio Grande",
    "University of Rochester",
    "University of San Diego",
    "University of San Francisco",
    "University of Science and Arts of Oklahoma",
    "University of Scranton",
    "University of Sioux Falls",
    "University of South Alabama",
    "University of South Carolina",
    "University of South Carolina - Aiken",
    "University of South Carolina - Beaufort",
    "University of South Carolina - Lancaster",
    "University of South Carolina - Salkehatchie",
    "University of South Carolina - Spartanburg",
    "University of South Carolina - Sumter",
    "University of South Carolina - Union",
    "University of South Dakota",
    "University of Southern California",
    "University of Southern Indiana",
    "University of Southern Maine",
    "University of Southern Mississippi",
    "University of South Florida",
    "University of St. Francis",
    "University of St. Thomas, Houston",
    "University of St. Thomas, St. Paul",
    "University of Tampa",
    "University of Tennessee - Chattanooga",
    "University of Tennessee - Knoxville",
    "University of Tennessee - Martin",
    "University of Tennessee - Memphis",
    "University of Tennessee Space Institute",
    "University of Texas",
    "University of Texas at Arlington",
    "University of Texas at Austin",
    "University of Texas at Brownsville",
    "University of Texas at Dallas",
    "University of Texas at El Paso",
    "University of Texas at San Antonio",
    "University of Texas at Tyler",
    "University of Texas Health Center at Houston",
    "University of Texas Health Center at Tyler",
    "University of Texas Health Science Center at San Antonio",
    "University of Texas M.D. Anderson Cancer Center",
    "University of Texas Medical Branch Galveston",
    "University of Texas of the Permian Basin",
    "University of Texas Pan American",
    "University of Texas Southwestern Medical Center at Dallas",
    "University of the Arts",
    "University of the District of Columbia",
    "University of the Incarnate World",
    "University of the Ozarks",
    "University of the Pacific",
    "University of the Sciences in Philadelphia",
    "University of the South",
    "University of the Southwest",
    "University of Toledo",
    "University of Tulsa",
    "University of Utah",
    "University of Vermont",
    "University of Virginia",
    "University of Virginia, College at Wise",
    "University of Washington",
    "University of Washington, Tacoma",
    "University of West Alabama",
    "University of West Florida",
    "University of West Los Angeles",
    "University of Wisconsin - Eau Claire",
    "University of Wisconsin - Green Bay",
    "University of Wisconsin - La Crosse",
    "University of Wisconsin - Madison",
    "University of Wisconsin - Milwaukee",
    "University of Wisconsin - Oshkosh",
    "University of Wisconsin - Parkside",
    "University of Wisconsin - Platteville",
    "University of Wisconsin - River Falls",
    "University of Wisconsin - Stevens Point",
    "University of Wisconsin - Stout",
    "University of Wisconsin - Superior",
    "University of Wisconsin - Whitewater",
    "University of Wyoming",
    "Upper Iowa University",
    "Urbana University",
    "Ursinus College",
    "Ursuline College",
    "Utah State University",
    "Utah Valley State College",
    "Utica College",
    "Valdosta State University",
    "Valley City State University",
    "Valley Forge Christian College",
    "Valparaiso University",
    "Vanderbilt University",
    "VanderCook College of Music",
    "Vanguard University of Southern California",
    "Vassar College",
    "Vennard College",
    "Vermont Law School",
    "Vermont Technical College",
    "Villa Julie College",
    "Villanova University",
    "Virginia College",
    "Virginia Commonwealth University",
    "Virginia Intermont College",
    "Virginia International University",
    "Virginia Military Institute",
    "Virginia Polytechnic Institute and State University (Virginia Tech)",
    "Virginia State University",
    "Virginia Union University",
    "Virginia Wesleyan College",
    "Viterbo College",
    "Voorhees College",
    "Wabash College",
    "Wagner College",
    "Wake Forest University",
    "Walden University",
    "Walla Walla College",
    "Walsh College of Accountancy and Business Administration",
    "Walsh University",
    "Warner Pacific College",
    "Warner Southern College",
    "Warren Wilson College",
    "Wartburg College",
    "Washburn University",
    "Washington and Lee University",
    "Washington Bible College",
    "Washington College",
    "Washington State University",
    "Washington State University, Spokane",
    "Washington State University, Tri-Cities",
    "Washington State University, Vancouver",
    "Washington University in St. Louis",
    "Wayland Baptist University",
    "Waynesburg College",
    "Wayne State College",
    "Wayne State University",
    "Webber College",
    "Webb Institute",
    "Weber State University",
    "Webster University",
    "Webster University North Florida",
    "Weill Medical College of Cornell University",
    "Wellesley College",
    "Wells College",
    "Wentworth Institute of Technology",
    "Wesleyan College",
    "Wesleyan University",
    "Wesley College",
    "Wesley College Mississippi",
    "Westbrook University",
    "West Chester University of Pennsylvania",
    "West Coast University",
    "Western Baptist College",
    "Western Bible College",
    "Western Carolina University",
    "Western Connecticut State University",
    "Western Governors University",
    "Western Illinois University",
    "Western International University",
    "Western Kentucky University",
    "Western Maryland College",
    "Western Michigan University",
    "Western New England College",
    "Western New Mexico University",
    "Western Oregon University",
    "Western State College",
    "Western States Chiropractic College",
    "Western State University College of Law",
    "Western State University College of Law - Orange County",
    "Western Washington University",
    "Westfield State College",
    "West Liberty State College",
    "Westminster College Fulton",
    "Westminster College New Wilmington",
    "Westminster College of Salt Lake City",
    "Westmont College",
    "West Suburban College of Nursing",
    "West Texas A&M University",
    "West Virginia School of Osteopathic Medicine",
    "West Virginia State College",
    "West Virginia University",
    "West Virginia University Institute of Technology",
    "West Virginia Wesleyan College",
    "Westwood College",
    "Wheaton College Massachusetts",
    "Wheeling Jesuit University",
    "Wheelock College",
    "Whitman College",
    "Whittier College",
    "Whitworth College",
    "Wichita State University",
    "Widener University",
    "Wilberforce University",
    "Wilbur Wright College",
    "Wiley College",
    "Wilkes University",
    "Willamette University",
    "William Carey College",
    "William Jewell College",
    "William Mitchell College of Law",
    "William Paterson University",
    "William Penn College",
    "Williams Baptist College",
    "Williams College",
    "William Tyndale College",
    "William Woods University",
    "Wilmington College",
    "Wilmington College",
    "Wilson College",
    "Wingate University",
    "Winona State University",
    "Winston-Salem State University",
    "Winthrop University",
    "Wisconsin Lutheran College",
    "Wisconsin School of Professional Psychology",
    "Wittenberg University",
    "Wofford College",
    "Woodbury University",
    "Worcester Polytechnic Institute",
    "Worcester State College",
    "Wright Institute",
    "Wright State University",
    "Xavier University",
    "Xavier University of Louisiana",
    "Yale University",
    "Yeshiva University",
    "York College Nebraska",
    "York College of Pennsylvania",
    "Yorker International University",
    "York University",
    "Youngstown State University",
    "Insituto Universitario - Centro Latinoamericano de Economia Humana - IU Claeh",
    "Universidad CatÃ³lica del Uruguay",
    "Universidad de la Empresa (UDE)",
    "Universidad de la RepÃºblica",
    "Universidad de Montevideo",
    "Universidad ORT Uruguay",
    "Ferghana Politechnical Institute",
    "International Business School Kelajak ILMI",
    "Kokand State Pedagogical Institute",
    "Management Development Institute of Singapore, Tashkent",
    "National University of Uzbekistan",
    "Nukus State Teachers Training Institute",
    "Samarkand State University",
    "Tashkent Automobile and Roads Institute",
    "Tashkent Institute of Irrigation and Melioration",
    "Tashkent Islam University",
    "Tashkent Medical Academy",
    "Tashkent Pharmaceutical Institute",
    "Tashkent School of Finance",
    "Tashkent State Agrarian University",
    "Tashkent State Technical University",
    "Tashkent State University of Economics",
    "Tashkent State University of Oriental Studies",
    "Tashkent University of Information Technologies",
    "Turin Polytechnic University In Tashkent",
    "University of World Economy and Diplomacy",
    "Uzbek State World Languages University",
    "Westminster International University in Tashkent",
    "Athenaeum Pontificium Regina Apostolorum",
    "Pontifcia UniversitÃ  Gregoriana",
    "Pontifcia Universitas a S.Thomas Aquinate in Urbe",
    "Pontifcia Universitas Lateranensis",
    "Pontifcia UniversitÃ  Urbaniana",
    "UniversitÃ  Pontifcia Salesiana",
    "Trinity University School of Medicine",
    "Universidad Bicentenaria de Aragua",
    "Universidad Bolivariana de Venezuela",
    "Universidad CatÃ³lica Andres Bello",
    "Universidad CatÃ³lica Cecilio Acosta",
    "Universidad CatÃ³lica del TÃ¡chira",
    "Universidad Central de Venezuela",
    "Universidad Centro Occidental Lisandro Alvarado",
    "Universidad de Carabobo",
    "Universidad de Los Andes",
    "Universidad del Zulia",
    "Universidad de Oriente",
    "Universidad Dr. Rafael Belloso ChacÃ­n",
    "Universidad Fermin Toro",
    "Universidad Gran Mariscal de Ayacucho",
    "Universidad JosÃ© Antonio PÃ¡ez",
    "Universidad JosÃ© Maria Vargas",
    "Universidad Metropolitana",
    "Universidad MonteÃ¡vila",
    "Universidad Nacional Abierta",
    "Universidad Nacional Experimental de Guayana",
    "Universidad Nacional Experimental de la Fuerza Armada",
    "Universidad Nacional Experimental de los Llanos Occidentales \"Ezequiel Zamora\"",
    "Universidad Nacional Experimental del TÃ¡chira",
    "Universidad Nacional Experimental \"Francisco de Miranda\"",
    "Universidad Nacional Experimental PolitÃ©cnica \"Antonio JosÃ© de Sucre\"",
    "Universidad Nacional Experimental \"Rafael Maria Baralt\"",
    "Universidad Nacional Experimental Romulo Gallegos",
    "Universidad Nacional Experimental \"SimÃ³n Rodriguez\"",
    "Universidad Nacional Experimental Sur del Lago \"JesÃºs Maria Semprum\"",
    "Universidad Nueva Esparta",
    "Universidad PedagÃ³gica Experimental Libertador",
    "Universidad Rafael Urdaneta",
    "Universidad Santa Maria Caracas",
    "Universidad SimÃ³n Bolivar",
    "Universidad TecnolÃ³gica del Centro",
    "Universidad Valle del Momboy",
    "Universidad Yacambu",
    "University of the Virgin Islands",
    "Banking University of Ho Chi Minh City",
    "Binh Duong University",
    "Can-Tho University",
    "Danang College Of Technology",
    "Foreign Trade University",
    "FPT University",
    "Hai Duong University",
    "Hanoi Medical University",
    "Hanoi National Economics University",
    "Hanoi Open University",
    "Hanoi University of Architecture",
    "Hanoi University of Civil Engineering",
    "Hanoi University of Mining and Geology",
    "Hanoi University of Science",
    "Hanoi University of Science & Technology",
    "Ho Chi Minh City Open University",
    "Ho Chi Minh City University of Agriculture and Forestry",
    "Ho Chi Minh City University of Architecture",
    "Ho Chi Minh City University of Economics",
    "Ho Chi Minh City University of Foreign Languages and Information Technology",
    "Ho Chi Minh City University of Law",
    "Ho Chi Minh City University of Medicine and Pharmacy",
    "Ho Chi Minh City University of Natural Sciences",
    "Ho Chi Minh City University of Pedagogics",
    "Ho Chi Minh City University of Social Sciences and Humanities",
    "Ho Chi Minh City University of Technology",
    "Ho Chi Minh City University of Transport",
    "Hong Bang University International",
    "Hue University",
    "Hue University of Agriculture and Forestry",
    "Institute of Finance",
    "Posts & Telecommunications Institute of Technology",
    "RMIT International University Vietnam",
    "Saigon University",
    "Tay Nguyen University",
    "Thainguyen University of Agriculture and Forestry",
    "University of Da Lat",
    "University of Da Nang",
    "University of Technical Education Ho Chi Minh City",
    "University of Transport and Communications",
    "Vietnam Maritime University",
    "Vietnam National University Hanoi",
    "Vietnam National University Ho Chi Minh City",
    "Vietnam National University of Agriculture",
    "Water Resources University",
    "National University of Samoa",
    "University of the South Pacific School of Agriculture",
    "Alahgaff University",
    "Al-Eman University",
    "Al-Nasser University",
    "Hadhramout University of Science and Technology",
    "Hodeidah University",
    "Queen Arwa University",
    "Saba University",
    "Sana'a University",
    "Taiz University",
    "Thamar University",
    "University of Aden",
    "University of Modern Sciences",
    "University of Science and Technology Sana'a",
    "Yemenia University",
    "Cape Peninsula University of Technology",
    "Central University of Technology, Free State",
    "Durban Institute of Technology",
    "Nelson Mandela Metropolitan University",
    "Rhodes University",
    "Tshwane University of Technology",
    "University of Cape Town",
    "University of Fort Hare",
    "University of Johannesburg",
    "University of KwaZulu-Natal",
    "University of Limpopo",
    "University of North West",
    "University of Pretoria",
    "University of South Africa",
    "University of Stellenbosch",
    "University of the Free State",
    "University of the Western Cape",
    "University of Venda",
    "University of Witwatersrand",
    "University of Zululand",
    "Vaal University of Technology",
    "Walter Sisulu University for Technology and Science",
    "Cavendish University",
    "Copperbelt University",
    "Mulungushi University",
    "Northrise University",
    "Rusangu University",
    "University of Lusaka",
    "University of Zambia",
    "Zambian Open University",
    "Africa University",
    "Bindura University of Science Education",
    "Catholic University in Zimbabwe",
    "Chinhoyi University of Technology",
    "Great Zimbabwe University",
    "Harare Institute of Technology",
    "Lupane State University",
    "Midlands State University",
    "National University of Science and Technology Bulawayo",
    "Reformed Church University",
    "Solusi University",
    "University of Zimbabwe",
    "Women's University in Africa",
    "Zimbabwe Ezekiel Guti University",
    "Zimbabwe Open University",
    "Not Listed"
]

major_list = ['Accounting', 'Actuarial Science', 'Advertising', 'Aerospace Engineering', 'Agriculture', 'Agronomy', 'Animation', 'Anthropology', 'Architecture', 'Artificial Intelligence', 'Astronomy', 'Aviation Management', 'Banking', 'Biochemistry', 'Bioinformatics', 'Biology', 'Biomedical Engineering', 'Biotechnology', 'Blockchain Technology', 'Business Administration', 'Ceramic Engineering', 'Chemical Engineering', 'Chemistry', 'Civil Engineering', 'Climate Science', 'Cloud Computing', 'Cognitive Science', 'Communication and Management of Creative Industries', 'Computer Science', 'Construction Management', 'Corporate Law', 'Criminal Justice', 'Cybersecurity', 'Dairy Technology', 'Data Science', 'Dentistry', 'Development Studies', 'Early Childhood Education', 'Economics', 'Education', 'Electrical Engineering', 'Energy Management', 'English Literature', 'Entrepreneurship', 'Environmental Engineering', 'Environmental Science', 'Fashion Design', 'Film Studies', 'Finance', 'Fine Arts', 'Fisheries Science', 'Food Technology', 'Forensic Science', 'Forestry', 'Game Development', 'Gender Studies', 'Genetics', 'Geography', 'Geology', 'Graphic Design', 'History', 'Horticulture', 'Hospitality Management', 'Hotel Management', 'Industrial Design', 'Industrial Engineering', 'Information Technology', 'Interior Design', 'International Business', 'International Law', 'International Relations', 'Journalism', 'Law', 'Linguistics', 'Logistics Management', 'Management', 'Marine Engineering', 'Maritime Studies', 'Mass Communication', 'Materials Science', 'Mathematics', 'Mechanical Engineering', 'Mechatronics Engineering', 'Media Studies', 'Medicine', 'Microbiology', 'Mining Engineering', 'Molecular Biology', 'Nanotechnology', 'Neuroscience', 'Nuclear Engineering', 'Nursing', 'Nutrition & Dietetics', 'Oceanography', 'Operations Management', 'Petroleum Engineering', 'Pharmacy', 'Philosophy', 'Physical Education', 'Physics', 'Physiotherapy', 'Political Science', 'Political Marketing', 'Polymer Science', 'Project Management', 'Psychology', 'Public Administration', 'Public Health', 'Public Policy', 'Public Relations', 'Real Estate Management', 'Renewable Energy Engineering', 'Robotics Engineering', 'Rural Development', 'Sociology', 'Software Engineering', 'Special Education', 'Sports Science', 'Statistics', 'Structural Engineering', 'Supply Chain Management', 'Sustainability Studies', 'Taxation', 'Telecommunications Engineering', 'Textile Engineering', 'Tourism Management', 'Translation Studies', 'UI/UX Design', 'Urban Planning', 'Urban Studies', 'Veterinary Science', 'Not Listed']
certification_list = ['ACCA', 'APR Certification', 'AWS Certified Solutions Architect', 'Actuarial Exams (SOA/IFoA)', 'Adobe Certified Professional', 'Autodesk AutoCAD Professional', 'Bar Council License', 'Board Certification', 'CISSP', 'Certified Energy Manager (CEM)', 'Certified Ethical Hacker (CEH)', 'Certified Financial Planner (CFP)', 'Certified Public Accountant (CPA)', 'Certified Public Manager', 'Certified Translator', 'Chartered Accountant (CA)', 'Chartered Financial Analyst (CFA)', 'Cisco CCIE', 'Cisco CCNA', 'Cisco CCNP', 'Clinical Research Certification', 'CompTIA A+', 'CompTIA Network+', 'CompTIA Security+', 'Digital Marketing Certification', 'Environmental Impact Assessment Certification', 'Food Safety Certification', 'Forensic Science Certification', 'Google Professional Certificate', 'HACCP', 'Huawei HCIA/HCIP', 'HubSpot Certification', 'IELTS / TOEFL / DELF', 'ISO Lead Auditor', 'International Arbitration Certification', 'LEED Accredited Professional', 'Laboratory Technician Certification', 'Microsoft Azure Certification', 'NCIDQ Certification', 'NCLEX-RN', 'Oracle Professional Certification', 'PLAB', 'PMP', 'PRINCE2', 'Pharmacist Licensure Exam', 'Professional Engineer (PE)', 'Radiation Safety Certification', 'Registered Architect License', 'Siemens Professional Certification', 'Six Sigma Black Belt', 'Six Sigma Green Belt', 'SolidWorks Professional (CSWP)', 'TESOL', 'Teaching License', 'USMLE', 'UX Certification (NN/g)', 'Unity Certified Developer', 'Not Listed']
