name: Workflow
on:
  push:
    branches:
      - '**'
      
env:
  DEBUG: true
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
  GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
  GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
  GOOGLE_REDIRECT_URI: ${{secrets.GOOGLE_REDIRECT_URI}}
  LINKEDIN_CLIENT_ID: test
  LINKEDIN_CLIENT_SECRET: test
  LINKEDIN_REDIRECT_URI: http://example.com
  FACEBOOK_APP_ID: ${{secrets.FACEBOOK_APP_ID}}
  FACEBOOK_APP_SECRET: ${{secrets.FACEBOOK_APP_SECRET}}
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_STORAGE_BUCKET_NAME: ${{secrets.AWS_STORAGE_BUCKET_NAME}}
  USE_AWS_S3: False
  AWS_EC2_PRIVATE_KEY: ${{secrets.AWS_EC2_PRIVATE_KEY}}
  AWS_EC2_USER_NAME: ubuntu
  AWS_EC2_STAGING_HOSTNAME: ${{secrets.AWS_EC2_STAGING_HOSTNAME}}
  AWS_EC2_PRODUCTION_HOSTNAME: ${{secrets.AWS_EC2_PRODUCTION_HOSTNAME}}
  FACEBOOK_APP_ID_ANDROID: ${{secrets.FACEBOOK_APP_ID_ANDROID}}
  FACEBOOK_APP_SECRET_ANDROID: ${{secrets.FACEBOOK_APP_SECRET_ANDROID}}
  FACEBOOK_APP_ID_WEB: ${{secrets.FACEBOOK_APP_ID_WEB}}
  FACEBOOK_APP_SECRET_WEB: ${{secrets.FACEBOOK_APP_SECRET_WEB}}
  FACEBOOK_APP_ID_IOS: ${{secrets.FACEBOOK_APP_ID_IOS}}
  FACEBOOK_APP_SECRET_IOS: ${{secrets.FACEBOOK_APP_SECRET_IOS}}

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
#    - name: Run migrations and tests
#      run: |
#        python manage.py test accounts --parallel


  deploy-staging:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Setup SSH key
      run: |
          echo "${{ secrets.AWS_EC2_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

    - name: Deploy to AWS EC2
      if: github.ref == 'refs/heads/staging'
      run: | 
          ssh -o StrictHostKeyChecking=no -i private_key ${AWS_EC2_USER_NAME}@${AWS_EC2_STAGING_HOSTNAME} << 'EOF'
            cd /home
            source environment/venv/bin/activate
            cd code/GTC-backend
            git pull
            pip install -r requirements.txt
            python manage.py migrate account --fake
#            python manage.py collectstatic --noinput
#            sudo systemctl restart gunicorn
#            sudo systemctl restart run_qcluster
#            sudo systemctl restart daphne
#            sudo systemctl restart nginx
          EOF
  
  deploy-production:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Setup SSH key
      if: github.ref == 'refs/heads/master'
      run: |
          echo "${{ secrets.AWS_EC2_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

    - name: Deploy to AWS EC2
      if: github.ref == 'refs/heads/master'
      run: | 
          ssh -o StrictHostKeyChecking=no -i private_key ${AWS_EC2_USER_NAME}@${AWS_EC2_PRODUCTION_HOSTNAME} << 'EOF'
            cd /home
            source environment/venv/bin/activate
            cd code/GTC-backend
            git pull
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn
            sudo systemctl restart run_qcluster
            sudo systemctl restart daphne
            sudo systemctl restart nginx
          EOF